// AUTO-GENERATED BY silc — DO NOT EDIT
/** GAS-lite abilities: cost, cooldown, cues, signals. */

import {
  Color3,
  Color4,
  MeshBuilder,
  ParticleSystem,
  PointLight,
  Texture,
  Vector3,
} from "@babylonjs/core";
import type { AbilityDef } from "../manifest.ts";
import type { BabylonHandles } from "../adapters/babylonScene.ts";
import type { Resources } from "../kernel/resources.ts";
import type { SignalBus } from "../kernel/signals.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { World } from "../kernel/world.ts";
import type { AttributeState } from "./spawn.ts";
import type { Possession } from "./mode.ts";

const cooldowns = new Map<string, number>();

export function createAbilitySystem(
  world: World,
  signals: SignalBus,
  handles: BabylonHandles,
  resources: Resources,
  possession: Possession,
): GameSystem {
  return {
    name: "abilities",
    order: 20,
    update(ctx) {
      for (const [key, t] of [...cooldowns.entries()]) {
        const next = t - ctx.dt;
        if (next <= 0) cooldowns.delete(key);
        else cooldowns.set(key, next);
      }
      const pawnId = possession.pawnId;
      if (pawnId == null) return;
      const abilities = world.getComponent<AbilityDef[]>("abilities", pawnId);
      if (!abilities?.length) return;
      const attrs = world.getComponent<AttributeState[]>("attributes", pawnId) ?? [];

      for (const ability of abilities) {
        const code = keyToCode(ability.key);
        if (!resources.input.consumeKey(code) && !resources.input.keys.has(code)) {
          // Prefer edge trigger via consume on Digit keys each frame once.
        }
      }

      // Edge-trigger: track pressed digits this frame via consumeKey only.
      for (const ability of abilities) {
        const code = keyToCode(ability.key);
        if (!justPressed(resources, code)) continue;
        const cdKey = `${pawnId}:${ability.key}`;
        if ((cooldowns.get(cdKey) ?? 0) > 0) continue;

        let cooldown = ability.cooldown ?? 0.5;
        let cost = ability.cost ?? 0;
        if (ability.ref && resources.data[ability.ref]) {
          const d = resources.data[ability.ref];
          if (d.cooldown != null) cooldown = Number(d.cooldown);
          if (d.cost != null) cost = Number(d.cost);
        }

        if (ability.costAttr && cost > 0) {
          const attr = attrs.find((a) => a.name === ability.costAttr);
          if (!attr || attr.value < cost) continue;
          attr.value -= cost;
        }

        cooldowns.set(cdKey, cooldown);
        const pos = world.worldPosition(pawnId);
        playCues(handles, ability, pos);
        possession.impulse = Math.max(
          possession.impulse,
          maxImpulse(ability),
        );
        signals.emit("ability_cast", {
          name: ability.name,
          key: ability.key,
          x: pos.x,
          y: pos.y,
          z: pos.z,
        });
      }
    },
  };
}

const pressedPrev = new Set<string>();

function justPressed(resources: Resources, code: string): boolean {
  const down = resources.input.keys.has(code);
  const was = pressedPrev.has(code);
  if (down && !was) {
    pressedPrev.add(code);
    return true;
  }
  if (!down) pressedPrev.delete(code);
  return false;
}

function keyToCode(key: string): string {
  if (/^[0-9]$/.test(key)) return `Digit${key}`;
  if (/^[a-zA-Z]$/.test(key)) return `Key${key.toUpperCase()}`;
  if (key === "F1") return "F1";
  return key;
}

function maxImpulse(ability: AbilityDef): number {
  let m = 0;
  for (const fx of ability.effects ?? []) {
    if (fx.type === "camera_impulse") {
      m = Math.max(m, Number(fx.props.strength ?? 0.2));
    }
  }
  return m;
}

function playCues(
  handles: BabylonHandles,
  ability: AbilityDef,
  pos: { x: number; y: number; z: number },
): void {
  for (const fx of ability.effects ?? []) {
    if (fx.type === "dynamic_light") {
      const light = new PointLight(
        `cue_light_${ability.key}`,
        new Vector3(pos.x, pos.y + 1.2, pos.z),
        handles.scene,
      );
      light.intensity = Number(fx.props.intensity ?? 1.2);
      light.range = Number(fx.props.radius_m ?? fx.props.radiusM ?? 5);
      const color = String(fx.props.color ?? "#a8d4ff");
      try {
        light.diffuse = Color3.FromHexString(color);
      } catch {
        light.diffuse = new Color3(0.7, 0.85, 1);
      }
      window.setTimeout(() => light.dispose(), 350);
    }
    if (fx.type === "particle_emitter") {
      const count = Number(fx.props.count ?? 64);
      const ps = new ParticleSystem(`cue_ps_${ability.key}`, count, handles.scene);
      ps.particleTexture = new Texture(
        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==",
        handles.scene,
      );
      ps.emitter = new Vector3(pos.x, pos.y + 1, pos.z);
      ps.minEmitBox = new Vector3(-0.2, 0, -0.2);
      ps.maxEmitBox = new Vector3(0.2, 0.4, 0.2);
      ps.color1 = new Color4(1, 0.95, 0.7, 1);
      ps.color2 = new Color4(0.6, 0.8, 1, 1);
      ps.colorDead = new Color4(0, 0, 0, 0);
      ps.minSize = 0.05;
      ps.maxSize = 0.2;
      ps.minLifeTime = 0.2;
      ps.maxLifeTime = 0.6;
      ps.emitRate = count * 4;
      ps.direction1 = new Vector3(-1, 2, -1);
      ps.direction2 = new Vector3(1, 3, 1);
      ps.gravity = new Vector3(0, -6, 0);
      ps.targetStopDuration = 0.25;
      ps.disposeOnStop = true;
      ps.start();
    }
    if (fx.type === "camera_impulse") {
      // Handled via possession.impulse in camera system.
    }
  }
  // Tiny flash mesh so cues are visible without particles texture issues.
  const flash = MeshBuilder.CreateSphere(
    `cue_flash_${ability.key}`,
    { diameter: 0.4 },
    handles.scene,
  );
  flash.position.set(pos.x, pos.y + 1.1, pos.z);
  window.setTimeout(() => flash.dispose(), 200);
}
