// AUTO-GENERATED BY silc — DO NOT EDIT
/** Unreal-style mode / pawn / controller ownership. */

import type { Groups } from "../kernel/groups.ts";
import type { Resources } from "../kernel/resources.ts";
import type { SignalBus } from "../kernel/signals.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { EntityId, World } from "../kernel/world.ts";
import {
  instantiatePrefab,
  spawnSceneChildren,
  spawnZonesAndEncounters,
} from "./spawn.ts";
import type { BabylonHandles } from "../adapters/babylonScene.ts";

export type Possession = {
  modeId: string;
  pawnId: EntityId | null;
  yaw: number;
  pitch: number;
  impulse: number;
  lastAbility: string | null;
  score: number;
};

export function createFrameworkSystems(
  world: World,
  groups: Groups,
  signals: SignalBus,
  handles: BabylonHandles,
  resources: Resources,
  possession: Possession,
): GameSystem[] {
  const firstPerson =
    handles.firstPerson || resources.manifest.camera?.mode === "first_person";
  let spawnPoint = { x: 0, y: 1, z: 0 };
  /** Depth past which a pawn has left the level and cannot recover. */
  const voidY = -20;
  return [
    {
      name: "modeBoot",
      order: 0,
      async init() {
        const root = world.create("SceneRoot", null);
        spawnSceneChildren(
          world,
          groups,
          handles,
          resources,
          root,
          resources.manifest.scene.children ?? [],
        );
        spawnZonesAndEncounters(world, groups, handles, resources, root);

        const mode = resources.manifest.mode;
        possession.modeId = mode?.id ?? "default";
        for (const spawn of mode?.spawns ?? []) {
          instantiatePrefab(world, groups, handles, resources, spawn.spawn, spawn.overrides, root);
        }

        const possessName = mode?.possess ?? null;
        let pawnId: EntityId | null = null;
        if (possessName) {
          pawnId = world.findByName(possessName);
          if (pawnId == null) {
            for (const [id] of world.query("pawn")) {
              const n = world.nameOf(id);
              if (n === possessName) {
                pawnId = id;
                break;
              }
            }
          }
        }
        if (pawnId == null) {
          const first = world.query("pawn")[0];
          if (first) pawnId = first[0];
        }
        if (pawnId != null) {
          const pawn = world.getComponent<{ possessed: boolean }>("pawn", pawnId);
          if (pawn) pawn.possessed = true;
          possession.pawnId = pawnId;
          spawnPoint = { ...world.worldPosition(pawnId) };
          if (firstPerson) {
            possession.pitch = 0;
            // Hide pawn body meshes in FP.
            const node = handles.nodes.get(pawnId);
            if (node) {
              for (const child of node.getChildMeshes()) {
                child.isVisible = false;
              }
            }
          }
          signals.emit("possessed", { pawnId });
        }

        signals.wireEdges(resources.manifest.signals ?? []);
        signals.connect("ability_cast", (payload) => {
          possession.lastAbility = String((payload as { name?: string })?.name ?? "");
          possession.score += 1;
          void resources.telemetry.event("ability_cast", payload);
        });
        signals.connect("Mode.on_ability_cast", (payload) => {
          possession.lastAbility = String((payload as { name?: string })?.name ?? "cast");
        });

        const run = await resources.run.start(possession.modeId);
        void resources.telemetry.event("run_start", run);
      },
    },
    {
      name: "controller",
      order: 10,
      fixedUpdate() {
        const pawnId = possession.pawnId;
        if (pawnId == null) return;
        if (world.worldPosition(pawnId).y < voidY) {
          world.setTransform(pawnId, { x: spawnPoint.x, y: spawnPoint.y, z: spawnPoint.z });
          world.addComponent("velocity", pawnId, { vx: 0, vy: 0, vz: 0 });
          void resources.telemetry.event("respawn", { reason: "fell_out_of_level" });
          return;
        }
        const movement = world.getComponent<{
          speed: number;
          jumpSpeed?: number;
          sprintMul?: number;
          style?: string;
        }>("movement", pawnId);
        const speed = movement?.speed ?? 5;
        const input = resources.input;
        const lookScale = firstPerson ? 0.0022 : 0.0025;
        // Mouse right → positive yaw → look toward +X when facing +Z (standard FPS).
        possession.yaw += input.mouseDx * lookScale;
        if (firstPerson) {
          possession.pitch = Math.max(
            -1.25,
            Math.min(1.25, possession.pitch + input.mouseDy * lookScale),
          );
        } else {
          possession.pitch = Math.max(
            0.35,
            Math.min(1.4, possession.pitch + input.mouseDy * 0.002),
          );
        }

        const sprinting = input.keys.has("ShiftLeft") || input.keys.has("ShiftRight");
        const mul = sprinting ? (movement?.sprintMul ?? 1.55) : 1;
        const forward = input.forward;
        const strafe = input.strafe;
        const sin = Math.sin(possession.yaw);
        const cos = Math.cos(possession.yaw);
        const vel =
          world.getComponent<{ vx: number; vy: number; vz: number }>("velocity", pawnId) ?? {
            vx: 0,
            vy: 0,
            vz: 0,
          };

        if (forward === 0 && strafe === 0) {
          vel.vx = 0;
          vel.vz = 0;
        } else {
          const moveSpeed = speed * mul;
          vel.vx = (strafe * cos + forward * sin) * moveSpeed;
          vel.vz = (-strafe * sin + forward * cos) * moveSpeed;
        }

        const grounded = world.getComponent<{ value: boolean }>("grounded", pawnId)?.value;
        if (firstPerson && input.consumeKey("Space") && grounded) {
          vel.vy = movement?.jumpSpeed ?? 7.5;
        }

        world.addComponent("velocity", pawnId, vel);
        world.setTransform(pawnId, { yaw: possession.yaw });
      },
    },
  ];
}
