// AUTO-GENERATED BY silc — DO NOT EDIT
/** Prefab instantiate + scene tree spawn (Unity/Godot). */

import type { EntityDef, SpawnDef, ZoneDef } from "../manifest.ts";
import { isSpawnDef } from "../manifest.ts";
import type { Groups } from "../kernel/groups.ts";
import type { PrefabRegistry, Resources } from "../kernel/resources.ts";
import type { EntityId, World } from "../kernel/world.ts";
import {
  attachLight,
  attachMesh,
  syncTransformNode,
  type BabylonHandles,
} from "../adapters/babylonScene.ts";
import {
  buildKitPiece,
  kitColliderParts,
  type KitDef,
  type MaterialDef,
} from "../adapters/kitBuilder.ts";

export type AttributeState = { name: string; value: number; max: number | null };

export function instantiatePrefab(
  world: World,
  groups: Groups,
  handles: BabylonHandles,
  resources: Resources,
  prefabName: string,
  overrides?: SpawnDef["overrides"],
  parent: EntityId | null = null,
): EntityId | null {
  const def = resources.prefabs.get(prefabName);
  if (!def) {
    console.warn(`[silc-game] missing prefab ${prefabName}`);
    return null;
  }
  return spawnEntityDef(world, groups, handles, resources, def, overrides, parent);
}

export function spawnEntityDef(
  world: World,
  groups: Groups,
  handles: BabylonHandles,
  resources: Resources,
  def: EntityDef,
  overrides?: SpawnDef["overrides"],
  parent: EntityId | null = null,
): EntityId {
  const id = world.create(def.name || def.id, parent);
  const src = overrides?.transform ?? def.transform;
  const tx = {
    x: src?.x ?? 0,
    y: src?.y ?? 0,
    z: src?.z ?? 0,
    // Authored yaw is degrees; the runtime works in radians throughout.
    yaw: ((src?.yaw ?? 0) * Math.PI) / 180,
  };
  world.setTransform(id, tx);

  for (const g of def.groups ?? []) groups.add(g, id);

  const node = syncTransformNode(handles, id, def.name || def.id, tx, tx.yaw);
  if (src?.sx != null || src?.sy != null || src?.sz != null) {
    node.scaling.set(src.sx ?? 1, src.sy ?? 1, src.sz ?? 1);
  }

  if (def.mesh) {
    const kitName = resolveKitPiece(def.mesh.asset, resources);
    if (kitName && resources.kit) {
      const meshes = buildKitPiece(
        handles.scene,
        kitName,
        resources.kit,
        resources.kitMaterials,
        node,
      );
      for (const m of meshes) {
        handles.shadowGen?.addShadowCaster(m);
      }
      // Derive collider hull from kit piece size when absent.
      const piece = resources.kit.pieces[kitName];
      if (piece && !def.collider) {
        world.addComponent("collider", id, {
          shape: "box",
          size: Math.max(piece.size.x, piece.size.z),
          hull: {
            aabb: {
              x: piece.size.x,
              y: piece.size.y,
              z: piece.size.z,
            },
          },
          parts: kitColliderParts(piece),
          static: true,
        });
      }
    } else {
      const mesh = attachMesh(
        handles.scene,
        node,
        def.mesh.shape || "box",
        def.mesh.size,
        def.mesh.color,
        handles.shadowGen,
        def.mesh.material ?? undefined,
        resources.kitMaterials,
      );
      // Hide pawn mesh in first-person mode, or in platformer mode when sprite exists
      const isPlatformer = resources.manifest.camera?.mode === "side_scroll";
      const isFirstPerson = resources.manifest.camera?.mode === "first_person";
      if (def.pawn && (isFirstPerson || (isPlatformer && def.sprite))) {
        mesh.isVisible = false;
      }
    }
    world.addComponent("mesh", id, { ...def.mesh });
  }
  if (def.light) {
    attachLight(
      handles.scene,
      node,
      def.light.kind,
      def.light.intensity,
      def.light.color,
      def.light.radiusM ?? 8,
      def.light.castShadows ?? false,
      handles.shadowGen,
    );
    world.addComponent("light", id, { ...def.light });
  }
  if (def.collider) {
    const baked = resources.bake.colliders?.find((c) => c.prefab === def.name);
    const pieceName = def.mesh?.asset ? resolveKitPiece(def.mesh.asset, resources) : null;
    const piece = pieceName && resources.kit ? resources.kit.pieces[pieceName] : null;
    world.addComponent("collider", id, {
      shape: def.collider.shape,
      size: def.collider.size,
      hull: baked ??
        (piece
          ? { aabb: { x: piece.size.x, y: piece.size.y, z: piece.size.z } }
          : def.collider.hull ?? null),
      parts: piece ? kitColliderParts(piece) : null,
      static: !(def.movement || def.pawn || def.npc),
    });
  }
  if (def.movement) {
    let speed = def.movement.speed ?? 5;
    const refName = overrides?.movement?.ref ?? def.movement.ref;
    if (refName && resources.data[refName]?.speed != null) {
      speed = Number(resources.data[refName].speed);
    }
    if (overrides?.movement?.speed != null) speed = overrides.movement.speed;
    world.addComponent("movement", id, {
      style: def.movement.style || "walk",
      speed,
      jumpSpeed: def.movement.jumpSpeed ?? 7.5,
      sprintMul: def.movement.sprintMul ?? 1.55,
    });
    world.addComponent("velocity", id, { vx: 0, vy: 0, vz: 0 });
  }
  if (def.attributes?.length) {
    const attrs: AttributeState[] = def.attributes.map((a) => ({
      name: a.name,
      value: a.value,
      max: a.max ?? null,
    }));
    world.addComponent("attributes", id, attrs);
  }
  if (def.abilities?.length) {
    world.addComponent("abilities", id, def.abilities);
  }
  if (def.pawn) {
    world.addComponent("pawn", id, { possessed: false });
  }
  if (def.weapon) {
    world.addComponent("weapon", id, { ...def.weapon });
  }
  if (def.ammo) {
    world.addComponent("ammo", id, { ...def.ammo });
  }
  if (def.damage) {
    world.addComponent("damage", id, { ...def.damage });
  }
  if (def.pickup) {
    world.addComponent("pickup", id, { ...def.pickup });
  }
  if (def.npc) {
    world.addComponent("npc", id, { ...def.npc });
  }
  if (def.perception) {
    world.addComponent("perception", id, {
      sightM: def.perception.sightM ?? 28,
      hearM: def.perception.hearM ?? 12,
      fovDeg: def.perception.fovDeg ?? 110,
    });
  }
  if (def.behavior) {
    world.addComponent("behavior", id, {
      tree: def.behavior.tree,
      defaultTactic: def.behavior.defaultTactic ?? null,
    });
  }
  if (def.mind) {
    world.addComponent("mind", id, {
      ref: def.mind.ref,
      cadenceS: def.mind.cadenceS ?? 4,
    });
  }
  if (def.navAgent) {
    world.addComponent("navAgent", id, { ...def.navAgent });
  }
  if (def.door) {
    world.addComponent("door", id, { ...def.door });
  }
  if (def.trigger) {
    world.addComponent("trigger", id, { ...def.trigger });
  }
  if (def.cover) {
    world.addComponent("cover", id, { ...def.cover });
  }
  if (def.audio) {
    world.addComponent("audio", id, { ...def.audio });
  }
  if (def.sprite) {
    world.addComponent("sprite", id, {
      atlas: def.sprite.atlas,
      frame: def.sprite.frame ?? null,
      width: def.sprite.width ?? 1,
      height: def.sprite.height ?? 1,
      animation: def.sprite.animation ?? "idle",
      flipX: def.sprite.flipX ?? false,
      billboard: def.sprite.billboard ?? true,
    });
  }
  if (def.collectible) {
    world.addComponent("collectible", id, { ...def.collectible });
  }
  if (def.interactable) {
    world.addComponent("interactable", id, { ...def.interactable });
  }
  if (def.patrol) {
    world.addComponent("patrol", id, { ...def.patrol });
    // Patrol entities need velocity for physics/movement
    if (!world.getComponent("velocity", id)) {
      world.addComponent("velocity", id, { vx: 0, vy: 0, vz: 0 });
    }
  }
  if (def.warp) {
    world.addComponent("warp", id, { ...def.warp });
  }
  if (def.levelEnd) {
    world.addComponent("levelEnd", id, { ...def.levelEnd });
  }
  if (def.stateMachine) {
    world.addComponent("stateMachine", id, {
      initial: def.stateMachine.initial ?? "active",
      onStompState: def.stateMachine.onStompState ?? null,
      onHitState: def.stateMachine.onHitState ?? null,
      onTouchState: def.stateMachine.onTouchState ?? null,
      deathDelay: def.stateMachine.deathDelay ?? null,
      onStateChange: def.stateMachine.onStateChange ?? null,
    });
  }
  if (def.particleEmitter) {
    world.addComponent("particleEmitter", id, {
      id: def.particleEmitter.id,
      preset: def.particleEmitter.preset ?? null,
      count: def.particleEmitter.count ?? null,
      speed: def.particleEmitter.speed ?? null,
      spread: def.particleEmitter.spread ?? null,
      lifetime: def.particleEmitter.lifetime ?? null,
      gravity: def.particleEmitter.gravity ?? null,
      color: def.particleEmitter.color ?? null,
      onTrigger: def.particleEmitter.onTrigger ?? null,
    });
  }
  if (def.signals?.length) {
    world.addComponent(
      "signals",
      id,
      def.signals.map((s) => s.name),
    );
  }

  for (const child of def.children ?? []) {
    if (isSpawnDef(child)) {
      instantiatePrefab(world, groups, handles, resources, child.spawn, child.overrides, id);
    } else {
      spawnEntityDef(world, groups, handles, resources, child, undefined, id);
    }
  }

  return id;
}

export function spawnSceneChildren(
  world: World,
  groups: Groups,
  handles: BabylonHandles,
  resources: Resources,
  root: EntityId,
  children: Array<EntityDef | SpawnDef>,
): void {
  for (const child of children) {
    if (isSpawnDef(child)) {
      instantiatePrefab(world, groups, handles, resources, child.spawn, child.overrides, root);
    } else {
      spawnEntityDef(world, groups, handles, resources, child, undefined, root);
    }
  }
}

/** Spawn zone trees and encounter waves from the lowered manifest. */
export function spawnZonesAndEncounters(
  world: World,
  groups: Groups,
  handles: BabylonHandles,
  resources: Resources,
  root: EntityId,
): void {
  const zones: ZoneDef[] = resources.manifest.zones?.length
    ? resources.manifest.zones
    : resources.bake.zones ?? [];
  for (const zone of zones) {
    const zoneId = world.create(zone.name || "Zone", root);
    world.addComponent("zone", zoneId, { kind: zone.kind, name: zone.name });
    for (const g of zone.groups ?? []) groups.add(g, zoneId);
    spawnSceneChildren(world, groups, handles, resources, zoneId, zone.children ?? []);
    for (const spawn of zone.spawns ?? []) {
      instantiatePrefab(world, groups, handles, resources, spawn.spawn, spawn.overrides, zoneId);
    }
  }

  const encounters =
    resources.manifest.mode?.encounters ??
    resources.manifest.encounters ??
    resources.bake.encounters ??
    [];
  for (const enc of encounters) {
    for (const spawn of enc.spawns ?? []) {
      instantiatePrefab(world, groups, handles, resources, spawn.spawn, spawn.overrides, root);
    }
  }
}

function resolveKitPiece(asset: string | undefined | null, resources: Resources): string | null {
  if (!asset || !resources.kit) return null;
  if (asset.startsWith("kit:")) {
    const name = asset.slice(4);
    return resources.kit.pieces[name] ? name : null;
  }
  if (resources.kit.pieces[asset]) return asset;
  const fromAssets = resources.manifest.assets?.[asset] ?? resources.bake.assets?.[asset];
  if (fromAssets?.path?.startsWith("kit:")) {
    const name = fromAssets.path.slice(4);
    return resources.kit.pieces[name] ? name : null;
  }
  return null;
}

export type { PrefabRegistry, KitDef, MaterialDef };
