// AUTO-GENERATED BY silc 0.2.0 — DO NOT EDIT
import { connect, createServer, type Socket } from "node:net";
import { join } from "node:path";
import { Database } from "bun:sqlite";

const socketPath = process.env.SILC_SOCKET || "__SOCKET_PATH__";
const port = Number(process.env.SILC_HTTP_PORT || "__PORT__");
const route = process.env.SILC_HTTP_ROUTE || "__ROUTE__";
const terminalPort = Number(process.env.SILC_TERMINAL_PORT || "__TERMINAL_PORT__");
const dbPath = process.env.SILC_DB_PATH || "__DB_PATH__";
const protocolVersion = 1;
const abiVersion = 1;
const root = import.meta.dir;
const distDir = join(root, "dist");
const ACTIONS = __ACTIONS_JSON__;
const PROCESSOR = "__PROCESSOR_OP__";
const HAS_LLM = __HAS_LLM__;
const HAS_SCRAPE = __HAS_SCRAPE__;
const SCRAPE_SITE = __SCRAPE_SITE__;
const SCRAPE_JS = "__SCRAPE_JS__";
const SCRAPE_DEPTH = __SCRAPE_DEPTH__;
const SCRAPE_SAME_HOST = __SCRAPE_SAME_HOST__;
const SCRAPE_LINK_CSS = "__SCRAPE_LINK_CSS__";
const SCRAPE_SELECTS = __SCRAPE_SELECTS_JSON__;
const SCRAPE_TABLE = "__SCRAPE_TABLE__";
const SCRAPE_CRAWL_BIN = process.env.SILC_SCRAPE_CRAWL_BIN || join(root, "..", "go", "crawl", "worker");
const SCRAPE_BROWSER_PY = process.env.SILC_SCRAPE_BROWSER_PY || join(root, "..", "python", "browser_worker.py");
const SCRAPE_PYTHON_BIN = process.env.SILC_SCRAPE_PYTHON_BIN || process.env.SILC_PYTHON_BIN || "python3";

function encodeFrame(value: unknown): Buffer {
  const payload = Buffer.from(JSON.stringify(value));
  const frame = Buffer.allocUnsafe(6 + payload.length);
  frame.writeUInt32LE(payload.length, 0);
  frame.writeUInt16LE(protocolVersion, 4);
  payload.copy(frame, 6);
  return frame;
}

function decodeFrame(buffer: Buffer): { frame: any; rest: Buffer } | null {
  if (buffer.length < 6) return null;
  const length = buffer.readUInt32LE(0);
  const version = buffer.readUInt16LE(4);
  if (version !== protocolVersion) throw new Error(`unsupported Silc protocol ${version}`);
  if (buffer.length < 6 + length) return null;
  const frame = JSON.parse(buffer.subarray(6, 6 + length).toString());
  return { frame, rest: buffer.subarray(6 + length) };
}

let supervisor: Socket | null = null;
let pending = Buffer.alloc(0);
const ingestWaiters = new Map<string, { resolve: (value: any) => void; reject: (error: Error) => void }>();

function rejectAllWaiters(error: Error) {
  for (const waiter of ingestWaiters.values()) waiter.reject(error);
  ingestWaiters.clear();
}

function dispatchFrames() {
  while (true) {
    const decoded = decodeFrame(pending);
    if (!decoded) break;
    pending = decoded.rest;
    const { frame } = decoded;
    if (frame.type === "RESPONSE" && typeof frame.request_id === "string") {
      const waiter = ingestWaiters.get(frame.request_id);
      if (waiter) {
        ingestWaiters.delete(frame.request_id);
        waiter.resolve(frame);
      }
    }
  }
}

function connectSupervisor(): Promise<void> {
  return new Promise((resolve, reject) => {
    supervisor = connect(socketPath);
    supervisor.on("connect", () => {
      supervisor!.write(encodeFrame({ type: "HELLO", worker_id: "bun", role: "bun", abi_version: abiVersion, pid: process.pid }));
      supervisor!.write(encodeFrame({ type: "READY", worker_id: "bun" }));
      resolve();
    });
    supervisor.on("data", (chunk) => {
      pending = Buffer.concat([pending, chunk]);
      try { dispatchFrames(); } catch (error) {
        rejectAllWaiters(error instanceof Error ? error : new Error(String(error)));
      }
    });
    supervisor.on("error", (error) => { rejectAllWaiters(error); reject(error); });
    supervisor.on("close", () => { supervisor = null; rejectAllWaiters(new Error("Silc supervisor closed")); });
  });
}

const INGEST_TIMEOUT_MS = 180_000;
// Keep application context well under DEFAULT_PAYLOAD_CAPACITY (16 KiB).
const MAX_CONTEXT_CHARS = 8_192;
// Personas are short identity/instruction blurbs, not data dumps.
const MAX_PERSONA_CHARS = 2_048;

function boundedText(raw: unknown, limit: number): string {
  if (raw === undefined || raw === null || raw === "") return "";
  let text = typeof raw === "string" ? raw : JSON.stringify(raw);
  if (text.length > limit) {
    text = text.slice(0, limit) + "…[truncated]";
  }
  return text;
}

function normalizeContext(raw: unknown): string {
  return boundedText(raw, MAX_CONTEXT_CHARS);
}

function normalizePersona(raw: unknown): string {
  return boundedText(raw, MAX_PERSONA_CHARS);
}

function ingest(payload: Record<string, unknown>, requestId: string): Promise<any> {
  if (!supervisor) return Promise.reject(new Error("supervisor socket not connected"));
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      if (ingestWaiters.delete(requestId)) {
        reject(new Error(`ingest timed out after ${INGEST_TIMEOUT_MS}ms`));
      }
    }, INGEST_TIMEOUT_MS);
    ingestWaiters.set(requestId, {
      resolve: (value) => {
        clearTimeout(timer);
        resolve(value);
      },
      reject: (error) => {
        clearTimeout(timer);
        reject(error);
      },
    });
    // ControlFrame::Ingest requires author + text. Chat payloads also carry
    // prompt/reply/model for the slot JSON, but text is what the supervisor
    // maps into the llm.complete record's prompt field.
    supervisor!.write(
      encodeFrame({
        type: "INGEST",
        request_id: requestId,
        author: "",
        text: "",
        ...payload,
      })
    );
  });
}

function openDb(): Database {
  const db = new Database(dbPath, { create: true });
  db.exec(`
    CREATE TABLE IF NOT EXISTS app_events (
      id TEXT PRIMARY KEY,
      kind TEXT NOT NULL,
      payload TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `);
  for (const table of __RESOURCE_TABLES__) {
    db.exec(`CREATE TABLE IF NOT EXISTS ${table} (
      id TEXT PRIMARY KEY,
      data TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );`);
  }
  return db;
}

const db = openDb();

function contentType(pathname: string): string {
  if (pathname.endsWith(".js")) return "application/javascript; charset=utf-8";
  if (pathname.endsWith(".css")) return "text/css; charset=utf-8";
  if (pathname.endsWith(".html")) return "text/html; charset=utf-8";
  if (pathname.endsWith(".svg")) return "image/svg+xml";
  return "application/octet-stream";
}

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "content-type": "application/json; charset=utf-8" },
  });
}

async function handleResource(req: Request, pathname: string): Promise<Response | null> {
  for (const action of ACTIONS) {
    const base = action.path.replace(/\/:id$/, "");
    const isItem = pathname.startsWith(base + "/") && action.path.includes(":id");
    const isCollection = pathname === action.path || pathname === base;
    if (!isItem && !isCollection && pathname !== action.path) continue;
    if (req.method !== action.http_method) continue;
    const table = action.path.split("/")[2];
    if (action.http_method === "GET" && !action.path.includes(":id")) {
      const rows = db.query(`SELECT id, data FROM ${table} ORDER BY created_at DESC`).all() as any[];
      return json(rows.map((r) => ({ id: r.id, ...JSON.parse(r.data) })));
    }
    if (action.http_method === "GET" && isItem) {
      const id = pathname.slice(base.length + 1);
      const row = db.query(`SELECT id, data FROM ${table} WHERE id = ?`).get(id) as any;
      if (!row) return json({ error: "not found" }, 404);
      return json({ id: row.id, ...JSON.parse(row.data) });
    }
    if (action.http_method === "POST") {
      const body = await req.json();
      const id = body.id || crypto.randomUUID();
      const { id: _i, ...rest } = body;
      db.query(`INSERT INTO ${table} (id, data) VALUES (?, ?)`).run(id, JSON.stringify(rest));
      return json({ id, ...rest }, 201);
    }
    if (action.http_method === "PUT" && isItem) {
      const id = pathname.slice(base.length + 1);
      const body = await req.json();
      db.query(`UPDATE ${table} SET data = ?, updated_at = datetime('now') WHERE id = ?`).run(JSON.stringify(body), id);
      return json({ id, ...body });
    }
    if (action.http_method === "DELETE" && isItem) {
      const id = pathname.slice(base.length + 1);
      db.query(`DELETE FROM ${table} WHERE id = ?`).run(id);
      return json({ ok: true });
    }
  }
  return null;
}

function decodeEntities(text: string): string {
  return text
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function selectCss(html: string, css: string): string {
  const sel = css.trim().toLowerCase();
  if (sel === "title") {
    const m = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
    return m ? decodeEntities(m[1].replace(/\s+/g, " ").trim()) : "";
  }
  const tagMatch = sel.match(/^([a-z][a-z0-9]*)(?:\s*,\s*.*)?$/);
  if (tagMatch) {
    const tag = tagMatch[1];
    const re = new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`, "i");
    const m = html.match(re);
    if (!m) return "";
    return decodeEntities(m[1].replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim());
  }
  // attribute / compound selectors: best-effort first matching tag text
  const any = html.match(/<([a-z][a-z0-9]*)[^>]*>([\s\S]*?)<\/\1>/i);
  return any ? decodeEntities(any[2].replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim()) : "";
}

function applySelects(html: string, page: Record<string, string>) {
  for (const sel of SCRAPE_SELECTS as Array<{ css: string; as_field?: string | null }>) {
    const value = selectCss(html, sel.css);
    const field = sel.as_field || sel.css.replace(/[^a-zA-Z0-9_]+/g, "_") || "value";
    if (field === "title" && value) page.title = value;
    else if (field === "snippet" || field === "body") page.snippet = value.slice(0, 280);
    else page[field] = value;
  }
}

function looksLikeShell(html: string): boolean {
  const text = html || "";
  const lower = text.toLowerCase();
  if (text.trim().length < 80) return true;
  if (lower.includes('<div id="root"></div>') || lower.includes('<div id="app"></div>')) return true;
  const bodyMatch = text.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  const body = bodyMatch ? bodyMatch[1] : text;
  const plain = body.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
  return plain.length < 40;
}

async function fetchStaticPage(url: string): Promise<{ html: string; status: string; error?: string }> {
  try {
    const resp = await fetch(url, { redirect: "follow", headers: { "user-agent": "SilcScrape/0.2" } });
    if (!resp.ok) return { html: "", status: "error", error: `HTTP ${resp.status}` };
    const html = await resp.text();
    return { html, status: "ok" };
  } catch (error) {
    return { html: "", status: "error", error: error instanceof Error ? error.message : String(error) };
  }
}

async function renderWithBrowser(url: string): Promise<{ html: string; title: string; status: string; error?: string }> {
  const proc = Bun.spawn([SCRAPE_PYTHON_BIN, SCRAPE_BROWSER_PY, "--url", url, "--json"], {
    stdout: "pipe",
    stderr: "pipe",
    env: { ...process.env },
  });
  const out = await new Response(proc.stdout).text();
  const err = await new Response(proc.stderr).text();
  const code = await proc.exited;
  if (code !== 0) {
    return { html: "", title: "", status: "error", error: err || `browser exit ${code}` };
  }
  try {
    const parsed = JSON.parse(out);
    return { html: parsed.html || "", title: parsed.title || "", status: "ok" };
  } catch {
    return { html: out, title: selectCss(out, "title"), status: "ok" };
  }
}

async function crawlWithGo(url: string, depth: number): Promise<Array<Record<string, string>>> {
  const proc = Bun.spawn([SCRAPE_CRAWL_BIN], {
    stdout: "pipe",
    stderr: "pipe",
    env: {
      ...process.env,
      SILC_SCRAPE_URL: url,
      SILC_SCRAPE_DEPTH: String(depth),
      SILC_SCRAPE_SAME_HOST: SCRAPE_SAME_HOST ? "true" : "false",
      SILC_SCRAPE_LINK_CSS: SCRAPE_LINK_CSS || "a[href]",
      SILC_SCRAPE_INCLUDE_HTML: SCRAPE_JS === "auto" || SCRAPE_JS === "true" ? "true" : "false",
    },
  });
  const out = await new Response(proc.stdout).text();
  const err = await new Response(proc.stderr).text();
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(err || `crawl worker exit ${code}`);
  }
  const pages = JSON.parse(out);
  if (!Array.isArray(pages)) throw new Error("crawl worker returned non-array");
  return pages;
}

function persistScrapePages(pages: Array<Record<string, string>>) {
  if (!SCRAPE_TABLE) return;
  db.query(`DELETE FROM ${SCRAPE_TABLE}`).run();
  const insert = db.query(`INSERT INTO ${SCRAPE_TABLE} (id, data) VALUES (?, ?)`);
  for (const page of pages) {
    const id = page.id || crypto.randomUUID();
    const { id: _drop, html: _html, ...rest } = page as any;
    insert.run(id, JSON.stringify({ ...rest, id }));
  }
}

async function runScrapeJob(body: Record<string, unknown>) {
  const url = String(body.url || body.target_url || "").trim();
  if (!url) throw new Error("url is required");
  let depth = Number(body.depth ?? SCRAPE_DEPTH ?? 2);
  if (!Number.isFinite(depth) || depth < 1) depth = 1;
  if (depth > 5) depth = 5;

  let rawPages: Array<Record<string, string>> = [];
  if (SCRAPE_SITE) {
    rawPages = await crawlWithGo(url, depth);
  } else {
    const fetched = await fetchStaticPage(url);
    rawPages = [{
      id: crypto.randomUUID(),
      url,
      title: selectCss(fetched.html, "title"),
      snippet: fetched.html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().slice(0, 280),
      depth: "0",
      status: fetched.status,
      html: fetched.html,
      ...(fetched.error ? { snippet: fetched.error } : {}),
    }];
  }

  const pages: Array<Record<string, string>> = [];
  for (const page of rawPages) {
    let html = page.html || "";
    let title = page.title || "";
    let status = page.status || "ok";
    if (status === "ok" && (SCRAPE_JS === "true" || (SCRAPE_JS === "auto" && looksLikeShell(html)))) {
      const rendered = await renderWithBrowser(page.url);
      if (rendered.status === "ok") {
        html = rendered.html;
        title = rendered.title || title;
      } else {
        status = "error";
        page.snippet = rendered.error || "browser render failed";
      }
    }
    const out: Record<string, string> = {
      id: page.id || crypto.randomUUID(),
      url: page.url,
      title,
      snippet: page.snippet || "",
      depth: page.depth || "0",
      status,
    };
    if (html) applySelects(html, out);
    if (!out.snippet && html) {
      out.snippet = html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().slice(0, 280);
    }
    pages.push(out);
  }

  persistScrapePages(pages);
  return { ok: true, count: pages.length, pages };
}

async function handleAction(req: Request, pathname: string): Promise<Response | null> {
  if (pathname === "/submit" && req.method === "POST") {
    const body = await req.json();
    if (HAS_SCRAPE) {
      try {
        const result = await runScrapeJob(body);
        return json(result);
      } catch (error) {
        return json({ ok: false, error: error instanceof Error ? error.message : String(error) }, 500);
      }
    }
    const requestId = crypto.randomUUID();
    const response = await ingest({ author: body.author || "", text: body.text || JSON.stringify(body), ...body }, requestId);
    return json({ ok: true, request_id: requestId, ...response });
  }
  if (pathname === "/scrape" && req.method === "POST" && HAS_SCRAPE) {
    const body = await req.json();
    try {
      const result = await runScrapeJob(body);
      return json(result);
    } catch (error) {
      return json({ ok: false, error: error instanceof Error ? error.message : String(error) }, 500);
    }
  }
  if (pathname === "/complete" && req.method === "POST") {
    const body = await req.json();
    const requestId = crypto.randomUUID();
    const prompt = body.prompt || body.text || "";
    const context = normalizeContext(body.context);
    const persona = normalizePersona(body.persona);
    const response = await ingest(
      {
        author: "",
        text: prompt,
        prompt,
        reply: "",
        model: body.model || "",
        session_id: body.session_id || "",
        context,
        persona,
      },
      requestId
    );
    if (response.ok === false) {
      return json({ ok: false, request_id: requestId, error: response.error || "complete failed" }, 500);
    }
    return json({ ok: true, request_id: requestId, reply: response.reply || response.summary || "", ...response });
  }
  if (pathname === "/history" && req.method === "GET") {
    const sessionId = new URL(req.url).searchParams.get("session_id");
    const rows = sessionId === null
      ? db.query(`
          SELECT payload
          FROM app_events
          WHERE kind = 'chat'
          ORDER BY created_at DESC
          LIMIT 50
        `).all() as any[]
      : db.query(`
          SELECT payload
          FROM app_events
          WHERE kind = 'chat'
            AND json_extract(payload, '$.session_id') = ?
          ORDER BY created_at DESC
          LIMIT 50
        `).all(sessionId) as any[];
    return json(rows.map((r) => JSON.parse(r.payload)));
  }
  return null;
}

const server = Bun.serve({
  hostname: "127.0.0.1",
  port,
  async fetch(req) {
    const url = new URL(req.url);
    let pathname = url.pathname;
    if (pathname === "/health") return json({ ok: true, processor: PROCESSOR, llm: HAS_LLM });

    const resourceResp = await handleResource(req, pathname);
    if (resourceResp) return resourceResp;
    const actionResp = await handleAction(req, pathname);
    if (actionResp) return actionResp;

    if (pathname === route || pathname === "/" || pathname === route + "/") {
      return new Response(Bun.file(join(distDir, "index.html")));
    }
    // Static assets must never fall back to index.html — that makes the
    // browser execute HTML as JS and produces a blank white page.
    if (pathname.startsWith("/assets/") || pathname.endsWith(".js") || pathname.endsWith(".css")) {
      const filePath = join(distDir, pathname.replace(/^\//, ""));
      const file = Bun.file(filePath);
      if (await file.exists()) {
        return new Response(file, { headers: { "content-type": contentType(pathname) } });
      }
      return new Response("Not found", { status: 404 });
    }
    const asset = Bun.file(join(distDir, pathname.replace(/^\//, "")));
    if (await asset.exists()) {
      return new Response(asset, { headers: { "content-type": contentType(pathname) } });
    }
    return new Response(Bun.file(join(distDir, "index.html")));
  },
});

// Dual-surface terminal: same actions/resources over a line-oriented session.
function renderTerminalHelp(): string {
  return [
    "Silc terminal surface (same app graph as web)",
    "Commands:",
    "  /help                 show this help",
    "  /routes               list app routes",
    "  /list <table>         list resource rows",
    "  /create <table> json  create a resource row",
    "  /delete <table> id    delete a resource row",
    "  /submit key=val ...   submit scored form fields",
    "  /chat <prompt>        complete via llm processor",
    "  /history              show chat history",
    "  /quit                 disconnect",
    "",
  ].join("\n");
}

const ROUTES = __ROUTES_JSON__;

function startTerminal() {
  if (!Number.isFinite(terminalPort) || terminalPort <= 0) return;
  const term = createServer((socket) => {
    socket.write("Silc 0.2.0 terminal\n");
    socket.write(renderTerminalHelp());
    socket.write("> ");
    let buf = "";
    socket.on("data", async (chunk) => {
      buf += chunk.toString("utf8");
      while (buf.includes("\n")) {
        const idx = buf.indexOf("\n");
        const line = buf.slice(0, idx).replace(/\r$/, "").trim();
        buf = buf.slice(idx + 1);
        try {
          if (!line || line === "/help") socket.write(renderTerminalHelp());
          else if (line === "/quit") { socket.end("bye\n"); return; }
          else if (line === "/routes") socket.write(ROUTES.map((r: any) => `  ${r.path} => ${r.component}`).join("\n") + "\n");
          else if (line.startsWith("/list ")) {
            const table = line.slice(6).trim();
            const rows = db.query(`SELECT id, data FROM ${table} ORDER BY created_at DESC`).all() as any[];
            socket.write(rows.map((r) => `${r.id} ${r.data}`).join("\n") + (rows.length ? "\n" : "(empty)\n"));
          } else if (line.startsWith("/create ")) {
            const rest = line.slice(8).trim();
            const sp = rest.indexOf(" ");
            const table = rest.slice(0, sp);
            const data = JSON.parse(rest.slice(sp + 1));
            const id = data.id || crypto.randomUUID();
            const { id: _i, ...body } = data;
            db.query(`INSERT INTO ${table} (id, data) VALUES (?, ?)`).run(id, JSON.stringify(body));
            socket.write(`created ${id}\n`);
          } else if (line.startsWith("/delete ")) {
            const [, table, id] = line.split(/\s+/);
            db.query(`DELETE FROM ${table} WHERE id = ?`).run(id);
            socket.write("deleted\n");
          } else if (line.startsWith("/submit ")) {
            const fields: Record<string, string> = {};
            for (const part of line.slice(8).split(/\s+/)) {
              const [k, ...v] = part.split("=");
              fields[k] = v.join("=");
            }
            const requestId = crypto.randomUUID();
            const response = await ingest({ author: fields.author || "", text: fields.text || "", ...fields }, requestId);
            socket.write(JSON.stringify(response) + "\n");
          } else if (line.startsWith("/chat ")) {
            const prompt = line.slice(6);
            const requestId = crypto.randomUUID();
            const response = await ingest(
              { author: "", text: prompt, prompt, reply: "", model: "" },
              requestId
            );
            if (response.ok === false) {
              socket.write(`error: ${response.error || "complete failed"}\n`);
            } else {
              socket.write((response.reply || response.summary || JSON.stringify(response)) + "\n");
            }
          } else if (line === "/history") {
            const rows = db.query(`SELECT payload FROM app_events WHERE kind = 'chat' ORDER BY created_at DESC LIMIT 20`).all() as any[];
            socket.write(rows.map((r) => r.payload).join("\n") + (rows.length ? "\n" : "(empty)\n"));
          } else {
            socket.write(`unknown command: ${line}\n`);
          }
        } catch (error) {
          socket.write(`error: ${error instanceof Error ? error.message : String(error)}\n`);
        }
        socket.write("> ");
      }
    });
  });
  term.listen(terminalPort, "127.0.0.1");
  console.log(`silc terminal on ${terminalPort}`);
}

await connectSupervisor();
startTerminal();
console.log(`silc web on ${port} route ${route}`);
void server;
