#!/usr/bin/env python3
# AUTO-GENERATED BY silc — DO NOT EDIT
import hashlib
import json
import mmap
import os
import socket
import struct

SOCKET_PATH = os.environ.get("SILC_SOCKET", "__SOCKET_PATH__")
IPC_DIR = os.environ.get("SILC_IPC_DIR", "ipc")
ABI_VERSION = 1
PROTOCOL_VERSION = 1
SCHEMA_ID = __SCHEMA_ID__
HEADER_SIZE = 128


def send_frame(sock, value):
    payload = json.dumps(value, separators=(",", ":")).encode()
    sock.sendall(struct.pack("<IH", len(payload), PROTOCOL_VERSION) + payload)


def recv_exact(sock, size):
    chunks = []
    while size:
        chunk = sock.recv(size)
        if not chunk:
            raise EOFError("Silc supervisor closed")
        chunks.append(chunk)
        size -= len(chunk)
    return b"".join(chunks)


def recv_frame(sock):
    length, version = struct.unpack("<IH", recv_exact(sock, 6))
    if version != PROTOCOL_VERSION:
        raise RuntimeError(f"unsupported protocol {version}")
    return json.loads(recv_exact(sock, length))


def score_text(text):
    words = text.split()
    word_score = min(1.0, len(words) / 100.0)
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    hash_score = int(digest[:8], 16) / 0xFFFFFFFF
    summary_words = words[:12] if words else ["empty"]
    summary = " ".join(summary_words)
    score = round((word_score + hash_score) / 2.0, 4)
    return summary, score


def process(segment_id):
    path = os.path.join(IPC_DIR, f"slot_{segment_id:04d}.sbuf")
    with open(path, "r+b", buffering=0) as file:
        with mmap.mmap(file.fileno(), 0) as view:
            if view[0:4] != b"SILC":
                raise RuntimeError("bad SILC shared-buffer magic")
            abi = struct.unpack_from("<H", view, 4)[0]
            if abi != ABI_VERSION:
                raise RuntimeError(f"unsupported ABI {abi}")
            schema_id = struct.unpack_from("<I", view, 8)[0]
            if schema_id != SCHEMA_ID:
                raise RuntimeError(f"schema_id mismatch: expected {SCHEMA_ID}, got {schema_id}")
            payload_offset = struct.unpack_from("<I", view, 20)[0]
            payload_len = struct.unpack_from("<I", view, 28)[0]
            record = json.loads(view[payload_offset : payload_offset + payload_len])
            text = record.get("text", "").strip()
            summary, score = score_text(text)
            record["summary"] = summary
            record["score"] = score
            encoded = json.dumps(record, separators=(",", ":")).encode()
            capacity = struct.unpack_from("<I", view, 24)[0]
            if len(encoded) > capacity:
                raise RuntimeError("scored payload exceeds slot capacity")
            view[payload_offset : payload_offset + len(encoded)] = encoded
            struct.pack_into("<I", view, 28, len(encoded))
            # MAP_SHARED writes are coherent with the Go consumer. Avoid
            # msync here: IPC slots are transient and do not require disk
            # durability; SQLite owns durable persistence at the sink.
            return record


def main():
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    sock.connect(SOCKET_PATH)
    send_frame(
        sock,
        {
            "type": "HELLO",
            "worker_id": "python",
            "role": "python",
            "abi_version": ABI_VERSION,
            "pid": os.getpid(),
        },
    )
    send_frame(sock, {"type": "READY", "worker_id": "python"})
    while True:
        frame = recv_frame(sock)
        if frame["type"] == "SHUTDOWN":
            break
        if frame["type"] != "NOTIFY":
            continue
        if frame.get("stage") != "python":
            continue
        try:
            result = process(frame["segment_id"])
            send_frame(
                sock,
                {
                    "type": "ACK",
                    "request_id": frame["request_id"],
                    "worker_id": "python",
                    "segment_id": frame["segment_id"],
                    "seq": frame["seq"],
                    "result": {
                        "score": result["score"],
                        "summary": result["summary"],
                    },
                },
            )
        except Exception as exc:
            send_frame(
                sock,
                {
                    "type": "ERROR",
                    "request_id": frame.get("request_id"),
                    "code": "PYTHON_WORKER",
                    "message": str(exc),
                },
            )


if __name__ == "__main__":
    main()
