// AUTO-GENERATED BY silc — DO NOT EDIT
import { connect, type Socket } from "node:net";

const socketPath = process.env.SILC_SOCKET || "__SOCKET_PATH__";
const port = Number(process.env.SILC_HTTP_PORT || "__PORT__");
const protocolVersion = 1;
const abiVersion = 1;

function encodeFrame(value: unknown): Buffer {
  const payload = Buffer.from(JSON.stringify(value));
  const frame = Buffer.allocUnsafe(6 + payload.length);
  frame.writeUInt32LE(payload.length, 0);
  frame.writeUInt16LE(protocolVersion, 4);
  payload.copy(frame, 6);
  return frame;
}

function decodeFrame(buffer: Buffer): { frame: any; rest: Buffer } | null {
  if (buffer.length < 6) return null;
  const length = buffer.readUInt32LE(0);
  const version = buffer.readUInt16LE(4);
  if (version !== protocolVersion) {
    throw new Error(`unsupported Silc protocol ${version}`);
  }
  if (buffer.length < 6 + length) return null;
  const frame = JSON.parse(buffer.subarray(6, 6 + length).toString());
  return { frame, rest: buffer.subarray(6 + length) };
}

let supervisor: Socket | null = null;
let pending = Buffer.alloc(0);
const ingestWaiters = new Map<
  string,
  { resolve: (value: any) => void; reject: (error: Error) => void }
>();

function rejectAllWaiters(error: Error) {
  for (const waiter of ingestWaiters.values()) {
    waiter.reject(error);
  }
  ingestWaiters.clear();
}

function dispatchFrames() {
  while (true) {
    const decoded = decodeFrame(pending);
    if (!decoded) break;
    pending = decoded.rest;
    const { frame } = decoded;
    if (frame.type === "RESPONSE" && typeof frame.request_id === "string") {
      const waiter = ingestWaiters.get(frame.request_id);
      if (waiter) {
        ingestWaiters.delete(frame.request_id);
        waiter.resolve(frame);
      }
    }
  }
}

function connectSupervisor(): Promise<void> {
  return new Promise((resolve, reject) => {
    supervisor = connect(socketPath);
    supervisor.on("connect", () => {
      supervisor!.write(
        encodeFrame({
          type: "HELLO",
          worker_id: "bun",
          role: "bun",
          abi_version: abiVersion,
          pid: process.pid,
        }),
      );
      supervisor!.write(encodeFrame({ type: "READY", worker_id: "bun" }));
      resolve();
    });
    supervisor.on("data", (chunk) => {
      pending = Buffer.concat([pending, chunk]);
      try {
        dispatchFrames();
      } catch (error) {
        rejectAllWaiters(error instanceof Error ? error : new Error(String(error)));
      }
    });
    supervisor.on("error", (error) => {
      rejectAllWaiters(error);
      reject(error);
    });
    supervisor.on("close", () => {
      supervisor = null;
      rejectAllWaiters(new Error("Silc supervisor closed"));
    });
  });
}

function ingest(author: string, text: string, requestId: string): Promise<any> {
  if (!supervisor) {
    return Promise.reject(new Error("supervisor socket not connected"));
  }
  return new Promise((resolve, reject) => {
    ingestWaiters.set(requestId, { resolve, reject });
    supervisor!.write(
      encodeFrame({
        type: "INGEST",
        request_id: requestId,
        author,
        text,
      }),
    );
  });
}

const html = `<!doctype html>
<html><head><meta charset="utf-8"><title>Silc Feedback Portal</title>
<style>body{font:16px system-ui;max-width:680px;margin:3rem auto;padding:0 1rem}
label{display:block;margin-top:1rem}input,textarea{box-sizing:border-box;width:100%;padding:.7rem}
button{margin-top:1rem;padding:.7rem 1rem}#result{white-space:pre-wrap}</style></head>
<body><h1>Silc Feedback Portal</h1>
<p>Bun → Silc mmap/UDS → Python → Go/SQLite</p>
<form id="form"><label>Author<input name="author" required maxlength="120"></label>
<label>Feedback<textarea name="text" required maxlength="8192" rows="8"></textarea></label>
<button>Submit</button></form><pre id="result"></pre>
<script>
form.onsubmit=async(e)=>{e.preventDefault();const d=Object.fromEntries(new FormData(form));
const r=await fetch('/submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)});
result.textContent=JSON.stringify(await r.json(),null,2)}
</script></body></html>`;

await connectSupervisor();

Bun.serve({
  hostname: "127.0.0.1",
  port,
  async fetch(request) {
    const url = new URL(request.url);
    if (request.method === "GET" && url.pathname === "/") {
      return new Response(html, { headers: { "content-type": "text/html; charset=utf-8" } });
    }
    if (request.method === "GET" && url.pathname === "/health") {
      return Response.json({ ok: true });
    }
    if (request.method === "POST" && url.pathname === "/submit") {
      const length = Number(request.headers.get("content-length") || "0");
      if (length > 16384) return Response.json({ error: "request too large" }, { status: 413 });
      try {
        const body = (await request.json()) as { author?: string; text?: string };
        const author = String(body.author || "").trim();
        const text = String(body.text || "").trim();
        if (!author || !text) {
          return Response.json({ error: "author and text are required" }, { status: 400 });
        }
        const requestId = crypto.randomUUID();
        const response = await ingest(author, text, requestId);
        return Response.json(response, { status: response.ok ? 201 : 500 });
      } catch (error) {
        return Response.json({ error: String(error) }, { status: 500 });
      }
    }
    return new Response("Not found", { status: 404 });
  },
});

console.log(`SILC_READY http://127.0.0.1:${port}`);
