#!/usr/bin/env python3
# AUTO-GENERATED BY silc __COMPILER_VERSION__ — DO NOT EDIT
"""Stream a zip of one file or one directory tree to stdout (ADR-018).

Invoked by the Bun worker for `GET /files/download` when the target is a
folder (or `?zip=1`). Uses only the standard library so the pinned CPython
needs no extra packages. Dot-files and symlinks that escape the root are
skipped, matching `/files/list`.
"""

import argparse
import os
import sys
import zipfile


def _inside(root: str, path: str) -> bool:
    try:
        real = os.path.realpath(path)
    except OSError:
        return False
    return real == root or real.startswith(root + os.sep)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True, help="file or directory to zip")
    parser.add_argument("--name", required=True, help="top-level name inside the archive")
    args = parser.parse_args()

    root = os.path.realpath(args.root)
    name = args.name.strip().strip("/") or "files"
    out = sys.stdout.buffer

    # ZIP_DEFLATED needs zlib, which CPython always ships with.
    with zipfile.ZipFile(out, mode="w", compression=zipfile.ZIP_DEFLATED, allowZip64=True) as zf:
        if os.path.isfile(root):
            zf.write(root, arcname=name)
            return 0
        if not os.path.isdir(root):
            sys.stderr.write(f"files_zip_worker: not a file or directory: {root}\n")
            return 2
        wrote_any = False
        for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
            dirnames[:] = sorted(
                d for d in dirnames if not d.startswith(".") and _inside(root, os.path.join(dirpath, d))
            )
            rel_dir = os.path.relpath(dirpath, root)
            arc_dir = name if rel_dir == "." else os.path.join(name, rel_dir)
            for filename in sorted(filenames):
                if filename.startswith("."):
                    continue
                full = os.path.join(dirpath, filename)
                if os.path.islink(full) and not _inside(root, full):
                    continue
                if not os.path.isfile(full):
                    continue
                zf.write(full, arcname=os.path.join(arc_dir, filename))
                wrote_any = True
        if not wrote_any:
            # Keep an explicit (empty) directory entry so the archive is not zero-length.
            zf.writestr(zipfile.ZipInfo(name + "/"), b"")
    out.flush()
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BrokenPipeError:
        # Client went away mid-download.
        sys.exit(0)
