#!/usr/bin/env python3
# AUTO-GENERATED BY silc __COMPILER_VERSION__ — DO NOT EDIT
"""Compile-time bake for game:: prefabs/data/colliders/assets (ADR-012).

Reads bake_plan.json, validates :ref integrity, generates procedural PBR
textures, modular kit metadata, and sprite atlases (ADR-013), writes
game_bake.json under the output directory. Uses the Silc-provisioned CPython.
"""

from __future__ import annotations

import json
import os
import random
import struct
import sys
import zlib
from pathlib import Path
from typing import Callable

try:
    from PIL import Image  # type: ignore

    _HAS_PILLOW = True
except ImportError:
    _HAS_PILLOW = False

TEXTURE_SIZE = 256
TEXTURE_NAMES = (
    "concrete_albedo",
    "concrete_normal",
    "concrete_roughness",
    "metal_albedo",
    "metal_roughness",
    "wood_albedo",
    "glass_albedo",
    "plaster_albedo",
    "asphalt_albedo",
    "emissive_strip",
)

GRID_M = 2.0

KIT_PIECES: dict[str, dict] = {
    "floor_2x2": {
        "kind": "floor",
        "size": {"x": 2.0, "y": 0.2, "z": 2.0},
        "gridUnits": {"x": 1, "y": 0.1, "z": 1},
        "material": "concrete",
        "collider": "box",
    },
    "wall_2x3": {
        "kind": "wall",
        "size": {"x": 2.0, "y": 3.0, "z": 0.2},
        "gridUnits": {"x": 1, "y": 1.5, "z": 0.1},
        "material": "concrete",
        "collider": "box",
    },
    "wall_door_2x3": {
        "kind": "wall_door",
        "size": {"x": 2.0, "y": 3.0, "z": 0.2},
        "gridUnits": {"x": 1, "y": 1.5, "z": 0.1},
        "material": "concrete",
        "opening": {"x": 1.4, "y": 2.1, "z": 0.0},
        "collider": "box",
    },
    "wall_window_2x3": {
        "kind": "wall_window",
        "size": {"x": 2.0, "y": 3.0, "z": 0.2},
        "gridUnits": {"x": 1, "y": 1.5, "z": 0.1},
        "material": "concrete",
        "opening": {"x": 1.2, "y": 0.8, "z": 0.0, "yOffset": 1.6},
        "collider": "box",
    },
    "column_0.4": {
        "kind": "column",
        "size": {"x": 0.4, "y": 3.0, "z": 0.4},
        "gridUnits": {"x": 0.2, "y": 1.5, "z": 0.2},
        "material": "concrete",
        "collider": "box",
    },
    "crate_1": {
        "kind": "prop",
        "size": {"x": 1.0, "y": 1.0, "z": 1.0},
        "gridUnits": {"x": 0.5, "y": 0.5, "z": 0.5},
        "material": "wood",
        "collider": "box",
    },
    "desk_1.6": {
        "kind": "prop",
        "size": {"x": 1.6, "y": 0.75, "z": 0.8},
        "gridUnits": {"x": 0.8, "y": 0.375, "z": 0.4},
        "material": "wood",
        "collider": "box",
    },
    "chair_0.5": {
        "kind": "prop",
        "size": {"x": 0.5, "y": 0.9, "z": 0.5},
        "gridUnits": {"x": 0.25, "y": 0.45, "z": 0.25},
        "material": "metal",
        "collider": "box",
    },
    "locker_0.6": {
        "kind": "prop",
        "size": {"x": 0.6, "y": 2.0, "z": 0.5},
        "gridUnits": {"x": 0.3, "y": 1.0, "z": 0.25},
        "material": "metal",
        "collider": "box",
    },
    "lab_table_2": {
        "kind": "prop",
        "size": {"x": 2.0, "y": 0.85, "z": 0.9},
        "gridUnits": {"x": 1, "y": 0.425, "z": 0.45},
        "material": "metal",
        "collider": "box",
    },
    "bunk_2": {
        "kind": "prop",
        "size": {"x": 2.0, "y": 1.6, "z": 1.0},
        "gridUnits": {"x": 1, "y": 0.8, "z": 0.5},
        "material": "metal",
        "collider": "box",
    },
    "planter_1": {
        "kind": "prop",
        "size": {"x": 1.0, "y": 0.6, "z": 1.0},
        "gridUnits": {"x": 0.5, "y": 0.3, "z": 0.5},
        "material": "concrete",
        "collider": "box",
    },
    "vent_1.2": {
        "kind": "prop",
        "size": {"x": 1.2, "y": 0.15, "z": 0.6},
        "gridUnits": {"x": 0.6, "y": 0.075, "z": 0.3},
        "material": "metal",
        "collider": "box",
    },
    "cover_low": {
        "kind": "cover",
        "size": {"x": 2.0, "y": 1.2, "z": 0.6},
        "gridUnits": {"x": 1, "y": 0.6, "z": 0.3},
        "material": "concrete",
        "coverQuality": "low",
        "collider": "box",
    },
    "cover_high": {
        "kind": "cover",
        "size": {"x": 2.0, "y": 2.4, "z": 0.6},
        "gridUnits": {"x": 1, "y": 1.2, "z": 0.3},
        "material": "concrete",
        "coverQuality": "high",
        "collider": "box",
    },
    "door_frame": {
        "kind": "door_frame",
        "size": {"x": 1.0, "y": 2.1, "z": 0.15},
        "gridUnits": {"x": 0.5, "y": 1.05, "z": 0.075},
        "material": "metal",
        "collider": "box",
    },
}

BAKED_MATERIALS: dict[str, dict] = {
    "concrete": {
        "albedo": "textures/concrete_albedo.png",
        "normal": "textures/concrete_normal.png",
        "roughnessMap": "textures/concrete_roughness.png",
        "roughness": 0.85,
        "metallic": 0.0,
    },
    "metal": {
        "albedo": "textures/metal_albedo.png",
        "roughnessMap": "textures/metal_roughness.png",
        "roughness": 0.35,
        "metallic": 0.9,
    },
    "wood": {
        "albedo": "textures/wood_albedo.png",
        "roughness": 0.65,
        "metallic": 0.0,
    },
    "glass": {
        "albedo": "textures/glass_albedo.png",
        "roughness": 0.05,
        "metallic": 0.0,
        "alpha": 0.35,
    },
    "plaster": {
        "albedo": "textures/plaster_albedo.png",
        "roughness": 0.9,
        "metallic": 0.0,
    },
    "asphalt": {
        "albedo": "textures/asphalt_albedo.png",
        "roughness": 0.95,
        "metallic": 0.0,
    },
    "emissive": {
        "albedo": "textures/emissive_strip.png",
        "emissive": "textures/emissive_strip.png",
        "roughness": 0.2,
        "metallic": 0.0,
    },
}


def _clamp(v: int) -> int:
    return max(0, min(255, v))


def _noise2d(x: int, y: int, seed: int = 0) -> float:
    n = x * 374761393 + y * 668265263 + seed * 982451653
    n = (n ^ (n >> 13)) * 1274126177
    return ((n ^ (n >> 16)) & 0x7FFFFFFF) / 0x7FFFFFFF


def _fbm(x: float, y: float, octaves: int = 4, seed: int = 0) -> float:
    total = 0.0
    amp = 0.5
    freq = 1.0
    for i in range(octaves):
        sx = int(x * freq * 32) + seed * (i + 1)
        sy = int(y * freq * 32) + seed * (i + 7)
        total += _noise2d(sx, sy, seed + i) * amp
        amp *= 0.5
        freq *= 2.0
    return total


def _make_pixels(name: str, size: int) -> list[tuple[int, int, int, int]]:
    rng = random.Random(hash(name) & 0xFFFFFFFF)
    seed = rng.randint(0, 99999)
    pixels: list[tuple[int, int, int, int]] = []

    for y in range(size):
        for x in range(size):
            u = x / size
            v = y / size
            if name == "concrete_albedo":
                n = _fbm(u, v, 5, seed)
                g = _clamp(int(95 + n * 45))
                pixels.append((g, g - 4, g - 8, 255))
            elif name == "concrete_normal":
                nx = int((_fbm(u + 0.01, v, 3, seed) - _fbm(u - 0.01, v, 3, seed)) * 800 + 128)
                ny = int((_fbm(u, v + 0.01, 3, seed) - _fbm(u, v - 0.01, 3, seed)) * 800 + 128)
                pixels.append((_clamp(nx), _clamp(ny), 255, 255))
            elif name == "concrete_roughness":
                n = _fbm(u, v, 4, seed)
                g = _clamp(int(170 + n * 40))
                pixels.append((g, g, g, 255))
            elif name == "metal_albedo":
                n = _fbm(u * 2, v * 2, 3, seed)
                r = _clamp(int(120 + n * 30))
                g = _clamp(int(125 + n * 28))
                b = _clamp(int(135 + n * 25))
                pixels.append((r, g, b, 255))
            elif name == "metal_roughness":
                n = _fbm(u * 4, v * 4, 2, seed)
                g = _clamp(int(40 + n * 50))
                pixels.append((g, g, g, 255))
            elif name == "wood_albedo":
                grain = abs((v * 18 + _fbm(u, v, 2, seed) * 2) % 1.0 - 0.5)
                r = _clamp(int(110 + grain * 80))
                g = _clamp(int(70 + grain * 50))
                b = _clamp(int(40 + grain * 30))
                pixels.append((r, g, b, 255))
            elif name == "glass_albedo":
                n = _fbm(u, v, 2, seed) * 0.15
                pixels.append((_clamp(int(180 + n * 40)), _clamp(int(210 + n * 30)), _clamp(int(230 + n * 20)), 90))
            elif name == "plaster_albedo":
                n = _fbm(u, v, 4, seed)
                g = _clamp(int(210 + n * 25))
                pixels.append((g, g - 2, g - 6, 255))
            elif name == "asphalt_albedo":
                n = _fbm(u, v, 5, seed)
                speck = 1 if _noise2d(x, y, seed) > 0.97 else 0
                g = _clamp(int(35 + n * 25 + speck * 40))
                pixels.append((g, g, g + 2, 255))
            elif name == "emissive_strip":
                stripe = 1.0 if int(v * 12) % 2 == 0 else 0.15
                glow = stripe * (0.7 + 0.3 * _fbm(u, v, 2, seed))
                r = _clamp(int(40 + glow * 180))
                g = _clamp(int(200 + glow * 55))
                b = _clamp(int(255 * glow))
                pixels.append((r, g, b, 255))
            else:
                pixels.append((128, 128, 128, 255))
    return pixels


def _write_png_pure(path: Path, size: int, pixels: list[tuple[int, int, int, int]]) -> None:
    raw = bytearray()
    row_bytes = size * 4
    for y in range(size):
        raw.append(0)  # filter type None
        start = y * size
        for x in range(size):
            r, g, b, a = pixels[start + x]
            raw.extend((r, g, b, a))

    def chunk(tag: bytes, data: bytes) -> bytes:
        crc = zlib.crc32(tag + data) & 0xFFFFFFFF
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", crc)

    ihdr = struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)
    compressed = zlib.compress(bytes(raw), 9)
    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", compressed) + chunk(b"IEND", b"")
    path.write_bytes(png)


def _write_png(path: Path, name: str, size: int = TEXTURE_SIZE) -> None:
    pixels = _make_pixels(name, size)
    if _HAS_PILLOW:
        img = Image.new("RGBA", (size, size))
        img.putdata(pixels)
        img.save(path, format="PNG")
    else:
        _write_png_pure(path, size, pixels)


def generate_textures(tex_dir: Path) -> dict[str, str]:
    tex_dir.mkdir(parents=True, exist_ok=True)
    out: dict[str, str] = {}
    for name in TEXTURE_NAMES:
        rel = f"textures/{name}.png"
        _write_png(tex_dir / f"{name}.png", name)
        out[name] = rel
    return out


def build_kit() -> dict:
    return {
        "gridM": GRID_M,
        "license": "Silc-generated procedural kit — compiler-owned, no CDN",
        "pieces": KIT_PIECES,
    }


def build_materials(plan_materials: dict) -> dict:
    merged = {k: dict(v) if isinstance(v, dict) else v for k, v in BAKED_MATERIALS.items()}
    if isinstance(plan_materials, dict):
        for name, props in plan_materials.items():
            if isinstance(props, dict):
                entry = dict(merged.get(name, {}))
                entry.update(props)
                merged[name] = entry
            else:
                merged[name] = props
    return merged


# ============================================================================
# Procedural Sprite Generation (ADR-013)
# ============================================================================

# Default frame sizes per style
STYLE_FRAME_SIZES = {
    "pixel_8": 16,
    "pixel_16": 32,
    "pixel_32": 64,
    "flat": 32,
    "outline": 32,
}

# Default animations per preset archetype
PRESET_ANIMATIONS = {
    "character": ["idle", "walk", "jump", "fall"],
    "enemy": ["idle", "walk", "hurt", "dead"],
    "item": ["idle", "collected"],
    "tile": ["idle", "active", "empty", "broken"],
    "effect": ["idle", "active", "fade"],
}

# Default palettes per preset
PRESET_PALETTES = {
    "character": {"primary": "#4488FF", "secondary": "#2244AA", "accent": "#FFCC00", "skin": "#FFCCAA"},
    "enemy": {"primary": "#AA4444", "secondary": "#662222", "accent": "#FFFF00"},
    "item": {"primary": "#FFCC00", "secondary": "#AA8800", "accent": "#FFFFFF"},
    "tile": {"primary": "#886644", "secondary": "#664422", "accent": "#AAAAAA"},
    "effect": {"primary": "#FFFFFF", "secondary": "#AAAAFF", "accent": "#FFFF00"},
}


def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    """Convert hex color string to RGB tuple."""
    hex_color = hex_color.lstrip("#")
    if len(hex_color) == 3:
        hex_color = "".join(c * 2 for c in hex_color)
    return (
        int(hex_color[0:2], 16),
        int(hex_color[2:4], 16),
        int(hex_color[4:6], 16),
    )


def _draw_character_frame(
    pixels: list[list[tuple[int, int, int, int]]],
    frame_size: int,
    palette: dict[str, str],
    anim: str,
    frame_idx: int,
) -> None:
    """Draw a character sprite frame (bipedal humanoid)."""
    primary = _hex_to_rgb(palette.get("primary", "#4488FF"))
    secondary = _hex_to_rgb(palette.get("secondary", "#2244AA"))
    accent = _hex_to_rgb(palette.get("accent", "#FFCC00"))
    skin = _hex_to_rgb(palette.get("skin", "#FFCCAA"))

    # Scale factor based on frame size
    s = frame_size // 16
    cx = frame_size // 2

    # Animation offsets
    bob = 0
    leg_offset = 0
    arm_offset = 0
    if anim == "walk":
        bob = (frame_idx % 2) * s
        leg_offset = ((frame_idx % 4) - 2) * s
        arm_offset = -leg_offset
    elif anim == "jump":
        bob = -2 * s
        arm_offset = -2 * s
    elif anim == "fall":
        bob = s
        arm_offset = 2 * s

    # Head (skin color)
    for y in range(2 * s, 5 * s):
        for x in range(cx - 2 * s, cx + 2 * s):
            if 0 <= x < frame_size and 0 <= y < frame_size:
                pixels[y + bob][x] = (*skin, 255)

    # Body (primary color)
    for y in range(5 * s, 10 * s):
        for x in range(cx - 2 * s, cx + 2 * s):
            if 0 <= x < frame_size and 0 <= y + bob < frame_size:
                pixels[y + bob][x] = (*primary, 255)

    # Arms (secondary color)
    for y in range(5 * s, 8 * s):
        for x in range(cx - 3 * s, cx - 2 * s):
            if 0 <= x < frame_size and 0 <= y + bob + arm_offset < frame_size:
                pixels[y + bob + arm_offset][x] = (*secondary, 255)
        for x in range(cx + 2 * s, cx + 3 * s):
            if 0 <= x < frame_size and 0 <= y + bob - arm_offset < frame_size:
                pixels[y + bob - arm_offset][x] = (*secondary, 255)

    # Legs (secondary color)
    for y in range(10 * s, 14 * s):
        for x in range(cx - 2 * s, cx):
            if 0 <= x < frame_size and 0 <= y + leg_offset < frame_size:
                pixels[y + leg_offset][x] = (*secondary, 255)
        for x in range(cx, cx + 2 * s):
            if 0 <= x < frame_size and 0 <= y - leg_offset < frame_size:
                pixels[y - leg_offset][x] = (*secondary, 255)


def _draw_enemy_frame(
    pixels: list[list[tuple[int, int, int, int]]],
    frame_size: int,
    palette: dict[str, str],
    anim: str,
    frame_idx: int,
) -> None:
    """Draw an enemy sprite frame (generic hostile)."""
    primary = _hex_to_rgb(palette.get("primary", "#AA4444"))
    secondary = _hex_to_rgb(palette.get("secondary", "#662222"))
    accent = _hex_to_rgb(palette.get("accent", "#FFFF00"))

    s = frame_size // 16
    cx = frame_size // 2
    cy = frame_size // 2

    squash = 0
    if anim == "walk":
        squash = (frame_idx % 2) * s
    elif anim == "hurt":
        squash = 2 * s
    elif anim == "dead":
        squash = 4 * s

    # Body (oval shape)
    for y in range(cy - 4 * s + squash, cy + 4 * s):
        for x in range(cx - 5 * s, cx + 5 * s):
            dx = (x - cx) / (5 * s)
            dy = (y - cy + squash // 2) / (4 * s - squash // 2) if (4 * s - squash // 2) > 0 else 0
            if dx * dx + dy * dy <= 1:
                if 0 <= x < frame_size and 0 <= y < frame_size:
                    pixels[y][x] = (*primary, 255)

    # Eyes (accent color)
    if anim != "dead":
        for ey in range(cy - 2 * s, cy):
            for ex in [cx - 2 * s, cx + s]:
                if 0 <= ex < frame_size and 0 <= ey < frame_size:
                    pixels[ey][ex] = (*accent, 255)
                    if ex + s < frame_size:
                        pixels[ey][ex + s] = (*accent, 255)

    # Feet (secondary)
    for y in range(cy + 3 * s, cy + 5 * s):
        for x in [cx - 3 * s, cx + 2 * s]:
            if 0 <= x < frame_size and 0 <= y < frame_size:
                pixels[y][x] = (*secondary, 255)
                if x + s < frame_size:
                    pixels[y][x + s] = (*secondary, 255)


def _draw_item_frame(
    pixels: list[list[tuple[int, int, int, int]]],
    frame_size: int,
    palette: dict[str, str],
    anim: str,
    frame_idx: int,
) -> None:
    """Draw an item sprite frame (collectible)."""
    primary = _hex_to_rgb(palette.get("primary", "#FFCC00"))
    secondary = _hex_to_rgb(palette.get("secondary", "#AA8800"))
    accent = _hex_to_rgb(palette.get("accent", "#FFFFFF"))

    s = frame_size // 16
    cx = frame_size // 2
    cy = frame_size // 2

    # Bobbing animation
    bob = 0
    if anim == "idle":
        bob = ((frame_idx % 4) - 2) * s // 2
    elif anim == "collected":
        # Shrinking effect
        s = max(1, s - frame_idx)

    # Circle/coin shape
    radius = 5 * s
    for y in range(frame_size):
        for x in range(frame_size):
            dx = x - cx
            dy = (y - bob) - cy
            dist = (dx * dx + dy * dy) ** 0.5
            if dist <= radius:
                if dist <= radius - s:
                    pixels[y][x] = (*primary, 255)
                else:
                    pixels[y][x] = (*secondary, 255)

    # Shine highlight
    for y in range(cy - 3 * s + bob, cy - s + bob):
        for x in range(cx - s, cx + s):
            if 0 <= x < frame_size and 0 <= y < frame_size:
                pixels[y][x] = (*accent, 255)


def _draw_tile_frame(
    pixels: list[list[tuple[int, int, int, int]]],
    frame_size: int,
    palette: dict[str, str],
    anim: str,
    frame_idx: int,
) -> None:
    """Draw a tile sprite frame (block/platform)."""
    primary = _hex_to_rgb(palette.get("primary", "#886644"))
    secondary = _hex_to_rgb(palette.get("secondary", "#664422"))
    accent = _hex_to_rgb(palette.get("accent", "#AAAAAA"))

    s = frame_size // 16

    # Fill with primary
    for y in range(frame_size):
        for x in range(frame_size):
            pixels[y][x] = (*primary, 255)

    # Border (secondary)
    for y in range(frame_size):
        for x in range(s):
            pixels[y][x] = (*secondary, 255)
            pixels[y][frame_size - 1 - x] = (*secondary, 255)
    for x in range(frame_size):
        for y in range(s):
            pixels[y][x] = (*secondary, 255)
            pixels[frame_size - 1 - y][x] = (*secondary, 255)

    # State-specific decorations
    if anim == "active" or anim == "idle":
        # Question mark or indicator
        cx, cy = frame_size // 2, frame_size // 2
        for y in range(cy - 3 * s, cy + s):
            for x in range(cx - s, cx + s):
                if 0 <= x < frame_size and 0 <= y < frame_size:
                    pixels[y][x] = (*accent, 255)
        for y in range(cy + 2 * s, cy + 3 * s):
            for x in range(cx - s // 2, cx + s // 2 + 1):
                if 0 <= x < frame_size and 0 <= y < frame_size:
                    pixels[y][x] = (*accent, 255)
    elif anim == "empty":
        # Darker, no decoration
        for y in range(s, frame_size - s):
            for x in range(s, frame_size - s):
                pixels[y][x] = (*secondary, 255)
    elif anim == "broken":
        # Cracks/debris pattern
        for i in range(frame_size // 4):
            x = random.randint(s, frame_size - s - 1)
            y = random.randint(s, frame_size - s - 1)
            pixels[y][x] = (0, 0, 0, 0)


def _draw_effect_frame(
    pixels: list[list[tuple[int, int, int, int]]],
    frame_size: int,
    palette: dict[str, str],
    anim: str,
    frame_idx: int,
) -> None:
    """Draw an effect sprite frame (particle/VFX)."""
    primary = _hex_to_rgb(palette.get("primary", "#FFFFFF"))
    secondary = _hex_to_rgb(palette.get("secondary", "#AAAAFF"))
    accent = _hex_to_rgb(palette.get("accent", "#FFFF00"))

    cx = frame_size // 2
    cy = frame_size // 2

    # Fade based on animation
    alpha = 255
    if anim == "fade":
        alpha = max(0, 255 - frame_idx * 50)

    # Radial gradient
    max_radius = frame_size // 2
    for y in range(frame_size):
        for x in range(frame_size):
            dx = x - cx
            dy = y - cy
            dist = (dx * dx + dy * dy) ** 0.5
            if dist <= max_radius:
                t = dist / max_radius
                r = int(primary[0] * (1 - t) + secondary[0] * t)
                g = int(primary[1] * (1 - t) + secondary[1] * t)
                b = int(primary[2] * (1 - t) + secondary[2] * t)
                a = int(alpha * (1 - t * 0.7))
                pixels[y][x] = (r, g, b, a)


PRESET_DRAWERS = {
    "character": _draw_character_frame,
    "enemy": _draw_enemy_frame,
    "item": _draw_item_frame,
    "tile": _draw_tile_frame,
    "effect": _draw_effect_frame,
}


def generate_sprite_atlas(
    asset_def: dict,
    sprites_dir: Path,
    public_assets_dir: Path | None,
) -> dict:
    """Generate a sprite atlas PNG and JSON metadata.

    Args:
        asset_def: The generated asset definition from bake_plan
        sprites_dir: Output directory for baked sprites (baked/sprites/)
        public_assets_dir: Optional output for public/assets/ export

    Returns:
        Metadata dict with paths and animation info
    """
    name = asset_def.get("name", "sprite")
    preset = asset_def.get("preset", "character")
    style = asset_def.get("style", "pixel_16")
    frame_size = int(asset_def.get("frameSize") or STYLE_FRAME_SIZES.get(style, 32))
    animations = asset_def.get("animations") or PRESET_ANIMATIONS.get(preset, ["idle"])
    palette = asset_def.get("palette") or PRESET_PALETTES.get(preset, {})
    export = asset_def.get("export", False)

    # Ensure palette values are strings
    if isinstance(palette, dict):
        palette = {k: str(v) for k, v in palette.items()}

    # Calculate atlas dimensions
    frames_per_anim = 4  # Default frames per animation
    total_frames = len(animations) * frames_per_anim
    cols = min(8, total_frames)
    rows = (total_frames + cols - 1) // cols

    atlas_width = cols * frame_size
    atlas_height = rows * frame_size

    # Create pixel buffer
    atlas_pixels: list[list[tuple[int, int, int, int]]] = [
        [(0, 0, 0, 0) for _ in range(atlas_width)] for _ in range(atlas_height)
    ]

    # Get the drawer function for this preset
    drawer = PRESET_DRAWERS.get(preset, _draw_character_frame)

    # Generate frames for each animation
    animation_meta: dict[str, dict] = {}
    frame_index = 0

    for anim in animations:
        anim_name = str(anim)
        start_frame = frame_index
        for f in range(frames_per_anim):
            col = frame_index % cols
            row = frame_index // cols
            x_offset = col * frame_size
            y_offset = row * frame_size

            # Create frame pixel buffer
            frame_pixels: list[list[tuple[int, int, int, int]]] = [
                [(0, 0, 0, 0) for _ in range(frame_size)] for _ in range(frame_size)
            ]

            # Draw the frame
            drawer(frame_pixels, frame_size, palette, anim_name, f)

            # Copy to atlas
            for y in range(frame_size):
                for x in range(frame_size):
                    atlas_pixels[y_offset + y][x_offset + x] = frame_pixels[y][x]

            frame_index += 1

        animation_meta[anim_name] = {
            "frames": list(range(start_frame, frame_index)),
            "duration": 0.15,
            "loop": anim_name not in ("dead", "collected", "broken"),
        }

    # Write PNG
    sprites_dir.mkdir(parents=True, exist_ok=True)
    png_path = sprites_dir / f"{name}.png"
    _write_sprite_png(png_path, atlas_width, atlas_height, atlas_pixels)

    # Write JSON metadata
    json_meta = {
        "frameWidth": frame_size,
        "frameHeight": frame_size,
        "columns": cols,
        "rows": rows,
        "animations": animation_meta,
    }
    json_path = sprites_dir / f"{name}.json"
    json_path.write_text(json.dumps(json_meta, indent=2) + "\n", encoding="utf-8")

    # Export to public/assets if requested
    if export and public_assets_dir:
        public_assets_dir.mkdir(parents=True, exist_ok=True)
        public_png = public_assets_dir / f"{name}.png"
        public_json = public_assets_dir / f"{name}.json"

        # Copy files
        import shutil
        shutil.copy2(png_path, public_png)
        shutil.copy2(json_path, public_json)

    return {
        "name": name,
        "path": f"sprites/{name}.png",
        "meta": f"sprites/{name}.json",
        "frameWidth": frame_size,
        "frameHeight": frame_size,
        "animations": list(animation_meta.keys()),
        "exported": export,
    }


def _write_sprite_png(
    path: Path,
    width: int,
    height: int,
    pixels: list[list[tuple[int, int, int, int]]],
) -> None:
    """Write a sprite atlas PNG file."""
    if _HAS_PILLOW:
        img = Image.new("RGBA", (width, height))
        flat_pixels = [pixel for row in pixels for pixel in row]
        img.putdata(flat_pixels)
        img.save(path, format="PNG")
    else:
        # Pure Python PNG writer
        raw = bytearray()
        for row in pixels:
            raw.append(0)  # filter type None
            for r, g, b, a in row:
                raw.extend((r, g, b, a))

        def chunk(tag: bytes, data: bytes) -> bytes:
            crc = zlib.crc32(tag + data) & 0xFFFFFFFF
            return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", crc)

        ihdr = struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0)
        compressed = zlib.compress(bytes(raw), 9)
        png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr) + chunk(b"IDAT", compressed) + chunk(b"IEND", b"")
        path.write_bytes(png)


def generate_sprites(
    generated_assets: list[dict],
    out_dir: Path,
    source_dir: Path | None = None,
) -> dict[str, dict]:
    """Generate all sprite atlases from game::generate definitions.

    Args:
        generated_assets: List of asset definitions from bake_plan
        out_dir: Base output directory (baked/)
        source_dir: Source directory for public/assets export

    Returns:
        Dict mapping asset names to their metadata
    """
    sprites_dir = out_dir / "sprites"
    public_assets_dir = source_dir / "public" / "assets" if source_dir else None

    generated: dict[str, dict] = {}

    for asset_def in generated_assets:
        asset_type = asset_def.get("type", "sprite")
        if asset_type != "sprite":
            continue  # Only handle sprites for now

        name = asset_def.get("name")
        if not name:
            continue

        # Check if manually edited version exists in public/assets
        if public_assets_dir:
            manual_png = public_assets_dir / f"{name}.png"
            manual_json = public_assets_dir / f"{name}.json"
            if manual_png.exists() and manual_json.exists():
                # Use manual version, copy to baked/sprites/
                sprites_dir.mkdir(parents=True, exist_ok=True)
                import shutil
                shutil.copy2(manual_png, sprites_dir / f"{name}.png")
                shutil.copy2(manual_json, sprites_dir / f"{name}.json")

                # Read metadata
                meta = json.loads(manual_json.read_text(encoding="utf-8"))
                generated[name] = {
                    "name": name,
                    "path": f"sprites/{name}.png",
                    "meta": f"sprites/{name}.json",
                    "frameWidth": meta.get("frameWidth", 32),
                    "frameHeight": meta.get("frameHeight", 32),
                    "animations": list((meta.get("animations") or {}).keys()),
                    "manual": True,
                }
                continue

        # Generate procedurally
        meta = generate_sprite_atlas(asset_def, sprites_dir, public_assets_dir)
        generated[name] = meta

    return generated


def _walk_nodes(nodes: list, visitor: Callable[[dict], None]) -> None:
    for node in nodes:
        if not isinstance(node, dict):
            continue
        visitor(node)
        children = node.get("children")
        if isinstance(children, list):
            _walk_nodes(children, visitor)


def _collect_entity_nodes(plan: dict) -> list[dict]:
    nodes: list[dict] = []

    def add(node: dict) -> None:
        nodes.append(node)

    prefabs = plan.get("prefabs") or {}
    if isinstance(prefabs, dict):
        for prefab in prefabs.values():
            if isinstance(prefab, dict):
                add(prefab)
    scene = plan.get("scene") or {}
    if isinstance(scene, dict):
        children = scene.get("children")
        if isinstance(children, list):
            _walk_nodes(children, add)
    for zone in plan.get("zones") or []:
        if not isinstance(zone, dict):
            continue
        children = zone.get("children")
        if isinstance(children, list):
            _walk_nodes(children, add)
    return nodes


def resolve_refs(plan: dict) -> list[str]:
    errors: list[str] = []
    data = plan.get("data") or {}
    if not isinstance(data, dict):
        data = {}

    weapons = plan.get("weapons") or {}
    if not isinstance(weapons, dict):
        weapons = {}

    assets = plan.get("assets") or {}
    if not isinstance(assets, dict):
        assets = {}

    materials = plan.get("materials") or {}
    if not isinstance(materials, dict):
        materials = {}

    prefabs = plan.get("prefabs") or {}
    if isinstance(prefabs, dict):
        for pname, prefab in prefabs.items():
            if not isinstance(prefab, dict):
                continue
            movement = prefab.get("movement") or {}
            ref = movement.get("ref") if isinstance(movement, dict) else None
            if ref and ref not in data:
                errors.append(f"prefab `{pname}` movement :ref(`{ref}`) missing game::data")
            for ability in prefab.get("abilities") or []:
                if not isinstance(ability, dict):
                    continue
                aref = ability.get("ref")
                if aref and aref not in data:
                    errors.append(f"prefab `{pname}` ability :ref(`{aref}`) missing game::data")
            weapon = prefab.get("weapon") or {}
            if isinstance(weapon, dict):
                wref = weapon.get("ref")
                if wref and wref not in weapons:
                    errors.append(f"prefab `{pname}` weapon :ref(`{wref}`) missing game::weapon")

    for spawn in plan.get("spawns") or []:
        if not isinstance(spawn, dict):
            continue
        name = spawn.get("spawn")
        if name and name not in prefabs:
            errors.append(f"spawn references unknown prefab `{name}`")

    known_materials = set(BAKED_MATERIALS) | set(materials)

    for node in _collect_entity_nodes(plan):
        mesh = node.get("mesh") or {}
        if isinstance(mesh, dict):
            asset = mesh.get("asset")
            if asset and asset not in assets and asset not in KIT_PIECES:
                errors.append(f"mesh asset `{asset}` missing from game::asset registry")
            mat = mesh.get("material")
            if mat and mat not in known_materials:
                errors.append(f"mesh material `{mat}` missing from materials registry")
        pickup = node.get("pickup") or {}
        if isinstance(pickup, dict):
            pref = pickup.get("ref")
            kind = pickup.get("kind")
            if pref and kind == "weapon" and pref not in weapons:
                errors.append(f"pickup weapon ref `{pref}` missing game::weapon")
        audio = node.get("audio") or {}
        if isinstance(audio, dict):
            aref = audio.get("ref")
            if aref and aref not in assets:
                errors.append(f"audio ref `{aref}` missing from game::asset registry")

    if isinstance(assets, dict):
        for aname, asset in assets.items():
            if not isinstance(asset, dict):
                continue
            path = asset.get("path")
            if path and isinstance(path, str) and path.startswith("http"):
                errors.append(f"asset `{aname}` must not use CDN path `{path}`")

    return errors


def hull_for_collider(collider: dict) -> dict:
    shape = str(collider.get("shape") or "box")
    size = float(collider.get("size") or 1.0)
    prefab = collider.get("prefab")
    if shape == "capsule":
        # `size` is the character height; 0.2 keeps shoulders door-width.
        radius = size * 0.2
        return {
            "prefab": prefab,
            "shape": "capsule",
            "radius": radius,
            "halfHeight": size * 0.5,
            "aabb": {"x": radius * 2, "y": size, "z": radius * 2},
        }
    if shape == "plane":
        return {
            "prefab": prefab,
            "shape": "plane",
            "radius": 0.0,
            "halfHeight": 0.0,
            "aabb": {"x": size, "y": 0.05, "z": size},
        }
    return {
        "prefab": prefab,
        "shape": "box",
        "radius": 0.0,
        "halfHeight": size * 0.5,
        "aabb": {"x": size, "y": size, "z": size},
    }


def _resolve_weapon_entry(weapon: dict, weapons: dict) -> dict:
    entry = dict(weapon)
    wref = entry.get("ref")
    if wref and wref in weapons and isinstance(weapons[wref], dict):
        src = weapons[wref]
        for key in (
            "slot",
            "fireMode",
            "damage",
            "fireRate",
            "magazine",
            "reload",
            "spread",
            "projectiles",
            "effects",
        ):
            if entry.get(key) is None and key in src:
                entry[key] = src[key]
    return entry


def bake(plan: dict, out_dir: Path, source_dir: Path | None = None) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    errors = resolve_refs(plan)
    if errors:
        raise SystemExit("silc game bake: " + "; ".join(errors))

    data = plan.get("data") or {}
    prefabs = plan.get("prefabs") or {}
    signals = plan.get("signals") or []
    mode = plan.get("mode")
    attributes = plan.get("attributes") or {}
    spawns = plan.get("spawns") or []
    assets = plan.get("assets") or {}
    plan_materials = plan.get("materials") or {}
    zones = plan.get("zones") or []
    weapons = plan.get("weapons") or {}
    encounters = plan.get("encounters") or []
    objectives = plan.get("objectives") or []
    environment = plan.get("environment")
    nav_hints = plan.get("navHints") or {}
    mind_refs = plan.get("mindRefs") or []
    generated_assets = plan.get("generatedAssets") or []

    textures = generate_textures(out_dir / "textures")
    kit = build_kit()
    materials = build_materials(plan_materials if isinstance(plan_materials, dict) else {})

    # Generate procedural sprites (ADR-013)
    generated_sprites = generate_sprites(generated_assets, out_dir, source_dir)

    # Compiler-owned kit pieces are addressable as mesh :asset without CDN paths.
    resolved_assets: dict = dict(assets) if isinstance(assets, dict) else {}
    for piece_name in KIT_PIECES:
        resolved_assets.setdefault(
            piece_name,
            {"path": f"kit:{piece_name}", "kind": "gltf"},
        )

    resolved_data: dict = {}
    if isinstance(data, dict):
        for name, props in data.items():
            if isinstance(props, dict):
                resolved_data[name] = dict(props)

    resolved_weapons: dict = {}
    if isinstance(weapons, dict):
        for wname, wdef in weapons.items():
            if isinstance(wdef, dict):
                entry = dict(wdef)
                wref = entry.get("ref")
                if wref and wref in resolved_data:
                    src = resolved_data[wref]
                    for key in ("damage", "fireRate", "cooldown", "spread", "magazine", "reload"):
                        if entry.get(key) is None and key in src:
                            entry[key] = src[key]
                resolved_weapons[wname] = entry

    resolved_prefabs: dict = {}
    if isinstance(prefabs, dict):
        for pname, prefab in prefabs.items():
            if not isinstance(prefab, dict):
                continue
            entry = dict(prefab)
            movement = dict(entry.get("movement") or {}) if entry.get("movement") else {}
            ref = movement.get("ref")
            if ref and ref in resolved_data:
                src = resolved_data[ref]
                if movement.get("speed") is None and "speed" in src:
                    movement["speed"] = src["speed"]
                if movement.get("jumpSpeed") is None and "jumpSpeed" in src:
                    movement["jumpSpeed"] = src["jumpSpeed"]
                if movement.get("sprintMul") is None and "sprintMul" in src:
                    movement["sprintMul"] = src["sprintMul"]
                entry["movement"] = movement
            abilities = []
            for ability in entry.get("abilities") or []:
                if not isinstance(ability, dict):
                    continue
                ab = dict(ability)
                aref = ab.get("ref")
                if aref and aref in resolved_data:
                    src = resolved_data[aref]
                    if ab.get("cooldown") in (None, 0.5) and "cooldown" in src:
                        ab["cooldown"] = src["cooldown"]
                    if ab.get("cost") in (None, 0.0) and "cost" in src:
                        ab["cost"] = src["cost"]
                abilities.append(ab)
            if abilities:
                entry["abilities"] = abilities
            weapon = entry.get("weapon")
            if isinstance(weapon, dict):
                entry["weapon"] = _resolve_weapon_entry(weapon, resolved_weapons)
            resolved_prefabs[pname] = entry

    colliders = [hull_for_collider(c) for c in (plan.get("colliders") or []) if isinstance(c, dict)]

    (out_dir / "kit.json").write_text(json.dumps(kit, indent=2) + "\n", encoding="utf-8")
    (out_dir / "materials.json").write_text(json.dumps(materials, indent=2) + "\n", encoding="utf-8")

    meta = {
        "engine": "cpython-bake-v1",
        "data": resolved_data,
        "assets": resolved_assets,
        "textures": textures,
        "sprites": generated_sprites,
        "kit": kit,
        "materials": materials,
        "zones": zones if isinstance(zones, list) else [],
        "weapons": resolved_weapons,
        "encounters": encounters if isinstance(encounters, list) else [],
        "objectives": objectives if isinstance(objectives, list) else [],
        "environment": environment,
        "navHints": nav_hints,
        "mindRefs": mind_refs,
        "prefabs": resolved_prefabs,
        "colliders": colliders,
        "spawns": spawns,
        "signals": signals,
        "mode": mode,
        "attributes": attributes,
    }
    (out_dir / "game_bake.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    (out_dir / "bake.json").write_text(
        json.dumps({
            "ok": True,
            "engine": meta["engine"],
            "textures": len(textures),
            "sprites": len(generated_sprites),
            "kitPieces": len(KIT_PIECES),
        }, indent=2) + "\n",
        encoding="utf-8",
    )
    return meta


def main() -> int:
    plan_path = Path(os.environ.get("SILC_GAME_BAKE_PLAN", "bake_plan.json"))
    out_dir = Path(os.environ.get("SILC_GAME_BAKE_OUT", "baked"))
    source_dir_env = os.environ.get("SILC_GAME_SOURCE_DIR")
    source_dir = Path(source_dir_env) if source_dir_env else None

    if not plan_path.is_file():
        print(f"silc game bake: missing plan {plan_path}", file=sys.stderr)
        return 1
    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    meta = bake(plan, out_dir, source_dir)
    n_tex = len(meta.get("textures") or {})
    n_sprites = len(meta.get("sprites") or {})
    n_kit = len((meta.get("kit") or {}).get("pieces") or {})
    n_prefabs = len(meta.get("prefabs") or {})
    print(
        f"silc game bake: wrote {out_dir}/game_bake.json "
        f"({n_prefabs} prefabs, {n_tex} textures, {n_sprites} sprites, {n_kit} kit pieces)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
