#!/usr/bin/env python3
# AUTO-GENERATED BY silc — DO NOT EDIT
"""Compile-time bake for game:: terrain/surface (ADR-012).

Reads bake_plan.json, writes height/noise buffers under the output directory.
Uses the Silc-provisioned CPython (+ numpy when available).
"""

from __future__ import annotations

import json
import math
import os
import struct
import sys
from pathlib import Path


def hash2(x: float, y: float) -> float:
    n = math.sin(x * 127.1 + y * 311.7) * 43758.5453
    return n - math.floor(n)


def noise2(x: float, y: float) -> float:
    x0 = math.floor(x)
    y0 = math.floor(y)
    fx = x - x0
    fy = y - y0
    ux = fx * fx * (3.0 - 2.0 * fx)
    uy = fy * fy * (3.0 - 2.0 * fy)
    a = hash2(x0, y0)
    b = hash2(x0 + 1, y0)
    c = hash2(x0, y0 + 1)
    d = hash2(x0 + 1, y0 + 1)
    return a + (b - a) * ux + (c - a) * uy + (a - b - c + d) * ux * uy


def fbm(x: float, y: float, octaves: int = 4) -> float:
    amp = 0.5
    freq = 1.0
    total = 0.0
    for _ in range(octaves):
        total += amp * noise2(x * freq, y * freq)
        freq *= 2.0
        amp *= 0.5
    return total


def bake(plan: dict, out_dir: Path) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    resolution = int(plan.get("resolution", 256))
    wind_deg = float(plan.get("windDeg", 35.0))
    wind = math.radians(wind_deg)
    wx, wy = math.cos(wind), math.sin(wind)
    layers = plan.get("layers") or [
        {"kind": "dune", "scaleM": 80.0, "amplitudeM": 12.0},
        {"kind": "drift", "scaleM": 12.0, "amplitudeM": 2.5},
    ]
    surface = plan.get("surfaceProfile") or "snow"

    heights = []
    for j in range(resolution):
        row = []
        for i in range(resolution):
            # Normalized world coords in ~[-1, 1]
            u = (i / max(resolution - 1, 1)) * 2.0 - 1.0
            v = (j / max(resolution - 1, 1)) * 2.0 - 1.0
            # Shear along wind for medium/fine layers
            sx = u * wx + v * wy
            sy = -u * wy + v * wx
            h = 0.0
            for layer in layers:
                kind = str(layer.get("kind", "dune"))
                scale = float(layer.get("scaleM", 40.0)) or 40.0
                amp = float(layer.get("amplitudeM", 1.0))
                if kind in ("dune",):
                    h += amp * fbm(u * (100.0 / scale), v * (100.0 / scale), 3)
                elif kind in ("drift",):
                    h += amp * fbm(sx * (100.0 / scale), sy * (80.0 / scale), 4)
                else:
                    h += amp * 0.5 * fbm(sx * (160.0 / scale), sy * (160.0 / scale), 5)
            row.append(h)
        heights.extend(row)

    # Normalize to roughly [-1, 1]
    mn = min(heights) if heights else 0.0
    mx = max(heights) if heights else 1.0
    span = (mx - mn) or 1.0
    norm = [(h - mn) / span * 2.0 - 1.0 for h in heights]

    raw_path = out_dir / "height.f32"
    with raw_path.open("wb") as fh:
        fh.write(struct.pack(f"<{len(norm)}f", *norm))

    meta = {
        "resolution": resolution,
        "windDeg": wind_deg,
        "surfaceProfile": surface,
        "layers": layers,
        "heightFile": "height.f32",
        "format": "f32le",
        "engine": "cpython-bake-v1",
    }
    (out_dir / "bake.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return meta


def main() -> int:
    plan_path = Path(os.environ.get("SILC_GAME_BAKE_PLAN", "bake_plan.json"))
    out_dir = Path(os.environ.get("SILC_GAME_BAKE_OUT", "baked"))
    if not plan_path.is_file():
        print(f"silc game bake: missing plan {plan_path}", file=sys.stderr)
        return 1
    plan = json.loads(plan_path.read_text(encoding="utf-8"))
    meta = bake(plan, out_dir)
    print(f"silc game bake: wrote {out_dir} ({meta['resolution']}²)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
