#!/usr/bin/env python3
# AUTO-GENERATED BY silc — DO NOT EDIT
"""Optional Silclm cognition worker for game::mind.

Listens on HTTP (SILC_COGNITION_PORT, default 18141). Returns schema-constrained
JSON tactical directives. Falls back to deterministic heuristics when the model
is unavailable or responses are invalid. Never invents game state.
"""

from __future__ import annotations

import json
import os
import re
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any

MODEL_PATH = os.environ.get("SILC_MODEL_PATH", "")
PORT = int(os.environ.get("SILC_COGNITION_PORT", "18141"))
ALLOWED = ("suppress", "flank_left", "flank_right", "push", "retreat", "hold")

_llm = None


def ensure_llm():
    global _llm
    if _llm is not None:
        return _llm
    if not MODEL_PATH or not os.path.isfile(MODEL_PATH):
        return None
    try:
        from llama_cpp import Llama

        _llm = Llama(model_path=MODEL_PATH, n_ctx=2048, verbose=False)
        return _llm
    except Exception as exc:  # noqa: BLE001
        print(f"silc cognition: llama unavailable ({exc})", file=sys.stderr)
        return None


def fallback(persona: str, context: dict[str, Any]) -> dict[str, Any]:
    hp = float(((context or {}).get("self") or {}).get("hp") or 100)
    allies = int((context or {}).get("alliesAlive") or 1)
    if hp < 35:
        tactic = "retreat"
        bark = "Falling back!"
        aggression = 0.25
    elif allies <= 1:
        tactic = "hold"
        bark = "Holding the line."
        aggression = 0.45
    elif "flank" in (persona or "").lower():
        tactic = "flank_left"
        bark = "Cutting left!"
        aggression = 0.7
    elif "breach" in (persona or "").lower():
        tactic = "push"
        bark = "Pushing through!"
        aggression = 0.85
    else:
        tactic = "suppress"
        bark = "Suppressing!"
        aggression = 0.65
    return {
        "aggression": aggression,
        "preferred_tactic": tactic,
        "bark": bark[:80],
        "ttl_s": 4.0,
        "revision": 1,
        "source": "fallback",
    }


def normalize(raw: dict[str, Any], persona: str, context: dict[str, Any]) -> dict[str, Any]:
    base = fallback(persona, context)
    tactic = str(raw.get("preferred_tactic") or base["preferred_tactic"])
    if tactic not in ALLOWED:
        tactic = base["preferred_tactic"]
    try:
        aggression = float(raw.get("aggression", base["aggression"]))
    except (TypeError, ValueError):
        aggression = base["aggression"]
    aggression = max(0.0, min(1.0, aggression))
    bark = str(raw.get("bark") or base["bark"])[:80]
    try:
        ttl = float(raw.get("ttl_s", 4.0))
    except (TypeError, ValueError):
        ttl = 4.0
    ttl = max(1.0, min(12.0, ttl))
    return {
        "aggression": aggression,
        "preferred_tactic": tactic,
        "bark": bark,
        "ttl_s": ttl,
        "revision": int(raw.get("revision") or 1),
        "source": raw.get("source") or "silclm",
    }


PROMPT = """You are a hostile megastructure NPC mind. Reply with ONLY compact JSON:
{{"aggression":0.0-1.0,"preferred_tactic":"suppress|flank_left|flank_right|push|retreat|hold","bark":"short line","ttl_s":4}}
Persona: {persona}
Battlefield: {context}
JSON:"""


def think(persona: str, context: dict[str, Any]) -> dict[str, Any]:
    llm = ensure_llm()
    if llm is None:
        return fallback(persona, context)
    prompt = PROMPT.format(
        persona=persona[:240],
        context=json.dumps(context, separators=(",", ":"))[:900],
    )
    try:
        out = llm(
            prompt,
            max_tokens=96,
            temperature=0.4,
            stop=["\n\n", "User:", "Human:"],
        )
        text = out["choices"][0]["text"].strip()
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if not match:
            return fallback(persona, context)
        parsed = json.loads(match.group(0))
        if not isinstance(parsed, dict):
            return fallback(persona, context)
        return normalize(parsed, persona, context)
    except Exception as exc:  # noqa: BLE001
        print(f"silc cognition: infer failed ({exc})", file=sys.stderr)
        return fallback(persona, context)


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt: str, *args) -> None:  # noqa: A003
        sys.stderr.write("cognition: " + (fmt % args) + "\n")

    def _json(self, code: int, body: dict[str, Any]) -> None:
        data = json.dumps(body).encode("utf-8")
        self.send_response(code)
        self.send_header("content-type", "application/json")
        self.send_header("content-length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self) -> None:  # noqa: N802
        if self.path.startswith("/health"):
            self._json(200, {"ok": True, "model": bool(MODEL_PATH)})
            return
        self._json(404, {"ok": False, "error": "not_found"})

    def do_POST(self) -> None:  # noqa: N802
        if self.path not in ("/think", "/api/cognition", "/"):
            self._json(404, {"ok": False, "error": "not_found"})
            return
        length = int(self.headers.get("content-length") or "0")
        raw = self.rfile.read(length) if length else b"{}"
        try:
            body = json.loads(raw.decode("utf-8") or "{}")
        except json.JSONDecodeError:
            self._json(400, {"ok": False, "error": "bad_json"})
            return
        persona = str(body.get("persona") or "Hostile operative")
        context = body.get("context") if isinstance(body.get("context"), dict) else {}
        directive = think(persona, context)
        self._json(200, {"ok": True, "directive": directive})


def main() -> int:
    server = ThreadingHTTPServer(("127.0.0.1", PORT), Handler)
    print(f"silc cognition worker http://127.0.0.1:{PORT}", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
