#!/usr/bin/env python3
# AUTO-GENERATED BY silc — DO NOT EDIT
import json
import mmap
import os
import socket
import struct

from llama_cpp import Llama

SOCKET_PATH = os.environ.get("SILC_SOCKET", "__SOCKET_PATH__")
IPC_DIR = os.environ.get("SILC_IPC_DIR", "ipc")
MODEL_PATH = os.environ["SILC_MODEL_PATH"]
MODEL_ID = os.environ.get("SILC_MODEL_ID", "llama3.2-1b")
ABI_VERSION = 1
PROTOCOL_VERSION = 1
SCHEMA_ID = __SCHEMA_ID__
MAX_TOKENS = 256
LLM = None


def send_frame(sock, value):
    payload = json.dumps(value, separators=(",", ":")).encode()
    sock.sendall(struct.pack("<IH", len(payload), PROTOCOL_VERSION) + payload)


def recv_exact(sock, size):
    chunks = []
    while size:
        chunk = sock.recv(size)
        if not chunk:
            raise EOFError("Silc supervisor closed")
        chunks.append(chunk)
        size -= len(chunk)
    return b"".join(chunks)


def recv_frame(sock):
    length, version = struct.unpack("<IH", recv_exact(sock, 6))
    if version != PROTOCOL_VERSION:
        raise RuntimeError(f"unsupported protocol {version}")
    return json.loads(recv_exact(sock, length))


def complete_llm(prompt):
    global LLM
    prompt = (prompt or "").strip()
    if not prompt:
        return ""
    if LLM is None:
        print(f"silc: loading inventory LLM {MODEL_ID}", flush=True)
        LLM = Llama(
            model_path=MODEL_PATH,
            n_ctx=2048,
            n_threads=max(1, (os.cpu_count() or 2) // 2),
            n_gpu_layers=-1,
            verbose=False,
        )
        print("silc: inventory LLM ready", flush=True)
    output = LLM.create_chat_completion(
        messages=[
            {
                "role": "system",
                "content": (
                    "You support a read-only grocery inventory. Follow the user's "
                    "format and grounding constraints exactly. Never invent products."
                ),
            },
            {"role": "user", "content": prompt},
        ],
        max_tokens=MAX_TOKENS,
        temperature=0.2,
    )
    return (output["choices"][0]["message"]["content"] or "").strip()


def process(segment_id):
    path = os.path.join(IPC_DIR, f"slot_{segment_id:04d}.sbuf")
    with open(path, "r+b", buffering=0) as file:
        with mmap.mmap(file.fileno(), 0) as view:
            if view[0:4] != b"SILC":
                raise RuntimeError("bad SILC shared-buffer magic")
            if struct.unpack_from("<H", view, 4)[0] != ABI_VERSION:
                raise RuntimeError("unsupported ABI")
            if struct.unpack_from("<I", view, 8)[0] != SCHEMA_ID:
                raise RuntimeError("schema_id mismatch")
            offset = struct.unpack_from("<I", view, 20)[0]
            length = struct.unpack_from("<I", view, 28)[0]
            record = json.loads(view[offset : offset + length])
            record["reply"] = complete_llm(record.get("prompt", ""))
            record["model"] = MODEL_ID
            encoded = json.dumps(record, separators=(",", ":")).encode()
            capacity = struct.unpack_from("<I", view, 24)[0]
            if len(encoded) > capacity:
                raise RuntimeError("completion payload exceeds slot capacity")
            view[offset : offset + len(encoded)] = encoded
            struct.pack_into("<I", view, 28, len(encoded))
            return record


def main():
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    sock.connect(SOCKET_PATH)
    send_frame(
        sock,
        {
            "type": "HELLO",
            "worker_id": "python",
            "role": "python",
            "abi_version": ABI_VERSION,
            "pid": os.getpid(),
        },
    )
    send_frame(sock, {"type": "READY", "worker_id": "python"})
    while True:
        frame = recv_frame(sock)
        if frame["type"] == "SHUTDOWN":
            break
        if frame["type"] != "NOTIFY" or frame.get("stage") != "python":
            continue
        try:
            result = process(frame["segment_id"])
            send_frame(
                sock,
                {
                    "type": "ACK",
                    "request_id": frame["request_id"],
                    "worker_id": "python",
                    "segment_id": frame["segment_id"],
                    "seq": frame["seq"],
                    "result": {"reply": result["reply"], "model": result["model"]},
                },
            )
        except Exception as exc:
            send_frame(
                sock,
                {
                    "type": "ERROR",
                    "request_id": frame.get("request_id"),
                    "code": "PYTHON_WORKER",
                    "message": str(exc),
                },
            )


if __name__ == "__main__":
    main()
