// AUTO-GENERATED BY silc — DO NOT EDIT
//
// Silc loop kernel (ADR-014). Runs the lowered loop plan: schedules, manual
// requests, and resource mutations start runs; every nondeterministic input is
// recorded in loop_events; effects reserve and commit receipts in
// loop_receipts; approvals suspend a run until a person decides in /loops.
package main

import (
	"bytes"
	"crypto/sha256"
	"database/sql"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"html"
	"io"
	"math"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
	_ "time/tzdata"

	_ "modernc.org/sqlite"
)

const protocolVersion = 1

// ---------------------------------------------------------------- plan

type Plan struct {
	PlanVersion     int                    `json:"plan_version"`
	CompilerVersion string                 `json:"compiler_version"`
	Hash            string                 `json:"hash"`
	Loops           []LoopPlan             `json:"loops"`
	Contracts       map[string][]FieldSpec `json:"contracts"`
	Tables          PlanTables             `json:"tables"`
	ResourceTables  []string               `json:"resource_tables"`
}

type PlanTables struct {
	Runs      string `json:"runs"`
	Approvals string `json:"approvals"`
	Notices   string `json:"notices"`
	Requests  string `json:"requests"`
}

type FieldSpec struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type LoopPlan struct {
	Name    string  `json:"name"`
	TZ      string  `json:"tz"`
	Trigger Trigger `json:"trigger"`
	Steps   []Step  `json:"steps"`
}

type Trigger struct {
	Kind           string `json:"kind"`
	Cron           string `json:"cron"`
	TZ             string `json:"tz"`
	CatchUpMinutes int    `json:"catch_up_minutes"`
	Resource       string `json:"resource"`
	Table          string `json:"table"`
	Contract       string `json:"contract"`
	Mutation       string `json:"mutation"`
}

type Arm struct {
	That  *Expr  `json:"that"`
	Steps []Step `json:"steps"`
}

type Step struct {
	Op            string   `json:"op"`
	Path          string   `json:"path"`
	As            string   `json:"as"`
	Reason        string   `json:"reason"`
	Prompt        string   `json:"prompt"`
	Key           string   `json:"key"`
	Unchecked     string   `json:"unchecked"`
	By            string   `json:"by"`
	Message       string   `json:"message"`
	Text          string   `json:"text"`
	To            string   `json:"to"`
	Where         *Expr    `json:"where"`
	URL           *Expr    `json:"url"`
	From          *Expr    `json:"from"`
	That          *Expr    `json:"that"`
	In            *Expr    `json:"in"`
	Value         *Expr    `json:"value"`
	Show          *Expr    `json:"show"`
	Resource      string   `json:"resource"`
	Table         string   `json:"table"`
	Contract      string   `json:"contract"`
	RowFields     []string `json:"row_fields"`
	Order         string   `json:"order"`
	Desc          bool     `json:"desc"`
	One           bool     `json:"one"`
	Max           int      `json:"max"`
	Retry         int      `json:"retry"`
	ReadOp        string   `json:"read_op"`
	Server        string   `json:"server"`
	Tool          string   `json:"tool"`
	Args          *Expr    `json:"args"`
	AuthEnv       string   `json:"auth_env"`
	Select        string   `json:"select"`
	Into          string   `json:"into"`
	Mode          string   `json:"mode"`
	WithinMinutes int      `json:"within_minutes"`
	Otherwise     []Step   `json:"otherwise"`
	Steps         []Step   `json:"steps"`
	Declined      []Step   `json:"declined"`
	TimedOut      []Step   `json:"timed_out"`
	Arms          []Arm    `json:"arms"`
}

type NewField struct {
	Name  string `json:"name"`
	Value *Expr  `json:"value"`
}

type Expr struct {
	K      string     `json:"k"`
	S      string     `json:"s"`
	N      float64    `json:"n"`
	B      bool       `json:"b"`
	Name   string     `json:"name"`
	Base   *Expr      `json:"base"`
	Field  string     `json:"field"`
	Op     string     `json:"op"`
	L      *Expr      `json:"l"`
	R      *Expr      `json:"r"`
	E      *Expr      `json:"e"`
	Items  []Expr     `json:"items"`
	Type   string     `json:"type"`
	Fields []NewField `json:"fields"`
}

func loadPlan(path string) (*Plan, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var p Plan
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("decode %s: %w", path, err)
	}
	if p.Hash == "" {
		return nil, fmt.Errorf("plan %s has no hash", path)
	}
	return &p, nil
}

func (p *Plan) loop(name string) *LoopPlan {
	for i := range p.Loops {
		if p.Loops[i].Name == name {
			return &p.Loops[i]
		}
	}
	return nil
}

// ---------------------------------------------------------------- kernel

type AskRequest struct {
	Loop    string
	Prompt  string
	Context string
	Schema  string
}

type Asker interface {
	Ask(req AskRequest) (string, error)
}

type Page struct {
	URL    string `json:"url"`
	Status int    `json:"status"`
	Title  string `json:"title"`
	Text   string `json:"text"`
}

type Kernel struct {
	db       *sql.DB
	plan     *Plan
	plansDir string
	plans    map[string]*Plan
	now      func() time.Time
	asker    Asker
	fetch    func(url string) (Page, error)
	mcp      func(server, tool string, args map[string]any, token string) (map[string]any, error)
	// crash is a test hook called at effect checkpoints ("after_reserve").
	crash func(point, path string)
	logf  func(format string, args ...any)
}

func NewKernel(db *sql.DB, plan *Plan, plansDir string) (*Kernel, error) {
	k := &Kernel{
		db:       db,
		plan:     plan,
		plansDir: plansDir,
		plans:    map[string]*Plan{plan.Hash: plan},
		now:      time.Now,
		fetch:    fetchPage,
		mcp:      mcpCall,
		logf: func(format string, args ...any) {
			fmt.Fprintf(os.Stderr, "silc loop: "+format+"\n", args...)
		},
	}
	if plansDir != "" {
		if err := os.MkdirAll(plansDir, 0o755); err == nil {
			pinned := filepath.Join(plansDir, plan.Hash+".json")
			if _, err := os.Stat(pinned); errors.Is(err, os.ErrNotExist) {
				if data, err := json.MarshalIndent(plan, "", "  "); err == nil {
					_ = os.WriteFile(pinned, data, 0o644)
				}
			}
		}
	}
	return k, k.initSchema()
}

func (k *Kernel) initSchema() error {
	tables := append([]string{}, k.plan.ResourceTables...)
	for _, t := range []string{k.plan.Tables.Runs, k.plan.Tables.Approvals, k.plan.Tables.Notices, k.plan.Tables.Requests} {
		if t != "" && !contains(tables, t) {
			tables = append(tables, t)
		}
	}
	for _, t := range tables {
		if _, err := k.db.Exec(fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %s (
			id TEXT PRIMARY KEY,
			data TEXT NOT NULL,
			created_at TEXT NOT NULL DEFAULT (datetime('now')),
			updated_at TEXT NOT NULL DEFAULT (datetime('now'))
		)`, t)); err != nil {
			return err
		}
	}
	_, err := k.db.Exec(`
		CREATE TABLE IF NOT EXISTS loop_events (
			run_id TEXT NOT NULL,
			seq INTEGER NOT NULL,
			path TEXT NOT NULL,
			kind TEXT NOT NULL,
			value TEXT NOT NULL,
			at TEXT NOT NULL,
			PRIMARY KEY (run_id, seq)
		);
		CREATE INDEX IF NOT EXISTS loop_events_lookup ON loop_events (run_id, path, kind);
		CREATE TABLE IF NOT EXISTS loop_receipts (
			op TEXT NOT NULL,
			key TEXT NOT NULL,
			status TEXT NOT NULL,
			run_id TEXT NOT NULL,
			receipt TEXT NOT NULL DEFAULT '',
			at TEXT NOT NULL,
			PRIMARY KEY (op, key)
		);
		CREATE TABLE IF NOT EXISTS loop_schedule (
			loop TEXT PRIMARY KEY,
			last_seen TEXT NOT NULL
		);
		CREATE TABLE IF NOT EXISTS loop_watermarks (
			loop TEXT PRIMARY KEY,
			mark TEXT NOT NULL
		);
	`)
	return err
}

func (k *Kernel) planByHash(hash string) (*Plan, error) {
	if p, ok := k.plans[hash]; ok {
		return p, nil
	}
	p, err := loadPlan(filepath.Join(k.plansDir, hash+".json"))
	if err != nil {
		return nil, fmt.Errorf("pinned plan %s is missing: %w", hash, err)
	}
	k.plans[hash] = p
	return p, nil
}

// Tick runs one scheduler pass: triggers, then resumable runs.
func (k *Kernel) Tick() {
	for i := range k.plan.Loops {
		lp := &k.plan.Loops[i]
		var err error
		switch lp.Trigger.Kind {
		case "schedule":
			err = k.checkSchedule(lp)
		case "on_mutation":
			err = k.checkMutations(lp)
		}
		if err != nil {
			k.logf("%s: trigger: %v", lp.Name, err)
		}
	}
	if err := k.checkRequests(); err != nil {
		k.logf("manual requests: %v", err)
	}
	if err := k.resumeRuns(); err != nil {
		k.logf("resume: %v", err)
	}
}

// ---------------------------------------------------------------- rows

func (k *Kernel) dbNow() string {
	var s string
	_ = k.db.QueryRow(`SELECT datetime('now')`).Scan(&s)
	return s
}

func getRow(q interface {
	QueryRow(string, ...any) *sql.Row
}, table, id string) (map[string]any, bool, error) {
	var data string
	err := q.QueryRow(fmt.Sprintf(`SELECT data FROM %s WHERE id = ?`, table), id).Scan(&data)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, err
	}
	row := map[string]any{}
	if err := json.Unmarshal([]byte(data), &row); err != nil {
		return nil, false, err
	}
	row["id"] = id
	return row, true, nil
}

func encodeData(row map[string]any) string {
	stored := map[string]any{}
	for k, v := range row {
		if k != "id" {
			stored[k] = v
		}
	}
	b, _ := json.Marshal(stored)
	return string(b)
}

func (k *Kernel) updateData(table, id string, patch map[string]any) error {
	row, ok, err := getRow(k.db, table, id)
	if err != nil || !ok {
		return err
	}
	for f, v := range patch {
		row[f] = v
	}
	_, err = k.db.Exec(fmt.Sprintf(`UPDATE %s SET data = ?, updated_at = datetime('now') WHERE id = ?`, table), encodeData(row), id)
	return err
}

func shortHash(parts ...string) string {
	h := sha256.Sum256([]byte(strings.Join(parts, "\x1f")))
	return hex.EncodeToString(h[:])[:16]
}

// ---------------------------------------------------------------- runs

type Run struct {
	ID   string
	Data map[string]any
}

func (k *Kernel) activeRun(loop string) (bool, error) {
	var n int
	err := k.db.QueryRow(fmt.Sprintf(
		`SELECT COUNT(*) FROM %s WHERE json_extract(data, '$.loop') = ? AND json_extract(data, '$.status') IN ('running', 'waiting')`,
		k.plan.Tables.Runs), loop).Scan(&n)
	return n > 0, err
}

// startRun creates at most one run per (loop, identity) and executes it.
func (k *Kernel) startRun(lp *LoopPlan, trigger, identity string, event map[string]any) (string, bool, error) {
	id := "run-" + shortHash(lp.Name, identity)
	data := map[string]any{
		"loop":        lp.Name,
		"plan":        k.plan.Hash,
		"trigger":     trigger,
		"identity":    identity,
		"status":      "running",
		"outcome":     "",
		"detail":      "",
		"started_at":  k.now().UTC().Format(time.RFC3339),
		"finished_at": "",
		"event":       event,
	}
	res, err := k.db.Exec(fmt.Sprintf(`INSERT OR IGNORE INTO %s (id, data) VALUES (?, ?)`, k.plan.Tables.Runs), id, encodeData(data))
	if err != nil {
		return id, false, err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return id, false, nil
	}
	k.logf("%s: run %s started (%s)", lp.Name, id, identity)
	k.execute(&Run{ID: id, Data: data})
	return id, true, nil
}

func (k *Kernel) loadRun(id string) (*Run, error) {
	row, ok, err := getRow(k.db, k.plan.Tables.Runs, id)
	if err != nil {
		return nil, err
	}
	if !ok {
		return nil, fmt.Errorf("run %s not found", id)
	}
	delete(row, "id")
	return &Run{ID: id, Data: row}, nil
}

// resumeRuns replays runs left running by a crash and waiting runs whose
// approvals changed or expired.
func (k *Kernel) resumeRuns() error {
	rows, err := k.db.Query(fmt.Sprintf(
		`SELECT id, json_extract(data, '$.status') FROM %s WHERE json_extract(data, '$.status') IN ('running', 'waiting') ORDER BY created_at`,
		k.plan.Tables.Runs))
	if err != nil {
		return err
	}
	type cand struct{ id, status string }
	var cands []cand
	for rows.Next() {
		var c cand
		if err := rows.Scan(&c.id, &c.status); err == nil {
			cands = append(cands, c)
		}
	}
	rows.Close()
	now := k.now().UTC().Format(time.RFC3339)
	for _, c := range cands {
		if c.status == "waiting" {
			var n int
			err := k.db.QueryRow(fmt.Sprintf(`SELECT COUNT(*) FROM %s WHERE json_extract(data, '$.run_id') = ? AND (
				(json_extract(data, '$.status') IN ('approved', 'declined') AND json_extract(data, '$.consumed') IS NULL)
				OR (json_extract(data, '$.status') = 'pending' AND json_extract(data, '$.deadline') <= ?))`,
				k.plan.Tables.Approvals), c.id, now).Scan(&n)
			if err != nil || n == 0 {
				continue
			}
		}
		run, err := k.loadRun(c.id)
		if err != nil {
			k.logf("resume %s: %v", c.id, err)
			continue
		}
		k.execute(run)
	}
	return nil
}

// ResumeRun replays one run regardless of status (tests and operators).
func (k *Kernel) ResumeRun(id string) error {
	run, err := k.loadRun(id)
	if err != nil {
		return err
	}
	k.execute(run)
	return nil
}

type sig int

const (
	sigNone sig = iota
	sigStop
	sigFail
	sigSkip
	sigSuspend
)

type outcome struct {
	s      sig
	reason string
}

var none = outcome{}

type scope struct {
	vars   map[string]any
	parent *scope
}

func (s *scope) get(name string) (any, bool) {
	for c := s; c != nil; c = c.parent {
		if v, ok := c.vars[name]; ok {
			return v, true
		}
	}
	return nil, false
}

func (s *scope) child() *scope { return &scope{vars: map[string]any{}, parent: s} }

type runCtx struct {
	k        *Kernel
	run      *Run
	plan     *Plan
	lp       *LoopPlan
	loc      *time.Location
	recorded map[string]string
	seq      int
	partial  bool
	items    map[string]int
}

func (k *Kernel) finish(run *Run, status, outcome, detail string) {
	patch := map[string]any{"status": status, "outcome": outcome, "detail": detail}
	if status == "finished" {
		patch["finished_at"] = k.now().UTC().Format(time.RFC3339)
	}
	if err := k.updateData(k.plan.Tables.Runs, run.ID, patch); err != nil {
		k.logf("run %s: update status: %v", run.ID, err)
	}
	k.logf("run %s: %s %s %s", run.ID, status, outcome, detail)
}

func (k *Kernel) execute(run *Run) {
	loopName, _ := run.Data["loop"].(string)
	hash, _ := run.Data["plan"].(string)
	plan, err := k.planByHash(hash)
	if err != nil {
		k.finish(run, "finished", "failed", err.Error())
		return
	}
	lp := plan.loop(loopName)
	if lp == nil {
		k.finish(run, "finished", "failed", fmt.Sprintf("loop %s is not in pinned plan %s", loopName, hash))
		return
	}
	loc, err := time.LoadLocation(lp.TZ)
	if err != nil {
		k.finish(run, "finished", "failed", fmt.Sprintf("time zone %q: %v", lp.TZ, err))
		return
	}
	ctx := &runCtx{k: k, run: run, plan: plan, lp: lp, loc: loc, recorded: map[string]string{}, items: map[string]int{}}
	if err := ctx.loadEvents(); err != nil {
		k.finish(run, "finished", "failed", err.Error())
		return
	}
	if status, _ := run.Data["status"].(string); status != "running" {
		_ = k.updateData(k.plan.Tables.Runs, run.ID, map[string]any{"status": "running"})
	}
	clockNow := k.now().In(loc)
	day := func(offset int) string { return clockNow.AddDate(0, 0, offset).Format("2006-01-02") }
	clockRaw := ctx.record("clock", "clock", map[string]any{
		"now":   clockNow.Format(time.RFC3339),
		"today": day(0),
		"calendar": map[string]any{
			"today":       day(0),
			"weekday":     clockNow.Weekday().String(),
			"last7_start": day(-6),
			"last7_end":   day(0),
			"next7_end":   day(6),
		},
	})
	var clock map[string]any
	_ = json.Unmarshal([]byte(clockRaw), &clock)
	root := &scope{vars: map[string]any{
		"now":   clock["now"],
		"today": clock["today"],
		"event":    run.Data["event"],
		"calendar": clock["calendar"],
	}}
	var out outcome
	func() {
		defer func() {
			if r := recover(); r != nil {
				if _, ok := r.(crashSignal); ok {
					panic(r)
				}
				out = outcome{sigFail, fmt.Sprintf("kernel error: %v", r)}
			}
		}()
		out = ctx.block(lp.Steps, root, "", false)
	}()
	detail := ctx.itemSummary()
	switch out.s {
	case sigSuspend:
		k.finish(run, "waiting", "", joinDetail("waiting for approval", detail))
	case sigStop:
		k.finish(run, "finished", "stopped", joinDetail(out.reason, detail))
	case sigFail:
		k.finish(run, "finished", "failed", joinDetail(out.reason, detail))
	default:
		if ctx.partial {
			k.finish(run, "finished", "partial", detail)
		} else {
			k.finish(run, "finished", "succeeded", detail)
		}
	}
}

func joinDetail(a, b string) string {
	if a == "" {
		return b
	}
	if b == "" {
		return a
	}
	return a + "; " + b
}

func (c *runCtx) itemSummary() string {
	if len(c.items) == 0 {
		return ""
	}
	var parts []string
	for _, k := range []string{"done", "skipped", "failed", "waiting"} {
		if n := c.items[k]; n > 0 {
			parts = append(parts, fmt.Sprintf("%d %s", n, k))
		}
	}
	return "items: " + strings.Join(parts, ", ")
}

func (c *runCtx) loadEvents() error {
	rows, err := c.k.db.Query(`SELECT seq, path, kind, value FROM loop_events WHERE run_id = ? ORDER BY seq`, c.run.ID)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var seq int
		var path, kind, value string
		if err := rows.Scan(&seq, &path, &kind, &value); err != nil {
			return err
		}
		c.recorded[path+"|"+kind] = value
		if seq >= c.seq {
			c.seq = seq + 1
		}
	}
	return rows.Err()
}

// record returns the recorded value for (path, kind), appending it first if new.
func (c *runCtx) record(path, kind string, value any) string {
	key := path + "|" + kind
	if v, ok := c.recorded[key]; ok {
		return v
	}
	b, _ := json.Marshal(value)
	if _, err := c.k.db.Exec(`INSERT INTO loop_events (run_id, seq, path, kind, value, at) VALUES (?, ?, ?, ?, ?, ?)`,
		c.run.ID, c.seq, path, kind, string(b), c.k.now().UTC().Format(time.RFC3339Nano)); err != nil {
		panic(fmt.Sprintf("append event: %v", err))
	}
	c.seq++
	c.recorded[key] = string(b)
	return string(b)
}

func (c *runCtx) recordedValue(path, kind string) (string, bool) {
	v, ok := c.recorded[path+"|"+kind]
	return v, ok
}

func stepPath(prefix string, i int) string {
	if prefix == "" {
		return strconv.Itoa(i)
	}
	return prefix + "." + strconv.Itoa(i)
}

func (c *runCtx) block(steps []Step, sc *scope, prefix string, inEach bool) outcome {
	for i := range steps {
		out := c.step(&steps[i], sc, stepPath(prefix, i), inEach)
		if out.s != sigNone {
			return out
		}
	}
	return none
}

func (c *runCtx) step(st *Step, sc *scope, path string, inEach bool) outcome {
	switch st.Op {
	case "let":
		v, _ := eval(st.Value, sc)
		sc.vars[st.As] = v
	case "find":
		raw, ok := c.recordedValue(path, "find")
		if !ok {
			rows, err := c.find(st, sc)
			if err != nil {
				return outcome{sigFail, fmt.Sprintf("loop::find %s: %v", st.Resource, err)}
			}
			raw = c.record(path, "find", rows)
		}
		var rows []any
		_ = json.Unmarshal([]byte(raw), &rows)
		if st.One {
			if len(rows) > 0 {
				sc.vars[st.As] = rows[0]
			} else {
				sc.vars[st.As] = nil
			}
		} else {
			if rows == nil {
				rows = []any{}
			}
			sc.vars[st.As] = rows
		}
	case "read":
		raw, ok := c.recordedValue(path, "read")
		if !ok {
			raw = c.record(path, "read", c.read(st, sc))
		}
		var res map[string]any
		_ = json.Unmarshal([]byte(raw), &res)
		if errText, _ := res["error"].(string); errText != "" {
			return outcome{sigFail, "loop::read: " + errText}
		}
		sc.vars[st.As] = res["page"]
	case "ask":
		raw, ok := c.recordedValue(path, "ask")
		if !ok {
			raw = c.record(path, "ask", c.ask(st, sc))
		}
		var res map[string]any
		_ = json.Unmarshal([]byte(raw), &res)
		if okv, _ := res["ok"].(bool); !okv {
			errText, _ := res["error"].(string)
			c.record(path, "trace:ask_failed", errText)
			if st.Otherwise != nil {
				return c.block(st.Otherwise, sc.child(), path+".otherwise", inEach)
			}
			return outcome{sigFail, fmt.Sprintf("loop::ask could not produce a valid %s: %s", st.Into, errText)}
		}
		sc.vars[st.As] = res["value"]
	case "gate":
		v, known := eval(st.That, sc)
		if b, isBool := v.(bool); known && isBool && b {
			return none
		}
		c.record(path, "trace:gate_blocked", st.Reason)
		if st.Otherwise != nil {
			return c.block(st.Otherwise, sc.child(), path+".otherwise", inEach)
		}
		return outcome{sigFail, "gate blocked: " + st.Reason}
	case "branch":
		for i, arm := range st.Arms {
			v, known := eval(arm.That, sc)
			if b, isBool := v.(bool); known && isBool && b {
				return c.block(arm.Steps, sc.child(), fmt.Sprintf("%s.when%d", path, i), inEach)
			}
		}
		return c.block(st.Otherwise, sc.child(), path+".otherwise", inEach)
	case "each":
		v, known := eval(st.In, sc)
		if !known {
			return outcome{sigFail, "loop::each :in is unknown"}
		}
		list, isList := v.([]any)
		if !isList {
			return outcome{sigFail, "loop::each :in is not a list"}
		}
		if len(list) > st.Max {
			return outcome{sigFail, fmt.Sprintf("loop::each has %d items; :max is %d", len(list), st.Max)}
		}
		waiting := 0
		for i, item := range list {
			itemScope := sc.child()
			itemScope.vars[st.As] = item
			out := c.block(st.Steps, itemScope, fmt.Sprintf("%s[%d]", path, i), true)
			switch out.s {
			case sigNone:
				c.items["done"]++
			case sigSkip:
				c.items["skipped"]++
				c.record(fmt.Sprintf("%s[%d]", path, i), "trace:skipped", out.reason)
			case sigFail:
				c.items["failed"]++
				c.partial = true
				c.record(fmt.Sprintf("%s[%d]", path, i), "trace:failed", out.reason)
			case sigSuspend:
				c.items["waiting"]++
				waiting++
			case sigStop:
				return out
			}
		}
		if waiting > 0 {
			return outcome{s: sigSuspend}
		}
	case "write":
		return c.write(st, sc, path)
	case "notify":
		return c.notify(st, sc, path)
	case "approve":
		return c.approve(st, sc, path, inEach)
	case "stop":
		return outcome{sigStop, renderLoose(st.Reason, sc)}
	case "fail":
		return outcome{sigFail, renderLoose(st.Reason, sc)}
	case "skip":
		return outcome{sigSkip, renderLoose(st.Reason, sc)}
	default:
		return outcome{sigFail, "unknown loop step " + st.Op}
	}
	return none
}

func (c *runCtx) find(st *Step, sc *scope) ([]any, error) {
	rows, err := c.k.db.Query(fmt.Sprintf(`SELECT id, data FROM %s ORDER BY created_at, id`, st.Table))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []any
	for rows.Next() {
		var id, data string
		if err := rows.Scan(&id, &data); err != nil {
			return nil, err
		}
		row := map[string]any{}
		if json.Unmarshal([]byte(data), &row) != nil {
			continue
		}
		row["id"] = id
		if st.Where != nil {
			rowScope := sc.child()
			for _, f := range st.RowFields {
				if v, ok := row[f]; ok {
					rowScope.vars[f] = v
				} else {
					rowScope.vars[f] = nil
				}
			}
			v, known := eval(st.Where, rowScope)
			if b, isBool := v.(bool); !known || !isBool || !b {
				continue
			}
		}
		out = append(out, row)
	}
	if st.Order != "" {
		sort.SliceStable(out, func(i, j int) bool {
			a := out[i].(map[string]any)[st.Order]
			b := out[j].(map[string]any)[st.Order]
			less, known := compare(a, b)
			if !known {
				return false
			}
			if st.Desc {
				return less > 0
			}
			return less < 0
		})
	}
	limit := st.Max
	if st.One {
		limit = 1
	}
	if limit > 0 && len(out) > limit {
		out = out[:limit]
	}
	if out == nil {
		out = []any{}
	}
	return out, nil
}

func (c *runCtx) read(st *Step, sc *scope) map[string]any {
	if st.ReadOp == "mcp::call" {
		return c.callTool(st, sc)
	}
	v, known := eval(st.URL, sc)
	url, isStr := v.(string)
	if !known || !isStr || !(strings.HasPrefix(url, "http://") || strings.HasPrefix(url, "https://")) {
		return map[string]any{"error": "url is unknown or not http(s)"}
	}
	var lastErr error
	for attempt := 0; attempt <= st.Retry; attempt++ {
		page, err := c.k.fetch(url)
		if err == nil {
			return map[string]any{"page": page}
		}
		lastErr = err
		if attempt < st.Retry {
			time.Sleep(time.Duration(200*(attempt+1)) * time.Millisecond)
		}
	}
	return map[string]any{"error": lastErr.Error()}
}

func (c *runCtx) schemaText(contract string) string {
	var parts []string
	for _, f := range c.plan.Contracts[contract] {
		parts = append(parts, fmt.Sprintf("%q (%s)", f.Name, f.Type))
	}
	return strings.Join(parts, ", ")
}

func (c *runCtx) ask(st *Step, sc *scope) map[string]any {
	if c.k.asker == nil {
		return map[string]any{"ok": false, "error": "silclm is not connected"}
	}
	context := ""
	if st.From != nil {
		v, _ := eval(st.From, sc)
		b, _ := json.Marshal(v)
		context = string(b)
		if list, isList := v.([]any); isList {
			for len(list) > 1 && len(context) > maxAskContext {
				list = trimOldest(list)
				b, _ = json.Marshal(list)
				context = string(b)
			}
		}
		if len(context) > maxAskContext {
			context = context[:maxAskContext]
		}
	}
	req := AskRequest{
		Loop:    c.lp.Name,
		Prompt:  renderLoose(st.Prompt, sc),
		Context: context,
		Schema:  c.schemaText(st.Into),
	}
	var lastErr string
	for attempt := 0; attempt <= st.Retry; attempt++ {
		reply, err := c.k.asker.Ask(req)
		if err != nil {
			lastErr = err.Error()
			continue
		}
		value, verr := checkContract(c.plan.Contracts[st.Into], reply)
		if verr == nil {
			return map[string]any{"ok": true, "value": value, "attempts": attempt + 1}
		}
		lastErr = verr.Error()
	}
	return map[string]any{"ok": false, "error": lastErr}
}

// maxAskContext keeps one ask inside a 16KiB IPC slot after JSON escaping.
const maxAskContext = 9000

// trimOldest shortens the largest nested list (tool windows are oldest first),
// or drops the first item when the list holds no lists.
func trimOldest(list []any) []any {
	largest, size := -1, 0
	for i, item := range list {
		if inner, ok := item.([]any); ok && len(inner) > 1 {
			b, _ := json.Marshal(inner)
			if len(b) > size {
				largest, size = i, len(b)
			}
		}
	}
	if largest < 0 {
		return list[1:]
	}
	out := append([]any{}, list...)
	out[largest] = out[largest].([]any)[1:]
	return out
}

// firstJSONObject returns the first brace-balanced object in a model reply.
// A greedy match would swallow a later "}" in trailing prose and then fail
// to parse ("invalid character after top-level value").
func firstJSONObject(s string) string {
	start := strings.IndexByte(s, '{')
	if start < 0 {
		return ""
	}
	depth := 0
	inStr := false
	esc := false
	for i := start; i < len(s); i++ {
		c := s[i]
		if inStr {
			if esc {
				esc = false
				continue
			}
			if c == '\\' {
				esc = true
				continue
			}
			if c == '"' {
				inStr = false
			}
			continue
		}
		switch c {
		case '"':
			inStr = true
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return s[start : i+1]
			}
		}
	}
	return ""
}

// checkContract parses a model reply and requires every contract field with the right type.
// A blank string is not a Str: the model must put real text in every field.
func checkContract(fields []FieldSpec, reply string) (map[string]any, error) {
	match := firstJSONObject(reply)
	if match == "" {
		return nil, fmt.Errorf("reply has no JSON object")
	}
	var obj map[string]any
	if err := json.Unmarshal([]byte(match), &obj); err != nil {
		return nil, fmt.Errorf("reply is not valid JSON: %v", err)
	}
	out := map[string]any{}
	for _, f := range fields {
		v, present := obj[f.Name]
		optional := strings.HasSuffix(f.Type, "?")
		ty := strings.TrimSuffix(f.Type, "?")
		if !present || v == nil {
			if optional {
				out[f.Name] = nil
				continue
			}
			return nil, fmt.Errorf("field %q is missing", f.Name)
		}
		ok := false
		switch ty {
		case "Str", "UUID":
			s, isStr := v.(string)
			ok = isStr && strings.TrimSpace(s) != ""
			if isStr {
				v = strings.TrimSpace(s)
			}
		case "Int", "int32", "int64":
			n, isNum := v.(float64)
			ok = isNum && n == math.Trunc(n)
		case "num32", "num64":
			_, ok = v.(float64)
		case "Bool":
			_, ok = v.(bool)
		case "List":
			_, ok = v.([]any)
		default:
			_, isStr := v.(string)
			_, isObj := v.(map[string]any)
			ok = isStr || isObj
		}
		if !ok {
			return nil, fmt.Errorf("field %q must be %s", f.Name, ty)
		}
		out[f.Name] = v
	}
	return out, nil
}

type crashSignal struct{ point, path string }

func (c *runCtx) checkpoint(point, path string) {
	if c.k.crash != nil {
		c.k.crash(point, path)
	}
}

// effect reserves a receipt, runs apply inside one transaction with the
// receipt commit, and is a no-op once the receipt is committed.
func (c *runCtx) effect(op, key, path string, apply func(tx *sql.Tx) (map[string]any, error)) outcome {
	var status string
	err := c.k.db.QueryRow(`SELECT status FROM loop_receipts WHERE op = ? AND key = ?`, op, key).Scan(&status)
	if err == nil && status == "committed" {
		c.record(path, "trace:effect_skipped", map[string]any{"op": op, "key": key})
		return none
	}
	if errors.Is(err, sql.ErrNoRows) {
		if _, err := c.k.db.Exec(`INSERT OR IGNORE INTO loop_receipts (op, key, status, run_id, at) VALUES (?, ?, 'started', ?, ?)`,
			op, key, c.run.ID, c.k.now().UTC().Format(time.RFC3339)); err != nil {
			return outcome{sigFail, "reserve receipt: " + err.Error()}
		}
	} else if err != nil {
		return outcome{sigFail, "read receipt: " + err.Error()}
	}
	c.checkpoint("after_reserve", path)
	tx, err := c.k.db.Begin()
	if err != nil {
		return outcome{sigFail, err.Error()}
	}
	receipt, err := apply(tx)
	if err != nil {
		_ = tx.Rollback()
		return outcome{sigFail, err.Error()}
	}
	b, _ := json.Marshal(receipt)
	if _, err := tx.Exec(`UPDATE loop_receipts SET status = 'committed', receipt = ?, run_id = ?, at = ? WHERE op = ? AND key = ?`,
		string(b), c.run.ID, c.k.now().UTC().Format(time.RFC3339), op, key); err != nil {
		_ = tx.Rollback()
		return outcome{sigFail, err.Error()}
	}
	if err := tx.Commit(); err != nil {
		return outcome{sigFail, err.Error()}
	}
	c.record(path, "trace:effect", map[string]any{"op": op, "key": key, "receipt": receipt})
	return none
}

func (c *runCtx) write(st *Step, sc *scope, path string) outcome {
	key, ok := renderStrict(st.Key, sc)
	if !ok {
		return outcome{sigFail, "loop::write :key has an unknown placeholder"}
	}
	v, _ := eval(st.Value, sc)
	value, isMap := v.(map[string]any)
	if !isMap {
		return outcome{sigFail, "loop::write :value is unknown"}
	}
	op := "write:" + st.Table
	return c.effect(op, key, path, func(tx *sql.Tx) (map[string]any, error) {
		if st.Mode == "update" {
			id, _ := value["id"].(string)
			if id == "" {
				return nil, fmt.Errorf("update needs an id")
			}
			row, found, err := getRow(tx, st.Table, id)
			if err != nil {
				return nil, err
			}
			if !found {
				return nil, fmt.Errorf("%s row %s not found", st.Resource, id)
			}
			for f, fv := range value {
				if f != "id" && fv != nil {
					row[f] = fv
				}
			}
			if _, err := tx.Exec(fmt.Sprintf(`UPDATE %s SET data = ?, updated_at = datetime('now') WHERE id = ?`, st.Table), encodeData(row), id); err != nil {
				return nil, err
			}
			return map[string]any{"table": st.Table, "id": id, "mode": "update"}, nil
		}
		id, _ := value["id"].(string)
		if id == "" {
			id = "loop-" + shortHash(op, key)
		}
		row := map[string]any{}
		for f, fv := range value {
			if fv != nil {
				row[f] = fv
			}
		}
		if _, err := tx.Exec(fmt.Sprintf(`INSERT OR IGNORE INTO %s (id, data) VALUES (?, ?)`, st.Table), id, encodeData(row)); err != nil {
			return nil, err
		}
		return map[string]any{"table": st.Table, "id": id, "mode": "create"}, nil
	})
}

func (c *runCtx) notify(st *Step, sc *scope, path string) outcome {
	key, ok := renderStrict(st.Key, sc)
	if !ok {
		return outcome{sigFail, "loop::notify :key has an unknown placeholder"}
	}
	to := renderLoose(st.To, sc)
	text := renderLoose(st.Text, sc)
	table := c.plan.Tables.Notices
	return c.effect("notify", key, path, func(tx *sql.Tx) (map[string]any, error) {
		id := "notice-" + shortHash(c.lp.Name, key)
		row := map[string]any{"loop": c.lp.Name, "run_id": c.run.ID, "to": to, "text": text, "key": key}
		if _, err := tx.Exec(fmt.Sprintf(`INSERT OR IGNORE INTO %s (id, data) VALUES (?, ?)`, table), id, encodeData(row)); err != nil {
			return nil, err
		}
		return map[string]any{"table": table, "id": id}, nil
	})
}

func sameName(a, b string) bool {
	return strings.EqualFold(strings.TrimSpace(a), strings.TrimSpace(b))
}

func (c *runCtx) approve(st *Step, sc *scope, path string, inEach bool) outcome {
	raw, decided := c.recordedValue(path, "approve")
	if !decided {
		table := c.plan.Tables.Approvals
		id := "apr-" + shortHash(c.run.ID, path)
		by := renderLoose(st.By, sc)
		row, found, err := getRow(c.k.db, table, id)
		if err != nil {
			return outcome{sigFail, err.Error()}
		}
		now := c.k.now()
		if !found {
			reqRaw := c.record(path, "approve_requested", map[string]any{
				"deadline": now.Add(time.Duration(st.WithinMinutes) * time.Minute).UTC().Format(time.RFC3339),
			})
			var req map[string]any
			_ = json.Unmarshal([]byte(reqRaw), &req)
			deadline, _ := req["deadline"].(string)
			show := ""
			if st.Show != nil {
				v, _ := eval(st.Show, sc)
				show = display(v)
			}
			local := deadline
			if t, err := time.Parse(time.RFC3339, deadline); err == nil {
				local = t.In(c.loc).Format("Mon Jan 2 15:04 MST")
			}
			data := map[string]any{
				"loop": c.lp.Name, "run_id": c.run.ID, "step": path, "by": by,
				"message": renderLoose(st.Message, sc), "show": show,
				"summary": fmt.Sprintf("Approver: %s · decide by %s", by, local),
				"status":  "pending", "deadline": deadline,
				"decided_by": "", "decided_at": "", "note": "",
			}
			if _, err := c.k.db.Exec(fmt.Sprintf(`INSERT OR IGNORE INTO %s (id, data) VALUES (?, ?)`, table), id, encodeData(data)); err != nil {
				return outcome{sigFail, err.Error()}
			}
			return outcome{s: sigSuspend}
		}
		status, _ := row["status"].(string)
		deadline, _ := row["deadline"].(string)
		var decision map[string]any
		switch status {
		case "approved", "declined":
			decidedBy, _ := row["decided_by"].(string)
			if !sameName(decidedBy, by) {
				_ = c.k.updateData(table, id, map[string]any{
					"status": "pending", "decided_by": "",
					"note": fmt.Sprintf("Only %s can decide this; %q tried.", by, decidedBy),
				})
				return outcome{s: sigSuspend}
			}
			decision = map[string]any{"outcome": status, "by": decidedBy, "decided_at": now.UTC().Format(time.RFC3339), "note": ""}
		default:
			if deadline != "" && now.UTC().Format(time.RFC3339) >= deadline {
				decision = map[string]any{"outcome": "timed_out", "by": "", "decided_at": now.UTC().Format(time.RFC3339), "note": ""}
			} else {
				return outcome{s: sigSuspend}
			}
		}
		raw = c.record(path, "approve", decision)
		final := decision["outcome"].(string)
		_ = c.k.updateData(table, id, map[string]any{"status": final, "decided_at": decision["decided_at"], "consumed": true})
	}
	var decision map[string]any
	_ = json.Unmarshal([]byte(raw), &decision)
	if st.As != "" {
		sc.vars[st.As] = decision
	}
	switch decision["outcome"] {
	case "approved":
		return none
	case "declined":
		return c.block(st.Declined, sc.child(), path+".declined", inEach)
	default:
		return c.block(st.TimedOut, sc.child(), path+".timed_out", inEach)
	}
}

// ---------------------------------------------------------------- expressions

func eval(e *Expr, sc *scope) (any, bool) {
	if e == nil {
		return nil, false
	}
	switch e.K {
	case "str":
		return e.S, true
	case "num":
		return e.N, true
	case "bool":
		return e.B, true
	case "var":
		v, ok := sc.get(e.Name)
		return v, ok && v != nil
	case "member":
		base, known := eval(e.Base, sc)
		if !known {
			return nil, false
		}
		switch b := base.(type) {
		case map[string]any:
			v, ok := b[e.Field]
			return v, ok && v != nil
		case []any:
			if e.Field == "count" {
				return float64(len(b)), true
			}
		}
		return nil, false
	case "not":
		v, known := eval(e.E, sc)
		b, isBool := v.(bool)
		if !known || !isBool {
			return nil, false
		}
		return !b, true
	case "neg":
		v, known := eval(e.E, sc)
		n, isNum := toNumber(v)
		if !known || !isNum {
			return nil, false
		}
		return -n, true
	case "list":
		out := make([]any, 0, len(e.Items))
		for i := range e.Items {
			v, _ := eval(&e.Items[i], sc)
			out = append(out, v)
		}
		return out, true
	case "new":
		out := map[string]any{}
		for _, f := range e.Fields {
			v, _ := eval(f.Value, sc)
			out[f.Name] = v
		}
		return out, true
	case "bin":
		return evalBin(e, sc)
	}
	return nil, false
}

func evalBin(e *Expr, sc *scope) (any, bool) {
	switch e.Op {
	case "&&", "||":
		l, lk := eval(e.L, sc)
		r, rk := eval(e.R, sc)
		lb, lIsBool := l.(bool)
		rb, rIsBool := r.(bool)
		lk = lk && lIsBool
		rk = rk && rIsBool
		if e.Op == "&&" {
			if (lk && !lb) || (rk && !rb) {
				return false, true
			}
			if lk && rk {
				return true, true
			}
			return nil, false
		}
		if (lk && lb) || (rk && rb) {
			return true, true
		}
		if lk && rk {
			return false, true
		}
		return nil, false
	}
	l, lk := eval(e.L, sc)
	r, rk := eval(e.R, sc)
	if !lk || !rk {
		return nil, false
	}
	switch e.Op {
	case "==", "!=":
		cmp, known := compare(l, r)
		if !known {
			return nil, false
		}
		return (cmp == 0) == (e.Op == "=="), true
	case "<", "<=", ">", ">=":
		cmp, known := compare(l, r)
		if !known {
			return nil, false
		}
		switch e.Op {
		case "<":
			return cmp < 0, true
		case "<=":
			return cmp <= 0, true
		case ">":
			return cmp > 0, true
		default:
			return cmp >= 0, true
		}
	case "+":
		ln, lNum := l.(float64)
		rn, rNum := r.(float64)
		if lNum && rNum {
			return ln + rn, true
		}
		return stringify(l) + stringify(r), true
	case "-", "*", "/":
		ln, lNum := toNumber(l)
		rn, rNum := toNumber(r)
		if !lNum || !rNum {
			return nil, false
		}
		switch e.Op {
		case "-":
			return ln - rn, true
		case "*":
			return ln * rn, true
		default:
			if rn == 0 {
				return nil, false
			}
			return ln / rn, true
		}
	}
	return nil, false
}

func toNumber(v any) (float64, bool) {
	switch n := v.(type) {
	case float64:
		return n, true
	case string:
		f, err := strconv.ParseFloat(strings.TrimSpace(n), 64)
		return f, err == nil
	}
	return 0, false
}

// compare orders numbers numerically, then strings lexically (ISO dates sort).
func compare(a, b any) (int, bool) {
	if a == nil || b == nil {
		return 0, false
	}
	if ab, ok := a.(bool); ok {
		bb, ok := b.(bool)
		if !ok {
			return 0, false
		}
		if ab == bb {
			return 0, true
		}
		return 1, true
	}
	an, aNum := toNumber(a)
	bn, bNum := toNumber(b)
	if aNum && bNum {
		switch {
		case an < bn:
			return -1, true
		case an > bn:
			return 1, true
		}
		return 0, true
	}
	return strings.Compare(stringify(a), stringify(b)), true
}

func stringify(v any) string {
	switch x := v.(type) {
	case nil:
		return ""
	case string:
		return x
	case float64:
		if x == math.Trunc(x) && math.Abs(x) < 1e15 {
			return strconv.FormatInt(int64(x), 10)
		}
		return strconv.FormatFloat(x, 'f', -1, 64)
	case bool:
		return strconv.FormatBool(x)
	default:
		b, _ := json.Marshal(x)
		return string(b)
	}
}

func display(v any) string {
	m, ok := v.(map[string]any)
	if !ok {
		return stringify(v)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var lines []string
	for _, k := range keys {
		lines = append(lines, fmt.Sprintf("%s: %s", k, stringify(m[k])))
	}
	return strings.Join(lines, "\n")
}

var placeholder = regexp.MustCompile(`\{\s*\$?([A-Za-z0-9_\-]+(?:\.[A-Za-z0-9_\-]+)*)\s*\}`)

func lookupPath(path string, sc *scope) (any, bool) {
	parts := strings.Split(path, ".")
	e := &Expr{K: "var", Name: parts[0]}
	for _, p := range parts[1:] {
		e = &Expr{K: "member", Base: e, Field: p}
	}
	return eval(e, sc)
}

func renderStrict(t string, sc *scope) (string, bool) {
	ok := true
	out := placeholder.ReplaceAllStringFunc(t, func(m string) string {
		path := placeholder.FindStringSubmatch(m)[1]
		v, known := lookupPath(path, sc)
		if !known {
			ok = false
			return ""
		}
		return stringify(v)
	})
	return out, ok
}

func renderLoose(t string, sc *scope) string {
	return placeholder.ReplaceAllStringFunc(t, func(m string) string {
		path := placeholder.FindStringSubmatch(m)[1]
		v, known := lookupPath(path, sc)
		if !known {
			return "(unknown)"
		}
		return stringify(v)
	})
}

// ---------------------------------------------------------------- triggers

type cronField struct{ set map[int]bool; any bool }

type cronSpec struct{ min, hour, dom, month, dow cronField }

func parseCronField(text string, lo, hi int) (cronField, error) {
	f := cronField{set: map[int]bool{}, any: text == "*"}
	for _, part := range strings.Split(text, ",") {
		rng, step := part, 1
		if i := strings.Index(part, "/"); i >= 0 {
			rng = part[:i]
			s, err := strconv.Atoi(part[i+1:])
			if err != nil || s <= 0 {
				return f, fmt.Errorf("bad step %q", part)
			}
			step = s
		}
		a, b := lo, hi
		if rng != "*" {
			if i := strings.Index(rng, "-"); i >= 0 {
				var err1, err2 error
				a, err1 = strconv.Atoi(rng[:i])
				b, err2 = strconv.Atoi(rng[i+1:])
				if err1 != nil || err2 != nil {
					return f, fmt.Errorf("bad range %q", rng)
				}
			} else {
				n, err := strconv.Atoi(rng)
				if err != nil {
					return f, fmt.Errorf("bad value %q", rng)
				}
				a, b = n, n
				if step > 1 {
					b = hi
				}
			}
		}
		for v := a; v <= b; v += step {
			f.set[v] = true
		}
	}
	return f, nil
}

func parseCron(text string) (*cronSpec, error) {
	fields := strings.Fields(text)
	if len(fields) != 5 {
		return nil, fmt.Errorf("cron %q needs 5 fields", text)
	}
	var c cronSpec
	var err error
	if c.min, err = parseCronField(fields[0], 0, 59); err != nil {
		return nil, err
	}
	if c.hour, err = parseCronField(fields[1], 0, 23); err != nil {
		return nil, err
	}
	if c.dom, err = parseCronField(fields[2], 1, 31); err != nil {
		return nil, err
	}
	if c.month, err = parseCronField(fields[3], 1, 12); err != nil {
		return nil, err
	}
	if c.dow, err = parseCronField(fields[4], 0, 7); err != nil {
		return nil, err
	}
	if c.dow.set[7] {
		c.dow.set[0] = true
	}
	return &c, nil
}

func (c *cronSpec) matches(t time.Time) bool {
	if !c.min.set[t.Minute()] || !c.hour.set[t.Hour()] || !c.month.set[int(t.Month())] {
		return false
	}
	domOK := c.dom.set[t.Day()]
	dowOK := c.dow.set[int(t.Weekday())]
	if c.dom.any || c.dow.any {
		return domOK && dowOK
	}
	return domOK || dowOK
}

func (k *Kernel) checkSchedule(lp *LoopPlan) error {
	cron, err := parseCron(lp.Trigger.Cron)
	if err != nil {
		return err
	}
	loc, err := time.LoadLocation(lp.Trigger.TZ)
	if err != nil {
		return err
	}
	now := k.now().UTC().Truncate(time.Minute)
	var lastText string
	err = k.db.QueryRow(`SELECT last_seen FROM loop_schedule WHERE loop = ?`, lp.Name).Scan(&lastText)
	var last time.Time
	if errors.Is(err, sql.ErrNoRows) {
		last = now.Add(-time.Minute)
	} else if err != nil {
		return err
	} else if last, err = time.Parse(time.RFC3339, lastText); err != nil {
		last = now.Add(-time.Minute)
	}
	if !now.After(last) {
		return nil
	}
	if horizon := now.Add(-31 * 24 * time.Hour); last.Before(horizon) {
		last = horizon
	}
	window := time.Duration(lp.Trigger.CatchUpMinutes) * time.Minute
	earliest := last.Add(time.Minute)
	if floor := now.Add(-window); earliest.Before(floor) {
		earliest = floor
	}
	var firing time.Time
	missed := 0
	for t := now; !t.Before(last.Add(time.Minute)); t = t.Add(-time.Minute) {
		if !cron.matches(t.In(loc)) {
			continue
		}
		if t.Before(earliest) {
			missed++
			continue
		}
		if firing.IsZero() {
			firing = t
		} else {
			missed++
		}
		if missed > 1000 {
			break
		}
	}
	if _, err := k.db.Exec(`INSERT INTO loop_schedule (loop, last_seen) VALUES (?, ?)
		ON CONFLICT(loop) DO UPDATE SET last_seen = excluded.last_seen`, lp.Name, now.Format(time.RFC3339)); err != nil {
		return err
	}
	if missed > 0 {
		k.logf("%s: %d missed firing(s) outside the catch-up window were not run", lp.Name, missed)
	}
	if firing.IsZero() {
		return nil
	}
	if busy, err := k.activeRun(lp.Name); err != nil {
		return err
	} else if busy {
		k.logf("%s: skipped firing %s; previous run is still active", lp.Name, firing.In(loc).Format(time.RFC3339))
		_, _ = k.db.Exec(`INSERT INTO loop_events (run_id, seq, path, kind, value, at)
			VALUES (?, (SELECT COALESCE(MAX(seq), -1) + 1 FROM loop_events WHERE run_id = ?), 'schedule', 'skipped_overlap', ?, ?)`,
			"loop:"+lp.Name, "loop:"+lp.Name, strconv.Quote(firing.Format(time.RFC3339)), k.now().UTC().Format(time.RFC3339Nano))
		return nil
	}
	event := map[string]any{
		"scheduled_for": firing.In(loc).Format(time.RFC3339),
		"fired_at":      k.now().In(loc).Format(time.RFC3339),
		"late":          k.now().Sub(firing) > time.Minute,
	}
	_, _, err = k.startRun(lp, "schedule", "schedule:"+firing.Format(time.RFC3339), event)
	return err
}

func (k *Kernel) checkRequests() error {
	if k.plan.Tables.Requests == "" {
		return nil
	}
	rows, err := k.db.Query(fmt.Sprintf(`SELECT id, data, created_at FROM %s WHERE json_extract(data, '$.status') = 'pending' ORDER BY created_at, id`, k.plan.Tables.Requests))
	if err != nil {
		return err
	}
	type req struct {
		id, created string
		data        map[string]any
	}
	var reqs []req
	for rows.Next() {
		var r req
		var data string
		if rows.Scan(&r.id, &data, &r.created) == nil {
			r.data = map[string]any{}
			if json.Unmarshal([]byte(data), &r.data) == nil {
				reqs = append(reqs, r)
			}
		}
	}
	rows.Close()
	for _, r := range reqs {
		name, _ := r.data["loop"].(string)
		lp := k.plan.loop(name)
		if lp == nil || (lp.Trigger.Kind != "manual" && lp.Trigger.Kind != "schedule") {
			_ = k.updateData(k.plan.Tables.Requests, r.id, map[string]any{"status": "rejected"})
			continue
		}
		if busy, err := k.activeRun(name); err != nil || busy {
			continue
		}
		by, _ := r.data["requested_by"].(string)
		event := map[string]any{"requested_by": by, "requested_at": r.created}
		runID := "run-" + shortHash(lp.Name, "manual:"+r.id)
		_ = k.updateData(k.plan.Tables.Requests, r.id, map[string]any{"status": "started", "run_id": runID})
		if _, _, err := k.startRun(lp, "manual", "manual:"+r.id, event); err != nil {
			return err
		}
	}
	return nil
}

func (k *Kernel) checkMutations(lp *LoopPlan) error {
	var mark string
	err := k.db.QueryRow(`SELECT mark FROM loop_watermarks WHERE loop = ?`, lp.Name).Scan(&mark)
	if errors.Is(err, sql.ErrNoRows) {
		_, err = k.db.Exec(`INSERT INTO loop_watermarks (loop, mark) VALUES (?, ?)`, lp.Name, k.dbNow())
		return err
	} else if err != nil {
		return err
	}
	column := "updated_at"
	extra := "AND updated_at > created_at"
	if lp.Trigger.Mutation == "create" {
		column = "created_at"
		extra = ""
	}
	rows, err := k.db.Query(fmt.Sprintf(`SELECT id, data, %s FROM %s WHERE %s >= ? %s ORDER BY %s, id`, column, lp.Trigger.Table, column, extra, column), mark)
	if err != nil {
		return err
	}
	type change struct {
		id, at string
		row    map[string]any
	}
	var changes []change
	for rows.Next() {
		var c change
		var data string
		if rows.Scan(&c.id, &data, &c.at) == nil {
			c.row = map[string]any{}
			if json.Unmarshal([]byte(data), &c.row) == nil {
				c.row["id"] = c.id
				changes = append(changes, c)
			}
		}
	}
	rows.Close()
	newMark := mark
	for _, c := range changes {
		identity := lp.Trigger.Mutation + ":" + c.id
		if lp.Trigger.Mutation == "update" {
			identity += "@" + c.at
		}
		if _, _, err := k.startRun(lp, "on_mutation", identity, c.row); err != nil {
			return err
		}
		if c.at > newMark {
			newMark = c.at
		}
	}
	if newMark != mark {
		_, err = k.db.Exec(`UPDATE loop_watermarks SET mark = ? WHERE loop = ?`, newMark, lp.Name)
	}
	return err
}

// ---------------------------------------------------------------- outside world

var (
	titleRe  = regexp.MustCompile(`(?is)<title[^>]*>(.*?)</title>`)
	scriptRe = regexp.MustCompile(`(?is)<(script|style|noscript)[^>]*>.*?</(script|style|noscript)>`)
	tagRe    = regexp.MustCompile(`(?s)<[^>]+>`)
	spaceRe  = regexp.MustCompile(`\s+`)
)

func (c *runCtx) callTool(st *Step, sc *scope) map[string]any {
	args := map[string]any{}
	if st.Args != nil {
		v, known := eval(st.Args, sc)
		m, isMap := v.(map[string]any)
		if !known || !isMap {
			return map[string]any{"error": "mcp::call :args is unknown"}
		}
		for k, fv := range m {
			if fv != nil {
				args[k] = fv
			}
		}
	}
	token := ""
	if st.AuthEnv != "" {
		token = os.Getenv(st.AuthEnv)
		if token == "" {
			return map[string]any{"error": st.AuthEnv + " is not set"}
		}
	}
	var lastErr error
	for attempt := 0; attempt <= st.Retry; attempt++ {
		res, err := c.k.mcp(st.Server, st.Tool, args, token)
		if err == nil {
			if st.Select != "" {
				res["data"] = selectPath(res["data"], st.Select)
			}
			if text, _ := res["text"].(string); len(text) > 65536 {
				res["text"] = text[:65536]
			}
			return map[string]any{"page": res}
		}
		lastErr = err
		if attempt < st.Retry {
			time.Sleep(time.Duration(200*(attempt+1)) * time.Millisecond)
		}
	}
	return map[string]any{"error": fmt.Sprintf("%s %s: %v", st.Server, st.Tool, lastErr)}
}

// selectPath walks a dotted path; a list maps the rest of the path over its items.
func selectPath(v any, path string) any {
	if path == "" {
		return v
	}
	seg, rest, _ := strings.Cut(path, ".")
	switch t := v.(type) {
	case map[string]any:
		return selectPath(t[seg], rest)
	case []any:
		out := make([]any, 0, len(t))
		for _, item := range t {
			out = append(out, selectPath(item, path))
		}
		return out
	}
	return nil
}

// mcpCall runs one MCP tool over streamable HTTP: initialize, initialized, tools/call.
func mcpCall(server, tool string, args map[string]any, token string) (map[string]any, error) {
	client := &http.Client{Timeout: 90 * time.Second}
	session := ""
	post := func(msg map[string]any) (map[string]any, error) {
		body, _ := json.Marshal(msg)
		req, err := http.NewRequest(http.MethodPost, server, bytes.NewReader(body))
		if err != nil {
			return nil, err
		}
		req.Header.Set("Content-Type", "application/json")
		req.Header.Set("Accept", "application/json, text/event-stream")
		req.Header.Set("User-Agent", "silc-loop/1")
		if token != "" {
			if strings.Contains(token, " ") {
				req.Header.Set("Authorization", token)
			} else {
				req.Header.Set("Authorization", "Bearer "+token)
			}
		}
		if session != "" {
			req.Header.Set("Mcp-Session-Id", session)
		}
		resp, err := client.Do(req)
		if err != nil {
			return nil, err
		}
		defer resp.Body.Close()
		if sid := resp.Header.Get("Mcp-Session-Id"); sid != "" {
			session = sid
		}
		data, err := io.ReadAll(io.LimitReader(resp.Body, 8<<20))
		if err != nil {
			return nil, err
		}
		if resp.StatusCode >= 400 {
			snippet := strings.TrimSpace(string(data))
			if len(snippet) > 300 {
				snippet = snippet[:300]
			}
			return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, snippet)
		}
		id, wantsReply := msg["id"]
		if !wantsReply {
			return nil, nil
		}
		var reply map[string]any
		if strings.HasPrefix(resp.Header.Get("Content-Type"), "text/event-stream") {
			for _, event := range strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n\n") {
				var payload []string
				for _, line := range strings.Split(event, "\n") {
					if strings.HasPrefix(line, "data:") {
						payload = append(payload, strings.TrimSpace(strings.TrimPrefix(line, "data:")))
					}
				}
				var m map[string]any
				if json.Unmarshal([]byte(strings.Join(payload, "\n")), &m) == nil && fmt.Sprint(m["id"]) == fmt.Sprint(id) {
					reply = m
					break
				}
			}
		} else if err := json.Unmarshal(data, &reply); err != nil {
			return nil, fmt.Errorf("reply is not JSON: %v", err)
		}
		if reply == nil {
			return nil, fmt.Errorf("no reply to %v", msg["method"])
		}
		if e, ok := reply["error"].(map[string]any); ok {
			return nil, fmt.Errorf("%v", e["message"])
		}
		result, _ := reply["result"].(map[string]any)
		return result, nil
	}
	if _, err := post(map[string]any{
		"jsonrpc": "2.0", "id": 1, "method": "initialize",
		"params": map[string]any{
			"protocolVersion": "2025-03-26",
			"capabilities":    map[string]any{},
			"clientInfo":      map[string]any{"name": "silc-loop", "version": "1"},
		},
	}); err != nil {
		return nil, fmt.Errorf("initialize: %w", err)
	}
	if _, err := post(map[string]any{"jsonrpc": "2.0", "method": "notifications/initialized"}); err != nil {
		return nil, fmt.Errorf("initialized: %w", err)
	}
	result, err := post(map[string]any{
		"jsonrpc": "2.0", "id": 2, "method": "tools/call",
		"params": map[string]any{"name": tool, "arguments": args},
	})
	if err != nil {
		return nil, err
	}
	var texts []string
	if content, ok := result["content"].([]any); ok {
		for _, part := range content {
			if p, ok := part.(map[string]any); ok && p["type"] == "text" {
				if t, ok := p["text"].(string); ok {
					texts = append(texts, t)
				}
			}
		}
	}
	text := strings.Join(texts, "\n")
	if isErr, _ := result["isError"].(bool); isErr {
		return nil, fmt.Errorf("tool error: %s", text)
	}
	data := result["structuredContent"]
	if data == nil {
		var parsed any
		if json.Unmarshal([]byte(text), &parsed) == nil {
			data = parsed
		} else {
			data = text
		}
	}
	return map[string]any{"text": text, "data": data}, nil
}

func fetchPage(url string) (Page, error) {
	client := &http.Client{Timeout: 20 * time.Second}
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return Page{}, err
	}
	req.Header.Set("User-Agent", "SilcLoop/0.1")
	resp, err := client.Do(req)
	if err != nil {
		return Page{}, err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 2<<20))
	if err != nil {
		return Page{}, err
	}
	if resp.StatusCode >= 400 {
		return Page{}, fmt.Errorf("GET %s returned %d", url, resp.StatusCode)
	}
	text := string(body)
	title := ""
	if m := titleRe.FindStringSubmatch(text); m != nil {
		title = strings.TrimSpace(html.UnescapeString(spaceRe.ReplaceAllString(m[1], " ")))
	}
	text = scriptRe.ReplaceAllString(text, " ")
	text = tagRe.ReplaceAllString(text, " ")
	text = strings.TrimSpace(spaceRe.ReplaceAllString(html.UnescapeString(text), " "))
	if len(text) > 8000 {
		text = text[:8000]
	}
	return Page{URL: url, Status: resp.StatusCode, Title: title, Text: text}, nil
}

type udsAsker struct {
	conn    net.Conn
	mu      sync.Mutex
	waiters map[string]chan map[string]any
	next    int
}

func encodeFrame(value any) ([]byte, error) {
	payload, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	buf := make([]byte, 6+len(payload))
	binary.LittleEndian.PutUint32(buf[0:4], uint32(len(payload)))
	binary.LittleEndian.PutUint16(buf[4:6], protocolVersion)
	copy(buf[6:], payload)
	return buf, nil
}

func readFrame(conn net.Conn) (map[string]any, error) {
	header := make([]byte, 6)
	if _, err := io.ReadFull(conn, header); err != nil {
		return nil, err
	}
	if binary.LittleEndian.Uint16(header[4:6]) != protocolVersion {
		return nil, fmt.Errorf("unsupported protocol")
	}
	payload := make([]byte, binary.LittleEndian.Uint32(header[0:4]))
	if _, err := io.ReadFull(conn, payload); err != nil {
		return nil, err
	}
	var out map[string]any
	return out, json.Unmarshal(payload, &out)
}

func dialSupervisor(path string) (*udsAsker, error) {
	var conn net.Conn
	var err error
	for i := 0; i < 50; i++ {
		if conn, err = net.Dial("unix", path); err == nil {
			break
		}
		time.Sleep(100 * time.Millisecond)
	}
	if conn == nil {
		return nil, err
	}
	a := &udsAsker{conn: conn, waiters: map[string]chan map[string]any{}}
	id := fmt.Sprintf("loop-%d", os.Getpid())
	if err := a.send(map[string]any{"type": "HELLO", "worker_id": id, "role": "loop", "abi_version": 1, "pid": os.Getpid()}); err != nil {
		return nil, err
	}
	if err := a.send(map[string]any{"type": "READY", "worker_id": id}); err != nil {
		return nil, err
	}
	go a.readLoop()
	return a, nil
}

func (a *udsAsker) send(v map[string]any) error {
	b, err := encodeFrame(v)
	if err != nil {
		return err
	}
	a.mu.Lock()
	defer a.mu.Unlock()
	_, err = a.conn.Write(b)
	return err
}

func (a *udsAsker) readLoop() {
	for {
		msg, err := readFrame(a.conn)
		if err != nil {
			fmt.Fprintln(os.Stderr, "silc loop: supervisor connection closed")
			os.Exit(0)
		}
		switch msg["type"] {
		case "SHUTDOWN":
			os.Exit(0)
		case "RESPONSE":
			id, _ := msg["request_id"].(string)
			a.mu.Lock()
			ch := a.waiters[id]
			delete(a.waiters, id)
			a.mu.Unlock()
			if ch != nil {
				ch <- msg
			}
		}
	}
}

func (a *udsAsker) Ask(req AskRequest) (string, error) {
	a.mu.Lock()
	a.next++
	id := fmt.Sprintf("ask-%d-%d", os.Getpid(), a.next)
	ch := make(chan map[string]any, 1)
	a.waiters[id] = ch
	a.mu.Unlock()
	if err := a.send(map[string]any{
		"type": "ASK", "request_id": id, "name": req.Loop,
		"prompt": req.Prompt, "context": req.Context, "schema": req.Schema,
	}); err != nil {
		return "", err
	}
	select {
	case msg := <-ch:
		if ok, _ := msg["ok"].(bool); !ok {
			errText, _ := msg["error"].(string)
			return "", fmt.Errorf("silclm: %s", errText)
		}
		reply, _ := msg["reply"].(string)
		return reply, nil
	case <-time.After(10 * time.Minute):
		a.mu.Lock()
		delete(a.waiters, id)
		a.mu.Unlock()
		return "", fmt.Errorf("silclm did not answer within 10 minutes")
	}
}

func contains(list []string, s string) bool {
	for _, v := range list {
		if v == s {
			return true
		}
	}
	return false
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func main() {
	planPath := envOr("SILC_LOOP_PLAN", "loop/plan.json")
	dbPath := envOr("SILC_DB_PATH", "data/app.db")
	plan, err := loadPlan(planPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "silc loop:", err)
		os.Exit(1)
	}
	if err := os.MkdirAll(filepath.Dir(dbPath), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "silc loop:", err)
		os.Exit(1)
	}
	db, err := sql.Open("sqlite", "file:"+dbPath+"?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)")
	if err != nil {
		fmt.Fprintln(os.Stderr, "silc loop:", err)
		os.Exit(1)
	}
	db.SetMaxOpenConns(1)
	k, err := NewKernel(db, plan, filepath.Join(filepath.Dir(planPath), "plans"))
	if err != nil {
		fmt.Fprintln(os.Stderr, "silc loop:", err)
		os.Exit(1)
	}
	if sock := os.Getenv("SILC_SOCKET"); sock != "" {
		asker, err := dialSupervisor(sock)
		if err != nil {
			k.logf("cannot reach supervisor (%v); loop::ask will fail", err)
		} else {
			k.asker = asker
		}
	}
	tick := 1000
	if v, err := strconv.Atoi(os.Getenv("SILC_LOOP_TICK_MS")); err == nil && v > 0 {
		tick = v
	}
	k.logf("kernel ready: %d loop(s), plan %s", len(plan.Loops), plan.Hash[:12])
	for {
		k.Tick()
		time.Sleep(time.Duration(tick) * time.Millisecond)
	}
}
