// AUTO-GENERATED BY silc __COMPILER_VERSION__ — DO NOT EDIT
import { connect, type Socket } from "node:net";

const socketPath = process.env.SILC_SOCKET || "__SOCKET_PATH__";
const protocolVersion = 1;
const abiVersion = 1;
const maxExtractedBytes = 40 * 1024;

function encodeFrame(value: unknown): Buffer {
  const payload = Buffer.from(JSON.stringify(value));
  const frame = Buffer.allocUnsafe(6 + payload.length);
  frame.writeUInt32LE(payload.length, 0);
  frame.writeUInt16LE(protocolVersion, 4);
  payload.copy(frame, 6);
  return frame;
}

function decodeFrame(buffer: Buffer): { frame: any; rest: Buffer } | null {
  if (buffer.length < 6) return null;
  const length = buffer.readUInt32LE(0);
  const version = buffer.readUInt16LE(4);
  if (version !== protocolVersion) throw new Error(`unsupported Silc protocol ${version}`);
  if (buffer.length < 6 + length) return null;
  return {
    frame: JSON.parse(buffer.subarray(6, 6 + length).toString()),
    rest: buffer.subarray(6 + length),
  };
}

function parseInput(): { url: string } {
  const raw = process.env.SILC_PIPELINE_INPUT_JSON;
  if (!raw) throw new Error("pipeline requires --input-json or --input");
  const value = JSON.parse(raw);
  if (!value || typeof value.url !== "string") {
    throw new Error('pipeline input must be a JSON object with string field "url"');
  }
  const url = new URL(value.url);
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    throw new Error("pipeline input url must use http or https");
  }
  return { url: url.toString() };
}

function decodeEntities(text: string): string {
  const named: Record<string, string> = {
    amp: "&",
    apos: "'",
    gt: ">",
    lt: "<",
    nbsp: " ",
    quot: '"',
  };
  return text.replace(/&(#x[0-9a-f]+|#[0-9]+|[a-z]+);/gi, (whole, entity: string) => {
    if (entity[0] !== "#") return named[entity.toLowerCase()] ?? whole;
    const hex = entity[1]?.toLowerCase() === "x";
    const value = Number.parseInt(entity.slice(hex ? 2 : 1), hex ? 16 : 10);
    return Number.isFinite(value) ? String.fromCodePoint(value) : whole;
  });
}

function extractText(html: string): string {
  const text = decodeEntities(
    html
      .replace(/<(script|style|noscript)\b[^>]*>[\s\S]*?<\/\1>/gi, " ")
      .replace(/<[^>]+>/g, " ")
      .replace(/\s+/g, " ")
      .trim(),
  );
  if (!text) throw new Error("scrape::extract produced no text");
  let bounded = text;
  while (Buffer.byteLength(bounded) > maxExtractedBytes) {
    bounded = bounded.slice(0, Math.floor(bounded.length * 0.9));
  }
  return bounded;
}

async function fetchExtract(url: string): Promise<string> {
  const response = await fetch(url, {
    headers: { "user-agent": "silc/0.3.0 pipeline" },
    redirect: "follow",
    signal: AbortSignal.timeout(30_000),
  });
  if (!response.ok) throw new Error(`scrape::page ${response.status} ${response.statusText}`);
  return extractText(await response.text());
}

function runIngest(socket: Socket, url: string, rawContent: string): Promise<any> {
  return new Promise((resolve, reject) => {
    const requestId = crypto.randomUUID();
    let pending = Buffer.alloc(0);
    const timeout = setTimeout(() => reject(new Error("pipeline timed out")), 180_000);
    socket.on("data", (chunk) => {
      pending = Buffer.concat([pending, chunk]);
      while (true) {
        const decoded = decodeFrame(pending);
        if (!decoded) break;
        pending = decoded.rest;
        const frame = decoded.frame;
        if (frame.type === "RESPONSE" && frame.request_id === requestId) {
          clearTimeout(timeout);
          if (!frame.ok) reject(new Error(frame.error || "pipeline failed"));
          else resolve(frame);
        }
      }
    });
    socket.write(
      encodeFrame({
        type: "INGEST",
        request_id: requestId,
        author: url,
        text: rawContent,
      }),
    );
  });
}

async function main() {
  const input = parseInput();
  const rawContent = await fetchExtract(input.url);
  const socket = connect(socketPath);
  await new Promise<void>((resolve, reject) => {
    socket.once("connect", resolve);
    socket.once("error", reject);
  });
  socket.write(
    encodeFrame({
      type: "HELLO",
      worker_id: `bun-pipeline-${process.pid}`,
      role: "bun",
      abi_version: abiVersion,
      pid: process.pid,
    }),
  );
  socket.write(encodeFrame({ type: "READY", worker_id: `bun-pipeline-${process.pid}` }));
  const result = await runIngest(socket, input.url, rawContent);
  console.log(JSON.stringify({ ...result, url: input.url, extracted_bytes: Buffer.byteLength(rawContent) }));
  socket.end();
}

main().catch((error) => {
  console.error(`silc pipeline: ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = 1;
});
