#!/usr/bin/env python3
# AUTO-GENERATED BY silc __COMPILER_VERSION__ — DO NOT EDIT
# ADR-006: python-playwright-v1 browser sidecar.
"""Render a URL with Playwright and print HTML (or JSON page) to stdout."""

from __future__ import annotations

import argparse
import json
import os
import sys


def looks_like_shell(html: str) -> bool:
    text = html or ""
    lower = text.lower()
    if len(text.strip()) < 80:
        return True
    if "<div id=\"root\"></div>" in lower or "<div id=\"app\"></div>" in lower:
        return True
    if "window.__NEXT_DATA__" in text and len(text) < 500:
        return True
    body = ""
    start = lower.find("<body")
    if start >= 0:
        end = lower.find("</body>", start)
        body = text[start:end] if end > start else text[start:]
    # Strip tags for a rough text density check.
    import re

    plain = re.sub(r"<[^>]+>", " ", body)
    plain = re.sub(r"\s+", " ", plain).strip()
    return len(plain) < 40


def render(url: str, wait_for: str | None, timeout_ms: int) -> tuple[str, str]:
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.goto(url, wait_until="networkidle", timeout=timeout_ms)
        if wait_for:
            page.wait_for_selector(wait_for, timeout=timeout_ms)
        html = page.content()
        title = page.title()
        browser.close()
    return html, title


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--url", default=os.environ.get("SILC_SCRAPE_URL", ""))
    parser.add_argument("--wait-for", default=os.environ.get("SILC_SCRAPE_WAIT_FOR", ""))
    parser.add_argument(
        "--timeout-ms",
        type=int,
        default=int(os.environ.get("SILC_SCRAPE_TIMEOUT_MS", "30000")),
    )
    parser.add_argument(
        "--check-shell",
        action="store_true",
        help="exit 2 if HTML looks like a JS shell (for :js(auto))",
    )
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    if not args.url:
        print("SILC_SCRAPE_URL / --url required", file=sys.stderr)
        return 1

    html, title = render(args.url, args.wait_for or None, args.timeout_ms)
    if args.check_shell and looks_like_shell(html):
        print(json.dumps({"shell": True, "url": args.url}))
        return 2
    if args.json:
        snippet = " ".join(html.split())
        if len(snippet) > 280:
            snippet = snippet[:280] + "…"
        print(
            json.dumps(
                {
                    "url": args.url,
                    "title": title,
                    "snippet": snippet,
                    "html": html,
                    "status": "ok",
                }
            )
        )
    else:
        print(html)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
