// AUTO-GENERATED BY silc 0.2.0 — DO NOT EDIT
package main

import (
	"database/sql"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"os"
	"path/filepath"
	"time"

	_ "modernc.org/sqlite"
)

const (
	protocolVersion = 1
	abiVersion      = 1
	schemaID        = __SCHEMA_ID__
)

type frame map[string]any

func encodeFrame(value any) ([]byte, error) {
	payload, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	buf := make([]byte, 6+len(payload))
	binary.LittleEndian.PutUint32(buf[0:4], uint32(len(payload)))
	binary.LittleEndian.PutUint16(buf[4:6], protocolVersion)
	copy(buf[6:], payload)
	return buf, nil
}

func readFrame(conn net.Conn) (frame, error) {
	header := make([]byte, 6)
	if _, err := io.ReadFull(conn, header); err != nil {
		return nil, err
	}
	if binary.LittleEndian.Uint16(header[4:6]) != protocolVersion {
		return nil, fmt.Errorf("unsupported protocol")
	}
	payload := make([]byte, binary.LittleEndian.Uint32(header[0:4]))
	if _, err := io.ReadFull(conn, payload); err != nil {
		return nil, err
	}
	var out frame
	return out, json.Unmarshal(payload, &out)
}

func readSlot(dir string, id int) (map[string]any, error) {
	path := filepath.Join(dir, fmt.Sprintf("slot_%04d.sbuf", id))
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if len(data) < 32 || string(data[0:4]) != "SILC" {
		return nil, fmt.Errorf("bad SILC magic")
	}
	if binary.LittleEndian.Uint16(data[4:6]) != abiVersion {
		return nil, fmt.Errorf("bad ABI")
	}
	if binary.LittleEndian.Uint32(data[8:12]) != schemaID {
		return nil, fmt.Errorf("schema_id mismatch")
	}
	offset := int(binary.LittleEndian.Uint32(data[20:24]))
	length := int(binary.LittleEndian.Uint32(data[28:32]))
	if offset < 0 || length < 0 || offset+length > len(data) {
		return nil, fmt.Errorf("payload out of bounds")
	}
	var record map[string]any
	err = json.Unmarshal(data[offset:offset+length], &record)
	return record, err
}

func main() {
	socketPath := envOr("SILC_SOCKET", "__SOCKET_PATH__")
	dbPath := envOr("SILC_DB_PATH", "__DB_PATH__")
	table := envOr("SILC_SQLITE_TABLE", "__TABLE__")
	ipcDir := envOr("SILC_IPC_DIR", "ipc")

	if err := os.MkdirAll(filepath.Dir(dbPath), 0o755); err != nil {
		fatal(err)
	}
	db, err := sql.Open("sqlite", dbPath)
	if err != nil {
		fatal(err)
	}
	defer db.Close()

	_, err = db.Exec(fmt.Sprintf(`
		CREATE TABLE IF NOT EXISTS %s (
			id TEXT PRIMARY KEY,
			payload TEXT NOT NULL,
			created_at TEXT NOT NULL DEFAULT (datetime('now'))
		);
		CREATE TABLE IF NOT EXISTS app_events (
			id TEXT PRIMARY KEY,
			kind TEXT NOT NULL,
			payload TEXT NOT NULL,
			created_at TEXT NOT NULL DEFAULT (datetime('now'))
		);
	`, table))
	if err != nil {
		fatal(err)
	}

	var conn net.Conn
	for i := 0; i < 50; i++ {
		conn, err = net.Dial("unix", socketPath)
		if err == nil {
			break
		}
		time.Sleep(100 * time.Millisecond)
	}
	if conn == nil {
		fatal(fmt.Errorf("cannot connect to %s", socketPath))
	}
	defer conn.Close()

	workerID := fmt.Sprintf("go-%d", os.Getpid())
	mustSend(conn, frame{"type": "HELLO", "worker_id": workerID, "role": "go", "abi_version": abiVersion, "pid": os.Getpid()})
	mustSend(conn, frame{"type": "READY", "worker_id": workerID})

	for {
		msg, err := readFrame(conn)
		if err != nil {
			return
		}
		if msg["type"] == "SHUTDOWN" {
			return
		}
		if msg["type"] != "NOTIFY" {
			continue
		}
		if stage, _ := msg["stage"].(string); stage != "go" {
			continue
		}
		requestID, _ := msg["request_id"].(string)
		segmentID := int(msg["segment_id"].(float64))
		seq := uint64(msg["seq"].(float64))
		record, runErr := readSlot(ipcDir, segmentID)
		if runErr == nil {
			runErr = persist(db, table, record)
		}
		if runErr != nil {
			mustSend(conn, frame{
				"type": "ERROR", "request_id": requestID,
				"code": "GO_SQLITE", "message": runErr.Error(),
			})
			continue
		}
		mustSend(conn, frame{
			"type": "ACK", "request_id": requestID, "worker_id": workerID,
			"segment_id": segmentID, "seq": seq, "result": record,
		})
	}
}

func persist(db *sql.DB, table string, record map[string]any) error {
	id, _ := record["id"].(string)
	if id == "" {
		id = fmt.Sprintf("%d", time.Now().UnixNano())
		record["id"] = id
	}
	payload, err := json.Marshal(record)
	if err != nil {
		return err
	}
	_, err = db.Exec(fmt.Sprintf(`INSERT OR REPLACE INTO %s (id, payload) VALUES (?, ?)`, table), id, string(payload))
	if err != nil {
		return err
	}
	kind := "event"
	if _, ok := record["prompt"]; ok {
		kind = "chat"
	}
	if _, ok := record["score"]; ok {
		kind = "score"
	}
	_, err = db.Exec(`INSERT OR REPLACE INTO app_events (id, kind, payload) VALUES (?, ?, ?)`, id, kind, string(payload))
	return err
}

func mustSend(conn net.Conn, value frame) {
	bytes, err := encodeFrame(value)
	if err != nil {
		fatal(err)
	}
	if _, err := conn.Write(bytes); err != nil {
		fatal(err)
	}
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
