// AUTO-GENERATED BY silc — OpenTUI terminal runtime. DO NOT EDIT
import {
  Box,
  Text,
  Input,
  Select,
  ScrollBox,
  TabSelect,
  TextTableRenderable,
  createCliRenderer,
  h as coreH,
  type CliRenderer,
  type VChild,
  type VNode,
} from "@opentui/core";
import { createTestRenderer } from "@opentui/core/testing";

export { Box, Text, Input, Select, ScrollBox, TabSelect, TextTableRenderable };
export type { VChild, VNode };

/** Host renderables from OpenTUI — never eagerly invoke these. */
const HOST = new Set<Function>([
  Box,
  Text,
  Input,
  Select,
  ScrollBox,
  TabSelect,
  TextTableRenderable,
]);

type EffectFn = () => void | (() => void);
type EffectRecord = { deps?: unknown[]; cleanup?: () => void };
type PendingEffect = { index: number; deps?: unknown[]; fn: EffectFn };
type HookState = {
  states: any[];
  index: number;
  effectIndex: number;
  effects: PendingEffect[];
  effectRecords: EffectRecord[];
};

let activeHooks: HookState | null = null;
let scheduled: (() => void) | null = null;

export function useState<T>(initial: T): [T, (value: T | ((prev: T) => T)) => void] {
  const hooks = activeHooks!;
  const i = hooks.index++;
  if (hooks.states.length <= i) hooks.states.push(initial);
  const set = (value: T | ((prev: T) => T)) => {
    const next = typeof value === "function" ? (value as (prev: T) => T)(hooks.states[i]) : value;
    if (Object.is(hooks.states[i], next)) return;
    hooks.states[i] = next;
    scheduled?.();
  };
  return [hooks.states[i] as T, set];
}

export function useEffect(fn: EffectFn, deps?: unknown[]) {
  const hooks = activeHooks!;
  const index = hooks.effectIndex++;
  const previous = hooks.effectRecords[index];
  const changed =
    deps === undefined ||
    previous === undefined ||
    previous.deps === undefined ||
    deps.length !== previous.deps.length ||
    deps.some((value, i) => !Object.is(value, previous.deps![i]));
  if (changed) hooks.effects.push({ index, deps, fn });
}

export function useRef<T>(initial: T): { current: T } {
  const hooks = activeHooks!;
  const i = hooks.index++;
  if (hooks.states.length <= i) hooks.states.push({ current: initial });
  return hooks.states[i] as { current: T };
}

function flatten(children: any[]): VChild[] {
  const out: VChild[] = [];
  for (const child of children) {
    if (child === null || child === undefined || child === false || child === true) continue;
    if (Array.isArray(child)) out.push(...flatten(child));
    else out.push(child);
  }
  return out;
}

/**
 * Classic JSX factory for TerminalApp.
 * Eagerly invokes author/catalog function components so silc hooks run during App(),
 * while leaving OpenTUI host constructors (Box/Text/…) as VNodes for the renderer.
 */
export function h(type: any, props: any = null, ...children: any[]): any {
  const p = props ?? {};
  const fromProps =
    p.children === undefined
      ? []
      : Array.isArray(p.children)
        ? p.children
        : [p.children];
  const kids = flatten(children.length ? children : fromProps);
  if (typeof type === "function" && !HOST.has(type)) {
    const { children: _ignored, ...rest } = p;
    return type(rest, ...kids);
  }
  return coreH(type, p, ...kids);
}

export function Fragment(_props: Record<string, unknown>, ...children: VChild[]): VNode {
  return coreH(Box, { flexDirection: "column", width: "100%" }, ...flatten(children));
}

type AppFn = () => VNode | VChild;

/** Relative `/api` and `/complete` URLs need an absolute origin outside the browser. */
function installFetchOriginProxy() {
  if ((globalThis as any).__silcFetchProxied) return;
  const origin =
    (typeof process !== "undefined" && process.env.SILC_WEB_ORIGIN) || "http://127.0.0.1";
  const original = globalThis.fetch.bind(globalThis);
  globalThis.fetch = ((input: any, init?: any) => {
    if (typeof input === "string" && input.startsWith("/")) {
      return original(`${origin}${input}`, init);
    }
    return original(input, init);
  }) as typeof fetch;
  (globalThis as any).__silcFetchProxied = true;
}

async function mount(renderer: CliRenderer, App: AppFn) {
  installFetchOriginProxy();
  const hooks: HookState = {
    states: [],
    index: 0,
    effectIndex: 0,
    effects: [],
    effectRecords: [],
  };
  let drawQueued = false;

  const draw = () => {
    while (renderer.root.getChildrenCount() > 0) {
      renderer.root.remove(renderer.root.getChildren()[0]!);
    }
    activeHooks = hooks;
    hooks.index = 0;
    hooks.effectIndex = 0;
    hooks.effects = [];
    const tree = App();
    activeHooks = null;
    if (tree) renderer.root.add(tree as any);
    for (const effect of hooks.effects) {
      try {
        hooks.effectRecords[effect.index]?.cleanup?.();
      } catch {
        /* ignore stale cleanup failures */
      }
      const cleanup = effect.fn();
      hooks.effectRecords[effect.index] = {
        deps: effect.deps,
        cleanup: typeof cleanup === "function" ? cleanup : undefined,
      };
    }
    renderer.requestRender();
  };

  scheduled = () => {
    if (drawQueued) return;
    drawQueued = true;
    queueMicrotask(() => {
      drawQueued = false;
      draw();
    });
  };
  draw();
  return { renderer, redraw: draw };
}

/** Local interactive OpenTUI surface (primary ui::terminal). */
export async function mountTerminalApp(App: AppFn) {
  const renderer = await createCliRenderer({
    exitOnCtrlC: true,
    useAlternateScreen: true,
  });
  return mount(renderer, App);
}

/** Headless smoke harness for compiler tests. */
export async function mountTerminalAppTest(App: AppFn, opts: { width?: number; height?: number } = {}) {
  const setup = await createTestRenderer({
    width: opts.width ?? 100,
    height: opts.height ?? 40,
    useAlternateScreen: false,
  });
  const mounted = await mount(setup.renderer, App);
  return {
    ...mounted,
    capture: () => setup.captureCharFrame(),
    destroy: () => setup.renderer.destroy(),
  };
}

export function __silcUnsupported(name: string): never {
  throw new Error(`silc: unsupported ui::${name} on terminal surface`);
}
