// AUTO-GENERATED BY silc — ShadCN-style Badge primitive. DO NOT EDIT
import * as React from "react";
import { cn } from "../../lib/utils";

type Tone = "default" | "muted" | "info" | "success" | "warning" | "danger";

const toneClass: Record<Tone, string> = {
  default: "border-border bg-muted text-foreground",
  muted: "border-border/60 bg-muted/50 text-muted-foreground",
  info: "border-primary/30 bg-primary/15 text-primary",
  success: "border-emerald-500/30 bg-emerald-500/15 text-emerald-400",
  warning: "border-amber-500/30 bg-amber-500/15 text-amber-400",
  danger: "border-destructive/30 bg-destructive/15 text-destructive",
};

export function Badge({
  text,
  tone = "default",
  className,
}: {
  text: string;
  tone?: Tone;
  className?: string;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-medium",
        toneClass[tone],
        className
      )}
    >
      {text}
    </span>
  );
}
