// AUTO-GENERATED BY silc — DO NOT EDIT
import { createRoot } from "react-dom/client";
import { App } from "./App";

const root = document.getElementById("app");
if (!root) {
  throw new Error("Silc ui::web mount point #app missing");
}
createRoot(root).render(<App />);
