// AUTO-GENERATED BY silc — ShadCN-style Empty primitive. DO NOT EDIT
import * as React from "react";
import { cn } from "../../lib/utils";

export function Empty({
  text = "No items",
  className,
}: {
  text?: string;
  className?: string;
}) {
  return <p className={cn("text-sm text-muted-foreground", className)}>{text}</p>;
}
