// AUTO-GENERATED BY silc — ShadCN-style ChatThread primitive. DO NOT EDIT
import * as React from "react";
import { cn } from "../../lib/utils";

export interface ChatMessage {
  prompt: string;
  reply: string;
  model?: string;
}

export function ChatThread({
  messages,
  thinking = false,
  className,
}: {
  messages: ChatMessage[];
  thinking?: boolean;
  className?: string;
}) {
  // Scroll only this container; scrollIntoView would also scroll the page.
  const scrollRef = React.useRef<HTMLDivElement | null>(null);
  React.useEffect(() => {
    const node = scrollRef.current;
    if (node) node.scrollTo({ top: node.scrollHeight, behavior: "smooth" });
  }, [messages.length, thinking]);

  return (
    <div
      ref={scrollRef}
      className={cn(
        "flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto rounded-xl border border-border bg-card/60 p-4",
        className
      )}
    >
      {messages.length === 0 && !thinking ? (
        <div className="grid flex-1 place-items-center">
          <p className="m-0 text-sm text-muted-foreground">
            Start the conversation — the model runs locally.
          </p>
        </div>
      ) : null}
      {messages.map((message, index) => (
        <div key={index} className="grid gap-3">
          <div className="justify-self-end">
            <div className="max-w-[85%] justify-self-end rounded-2xl rounded-br-sm bg-primary px-4 py-2.5 text-sm leading-6 text-primary-foreground">
              {message.prompt}
            </div>
          </div>
          <div className="justify-self-start">
            <div className="max-w-[85%] rounded-2xl rounded-bl-sm border border-border bg-background/70 px-4 py-2.5 text-sm leading-6">
              <p className="m-0 whitespace-pre-wrap">{message.reply}</p>
              {message.model ? (
                <p className="mb-0 mt-2 text-[11px] uppercase tracking-wider text-muted-foreground">
                  {message.model}
                </p>
              ) : null}
            </div>
          </div>
        </div>
      ))}
      {thinking ? (
        <div className="justify-self-start">
          <div className="inline-flex items-center gap-2 rounded-2xl rounded-bl-sm border border-border bg-background/70 px-4 py-2.5 text-sm text-muted-foreground">
            <span className="inline-block h-2 w-2 animate-pulse rounded-full bg-[var(--silc-accent)]" />
            Thinking…
          </div>
        </div>
      ) : null}
    </div>
  );
}
