// AUTO-GENERATED BY silc — ShadCN-style AppBar primitive. DO NOT EDIT
import * as React from "react";
import { cn } from "../../lib/utils";
import { ThoughtPivotLogo } from "./logo";

export function AppBar({
  title,
  className,
}: {
  title: string;
  className?: string;
}) {
  return (
    <header
      className={cn(
        "flex h-14 items-center border-b border-border bg-card/90 px-5 backdrop-blur",
        className
      )}
    >
      <ThoughtPivotLogo className="h-4 w-auto text-foreground" />
      <span className="mx-4 h-5 w-px bg-border" aria-hidden="true" />
      <h1 className="m-0 text-lg font-semibold tracking-tight">{title}</h1>
      <span className="ml-auto text-[10px] font-bold uppercase tracking-widest text-[var(--silc-accent)]">
        Silc
      </span>
    </header>
  );
}
