// AUTO-GENERATED BY silc — ShadCN-style Toolbar primitive. DO NOT EDIT
import * as React from "react";
import { cn } from "../../lib/utils";

export function Toolbar({
  className,
  children,
}: {
  className?: string;
  children?: React.ReactNode;
}) {
  return (
    <div className={cn("mt-1 flex flex-wrap items-center gap-3", className)}>
      {children}
    </div>
  );
}
