// AUTO-GENERATED BY silc — ShadCN-style Switch primitive. DO NOT EDIT
import * as React from "react";
import { cn } from "../../lib/utils";

export interface SwitchProps {
  id?: string;
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
  disabled?: boolean;
  className?: string;
}

export function Switch({
  id,
  label,
  checked,
  onChange,
  disabled = false,
  className,
}: SwitchProps) {
  const switchId = id || React.useId();

  return (
    <div className={cn("inline-flex items-center gap-3", className)}>
      <button
        id={switchId}
        type="button"
        role="switch"
        aria-checked={checked}
        aria-label={label}
        disabled={disabled}
        onClick={() => onChange(!checked)}
        className={cn(
          "relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border border-border transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/30 disabled:cursor-not-allowed disabled:opacity-50",
          checked ? "bg-primary" : "bg-muted"
        )}
      >
        <span
          aria-hidden
          className={cn(
            "pointer-events-none inline-block h-5 w-5 translate-y-0 rounded-full bg-background shadow-sm transition",
            checked ? "translate-x-5" : "translate-x-0.5"
          )}
        />
      </button>
      <label htmlFor={switchId} className="text-sm text-foreground">
        {label}
      </label>
    </div>
  );
}
