// AUTO-GENERATED BY silc — ShadCN-style Dialog primitive. DO NOT EDIT
import * as React from "react";
import { cn } from "../../lib/utils";
import { Button } from "./button";

export function Dialog({
  open,
  title,
  children,
  onConfirm,
  onCancel,
  className,
}: {
  open: boolean;
  title?: string;
  children?: React.ReactNode;
  onConfirm?: () => void;
  onCancel?: () => void;
  className?: string;
}) {
  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <button
        type="button"
        aria-label="Close dialog backdrop"
        className="absolute inset-0 bg-background/80 backdrop-blur-sm"
        onClick={onCancel}
      />
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby={title ? "silc-dialog-title" : undefined}
        className={cn(
          "relative z-10 w-full max-w-lg rounded-xl border border-border bg-card p-6 text-card-foreground shadow-xl",
          className
        )}
      >
        {title ? (
          <h2 id="silc-dialog-title" className="mb-4 text-lg font-semibold">
            {title}
          </h2>
        ) : null}
        <div className="mb-6">{children}</div>
        <div className="flex justify-end gap-2">
          <Button type="button" variant="secondary" onClick={onCancel}>
            Cancel
          </Button>
          <Button type="button" onClick={onConfirm}>
            Confirm
          </Button>
        </div>
      </div>
    </div>
  );
}
