// AUTO-GENERATED BY silc — ShadCN-style ChatComposer primitive. DO NOT EDIT
import * as React from "react";
import { cn } from "../../lib/utils";
import { Button } from "./button";
import { Label } from "./label";
import { Textarea } from "./textarea";

export function ChatComposer({
  id,
  label,
  placeholder,
  value,
  onChange,
  onSubmit,
  submitting = false,
  className,
}: {
  id: string;
  label?: string;
  placeholder?: string;
  value: string;
  onChange: (value: string) => void;
  onSubmit: (event: React.FormEvent<HTMLFormElement>) => void;
  submitting?: boolean;
  className?: string;
}) {
  const formRef = React.useRef<HTMLFormElement | null>(null);

  function onKeyDown(event: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (event.key === "Enter" && !event.shiftKey) {
      event.preventDefault();
      formRef.current?.requestSubmit();
    }
  }

  return (
    <form ref={formRef} className={cn("grid gap-2", className)} onSubmit={onSubmit}>
      {label ? <Label htmlFor={id}>{label}</Label> : null}
      <div className="flex items-end gap-3">
        <Textarea
          id={id}
          value={value}
          onChange={(event) => onChange(event.target.value)}
          onKeyDown={onKeyDown}
          placeholder={placeholder}
          rows={3}
          maxLength={16384}
          required
          className="flex-1"
        />
        <Button type="submit" disabled={submitting || value.trim().length === 0}>
          {submitting ? "Sending…" : "Send"}
        </Button>
      </div>
      <p className="m-0 text-xs text-muted-foreground">
        Enter to send · Shift+Enter for a new line
      </p>
    </form>
  );
}
