// AUTO-GENERATED BY silc — ShadCN-style Select primitive. DO NOT EDIT
import * as React from "react";
import { cn } from "../../lib/utils";
import { Label } from "./label";

export interface SelectProps {
  id?: string;
  label?: string;
  value: string;
  options: string[];
  onChange: (value: string) => void;
  disabled?: boolean;
  placeholder?: string;
  className?: string;
}

export function Select({
  id,
  label,
  value,
  options,
  onChange,
  disabled = false,
  placeholder,
  className,
}: SelectProps) {
  const selectId = id || React.useId();

  return (
    <div className={cn("grid gap-2", className)}>
      {label ? <Label htmlFor={selectId}>{label}</Label> : null}
      <select
        id={selectId}
        value={value}
        disabled={disabled}
        onChange={(event) => onChange(event.target.value)}
        className={cn(
          "flex h-11 w-full rounded-lg border border-input bg-background/75 px-3 py-2 text-sm text-foreground shadow-sm outline-none transition focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/30 disabled:cursor-not-allowed disabled:opacity-50"
        )}
      >
        {placeholder ? (
          <option value="" disabled>
            {placeholder}
          </option>
        ) : null}
        {options.map((option) => (
          <option key={option} value={option}>
            {option}
          </option>
        ))}
      </select>
    </div>
  );
}
