// AUTO-GENERATED BY silc — DO NOT EDIT
import { defineComponent, reactive, ref } from "vue";

export default defineComponent({
  name: "SilcUiWebForm",
  setup() {
    const form = reactive({
      author: "",
      text: "",
    });
    const status = ref("");
    const statusKind = ref("");
    const result = ref("");
    const submitting = ref(false);

    async function onSubmit() {
      submitting.value = true;
      status.value = "Submitting…";
      statusKind.value = "";
      result.value = "";
      try {
        const response = await fetch("/submit", {
          method: "POST",
          headers: { "content-type": "application/json" },
          body: JSON.stringify({
            author: form.author,
            text: form.text,
          }),
        });
        const body = await response.json();
        result.value = JSON.stringify(body, null, 2);
        if (response.ok && body.ok) {
          status.value = "Saved through Bun → Python → Go/SQLite";
          statusKind.value = "is-ok";
        } else {
          status.value = body.error || "Request failed";
          statusKind.value = "is-error";
        }
      } catch (error) {
        status.value = String(error);
        statusKind.value = "is-error";
      } finally {
        submitting.value = false;
      }
    }

    return { form, status, statusKind, result, submitting, onSubmit };
  },
  template: `
    <div class="silc-shell">
      <p class="silc-eyebrow">Silc ui::web · Vue substrate</p>
      <h1>Silc Feedback Portal</h1>
      <p class="silc-lede">
        Declarative Silc UI. Compiler-owned Vue on Bun — authors never write HTML or CSS.
      </p>
      <form class="silc-form" @submit.prevent="onSubmit">
        <div class="silc-field">
          <label for="author">Author</label>
          <input id="author" v-model.trim="form.author" required maxlength="120" autocomplete="nickname" />
        </div>
        <div class="silc-field">
          <label for="text">Feedback</label>
          <textarea id="text" v-model.trim="form.text" required maxlength="8192" rows="8"></textarea>
        </div>
        <div class="silc-actions">
          <button type="submit" :disabled="submitting">{{ submitting ? "Submitting…" : "Submit" }}</button>
          <span class="silc-status" :class="statusKind">{{ status }}</span>
        </div>
      </form>
      <pre v-if="result" class="silc-result">{{ result }}</pre>
    </div>
  `,
});
