// AUTO-GENERATED BY silc — ShadCN-style NavItem primitive. DO NOT EDIT
import * as React from "react";
import { cn } from "../../lib/utils";

export function NavItem({
  label,
  active = false,
  className,
}: {
  label: string;
  active?: boolean;
  className?: string;
}) {
  return (
    <div
      role="link"
      aria-current={active ? "page" : undefined}
      className={cn(
        "rounded-lg px-3 py-2 text-sm font-medium transition",
        active
          ? "bg-primary/20 text-foreground"
          : "text-muted-foreground hover:bg-background/60 hover:text-foreground",
        className
      )}
    >
      {label}
    </div>
  );
}
