// AUTO-GENERATED BY silc — DO NOT EDIT
/** Entity tree world (Godot-style hierarchy + Unity component bags). */

export type EntityId = number;

export type Transform = {
  x: number;
  y: number;
  z: number;
  yaw: number;
};

export class World {
  private nextId = 1;
  private readonly parents = new Map<EntityId, EntityId | null>();
  private readonly children = new Map<EntityId, EntityId[]>();
  private readonly names = new Map<EntityId, string>();
  private readonly nameIndex = new Map<string, EntityId>();
  private readonly transforms = new Map<EntityId, Transform>();
  private readonly componentStores = new Map<string, Map<EntityId, unknown>>();
  private readonly alive = new Set<EntityId>();

  create(name?: string, parent: EntityId | null = null): EntityId {
    const id = this.nextId++;
    this.alive.add(id);
    this.parents.set(id, parent);
    this.children.set(id, []);
    this.transforms.set(id, { x: 0, y: 0, z: 0, yaw: 0 });
    if (parent != null) {
      this.children.get(parent)!.push(id);
    }
    if (name) {
      this.names.set(id, name);
      this.nameIndex.set(name, id);
    }
    return id;
  }

  destroy(id: EntityId): void {
    if (!this.alive.has(id)) return;
    for (const child of [...(this.children.get(id) ?? [])]) {
      this.destroy(child);
    }
    const parent = this.parents.get(id);
    if (parent != null) {
      const list = this.children.get(parent);
      if (list) {
        const idx = list.indexOf(id);
        if (idx >= 0) list.splice(idx, 1);
      }
    }
    const name = this.names.get(id);
    if (name) this.nameIndex.delete(name);
    for (const store of this.componentStores.values()) {
      store.delete(id);
    }
    this.alive.delete(id);
    this.parents.delete(id);
    this.children.delete(id);
    this.names.delete(id);
    this.transforms.delete(id);
  }

  setName(id: EntityId, name: string): void {
    const prev = this.names.get(id);
    if (prev) this.nameIndex.delete(prev);
    this.names.set(id, name);
    this.nameIndex.set(name, id);
  }

  findByName(name: string): EntityId | null {
    return this.nameIndex.get(name) ?? null;
  }

  nameOf(id: EntityId): string | null {
    return this.names.get(id) ?? null;
  }

  parentOf(id: EntityId): EntityId | null {
    return this.parents.get(id) ?? null;
  }

  childrenOf(id: EntityId): EntityId[] {
    return [...(this.children.get(id) ?? [])];
  }

  transform(id: EntityId): Transform {
    return this.transforms.get(id)!;
  }

  setTransform(id: EntityId, t: Partial<Transform>): void {
    const cur = this.transforms.get(id)!;
    Object.assign(cur, t);
  }

  worldPosition(id: EntityId): { x: number; y: number; z: number } {
    let x = 0;
    let y = 0;
    let z = 0;
    let cur: EntityId | null = id;
    while (cur != null) {
      const t = this.transforms.get(cur)!;
      x += t.x;
      y += t.y;
      z += t.z;
      cur = this.parents.get(cur) ?? null;
    }
    return { x, y, z };
  }

  addComponent<T>(type: string, id: EntityId, value: T): void {
    let store = this.componentStores.get(type);
    if (!store) {
      store = new Map();
      this.componentStores.set(type, store);
    }
    store.set(id, value);
  }

  getComponent<T>(type: string, id: EntityId): T | null {
    return (this.componentStores.get(type)?.get(id) as T | undefined) ?? null;
  }

  hasComponent(type: string, id: EntityId): boolean {
    return this.componentStores.get(type)?.has(id) ?? false;
  }

  query(type: string): Array<[EntityId, unknown]> {
    const store = this.componentStores.get(type);
    if (!store) return [];
    return [...store.entries()];
  }

  entities(): EntityId[] {
    return [...this.alive];
  }
}
