//! Inspectable first-pass stub code generation for Go, Python, and Bun.

use sil_core::{Module, Program, Target};
use sil_router::RouteDecision;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct EmitResult {
    pub root: PathBuf,
    pub manifest: PathBuf,
    pub generated: Vec<PathBuf>,
}

pub fn emit(
    program: &Program,
    decisions: &[RouteDecision],
    source_path: &Path,
    runtime_root: &Path,
    compiler_version: &str,
) -> Result<EmitResult, String> {
    fs::create_dir_all(runtime_root)
        .map_err(|error| format!("create {}: {error}", runtime_root.display()))?;
    for target in ["go", "python", "typescript"] {
        fs::create_dir_all(runtime_root.join(target))
            .map_err(|error| format!("create target directory: {error}"))?;
    }

    let mut generated = Vec::new();
    let mut modules_json = Vec::new();
    for module in &program.modules {
        let decision = decisions
            .iter()
            .find(|decision| decision.module == module.name)
            .ok_or_else(|| format!("missing route decision for {}", module.name))?;
        let file_name = format!(
            "{}.{}",
            snake_case(&module.name),
            extension(decision.target)
        );
        let path = runtime_root
            .join(decision.target.runtime_dir())
            .join(file_name);
        fs::write(&path, render_stub(module, decision))
            .map_err(|error| format!("write {}: {error}", path.display()))?;
        generated.push(path.clone());
        modules_json.push(serde_json::json!({
            "name": module.name,
            "kind": module.kind.as_str(),
            "target": decision.target.as_str(),
            "provenance": decision.provenance,
            "generated": path.strip_prefix(runtime_root).unwrap_or(&path),
            "methods": module.methods.iter().map(|m| &m.name).collect::<Vec<_>>(),
        }));
    }

    let manifest_path = runtime_root.join("manifest.json");
    let manifest = serde_json::json!({
        "language": "Silc",
        "compiler": "silc",
        "compiler_version": compiler_version,
        "source": source_path,
        "source_version": program.version,
        "modules": modules_json,
    });
    fs::write(
        &manifest_path,
        serde_json::to_string_pretty(&manifest).map_err(|e| e.to_string())?,
    )
    .map_err(|error| format!("write {}: {error}", manifest_path.display()))?;

    Ok(EmitResult {
        root: runtime_root.to_path_buf(),
        manifest: manifest_path,
        generated,
    })
}

fn render_stub(module: &Module, decision: &RouteDecision) -> String {
    let methods = module
        .methods
        .iter()
        .map(|method| method.name.as_str())
        .collect::<Vec<_>>();
    match decision.target {
        Target::Bun => {
            let bodies = methods
                .iter()
                .map(|name| {
                    format!(
                        "  async {name}(): Promise<void> {{\n    // TODO: generated pipeline\n  }}"
                    )
                })
                .collect::<Vec<_>>()
                .join("\n\n");
            format!(
                "// AUTO-GENERATED BY silc — DO NOT EDIT\n// {}\nexport class {} {{\n{}\n}}\n",
                decision.provenance, module.name, bodies
            )
        }
        Target::Python => {
            let bodies = methods
                .iter()
                .map(|name| {
                    format!(
                        "    def {name}(self):\n        # TODO: generated pipeline\n        pass"
                    )
                })
                .collect::<Vec<_>>()
                .join("\n\n");
            format!(
                "# AUTO-GENERATED BY silc — DO NOT EDIT\n# {}\nclass {}:\n{}\n",
                decision.provenance, module.name, bodies
            )
        }
        Target::Go => {
            let bodies = methods
                .iter()
                .map(|name| {
                    format!(
                        "func (m *{}) {}() {{\n\t// TODO: generated pipeline\n}}",
                        module.name,
                        pascal_case(name)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n\n");
            format!(
                "// AUTO-GENERATED BY silc — DO NOT EDIT\n// {}\npackage generated\n\ntype {} struct {{}}\n\n{}\n",
                decision.provenance, module.name, bodies
            )
        }
    }
}

fn extension(target: Target) -> &'static str {
    match target {
        Target::Go => "go",
        Target::Python => "py",
        Target::Bun => "ts",
    }
}

fn snake_case(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch.is_uppercase() && index > 0 {
            out.push('_');
        }
        out.extend(ch.to_lowercase());
    }
    out
}

fn pascal_case(name: &str) -> String {
    name.split('_')
        .map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|first| first.to_uppercase().collect::<String>() + chars.as_str())
                .unwrap_or_default()
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn parse_route_emit_all_examples() {
        let examples = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../examples");
        for name in [
            "article_pipeline.silc",
            "sensor_alert.silc",
            "csv_summary.raku",
            "url_health.silc",
            "log_anomaly.raku",
        ] {
            let source_path = examples.join(name);
            let source = fs::read_to_string(&source_path).expect("read example");
            let program = sil_parser::parse(&source).expect("parse example");
            program.validate().expect("validate example");
            let decisions = sil_router::route_program(&program);
            assert_eq!(decisions.len(), 3);
            assert!(decisions.iter().any(|d| d.target == Target::Bun));
            assert!(decisions.iter().any(|d| d.target == Target::Python));
            assert!(decisions.iter().any(|d| d.target == Target::Go));

            let nonce = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos();
            let output = std::env::temp_dir().join(format!("silc-{nonce}"));
            let result =
                emit(&program, &decisions, &source_path, &output, "test").expect("emit example");
            assert!(result.manifest.exists());
            assert_eq!(result.generated.len(), 3);
            let manifest = fs::read_to_string(&result.manifest).unwrap();
            assert!(manifest.contains("\"target\": \"bun\""));
            assert!(manifest.contains("\"target\": \"python\""));
            assert!(manifest.contains("\"target\": \"go\""));
            fs::remove_dir_all(output).ok();
        }
    }
}
