//! Lower Silc components to dual-surface adapters (React web + terminal).

use sil_core::{
    App, BinOp, Component, ExecutableGraph, Expr, Program, UiNode, UiTemplate, UnaryOp,
};

pub fn render_web_app(program: &Program, graph: &ExecutableGraph) -> String {
    let app = graph.app.as_ref().expect("UI graph requires app");
    let mut out = String::new();
    out.push_str("/* AUTO-GENERATED BY silc 0.2.0 — DO NOT EDIT */\n");
    out.push_str("import React, { useEffect, useRef, useState } from \"react\";\n");
    out.push_str("import { AppBar } from \"./components/ui/app-bar\";\n");
    out.push_str("import { SidePanel } from \"./components/ui/side-panel\";\n");
    out.push_str("import { NavItem } from \"./components/ui/nav-item\";\n");
    out.push_str("import { Button } from \"./components/ui/button\";\n");
    out.push_str("import { Input } from \"./components/ui/input\";\n");
    out.push_str("import { Textarea } from \"./components/ui/textarea\";\n");
    out.push_str("import { Label } from \"./components/ui/label\";\n");
    out.push_str("import { Card } from \"./components/ui/card\";\n");
    out.push_str("import { RadioGroup } from \"./components/ui/radio-group\";\n");
    out.push_str("import { Toolbar } from \"./components/ui/toolbar\";\n");
    out.push_str("import { ChatThread } from \"./components/ui/chat-thread\";\n");
    out.push_str("import { ChatComposer } from \"./components/ui/chat-composer\";\n");
    out.push_str("import { HistoryPanel } from \"./components/ui/history-panel\";\n");
    out.push_str("import { SearchInput } from \"./components/ui/search-input\";\n");
    out.push_str("\n");

    for component in program.all_components() {
        out.push_str(&render_web_component(component, program));
        out.push('\n');
    }

    out.push_str(&render_router(app));
    out
}

fn render_router(app: &App) -> String {
    let mut cases = String::new();
    for route in &app.routes {
        cases.push_str(&format!(
            "    if (path === {path}) return <{comp} />;\n",
            path = escape_js_string(&route.path),
            comp = route.component
        ));
    }
    let default_comp = app
        .default_route()
        .map(|r| r.component.as_str())
        .unwrap_or("null");
    format!(
        r#"
function usePath() {{
  const [path, setPath] = useState(window.location.pathname || "/");
  useEffect(() => {{
    const onPop = () => setPath(window.location.pathname || "/");
    window.addEventListener("popstate", onPop);
    return () => window.removeEventListener("popstate", onPop);
  }}, []);
  return [path, (next) => {{ window.history.pushState({{}}, "", next); setPath(next); }}];
}}

export function App() {{
  const [path] = usePath();
{cases}  return <{default_comp} />;
}}
"#,
        cases = cases,
        default_comp = default_comp
    )
}

fn render_web_component(component: &Component, program: &Program) -> String {
    let chat_field = find_chat_field(&component.render);
    let has_chat_ui =
        chat_field.is_some() || template_has_component(&component.render, "chat_history");
    let session_field = find_chat_session_field(&component.render).or_else(|| {
        component
            .state
            .iter()
            .find(|f| {
                matches!(
                    f.name.as_str(),
                    "active_session" | "session_id" | "current_session" | "selected_session"
                )
            })
            .map(|f| f.name.clone())
    });

    let mut state_decls = String::new();
    for field in &component.state {
        let init = field
            .default
            .as_ref()
            .map(expr_to_js)
            .unwrap_or_else(|| "\"\"".into());
        state_decls.push_str(&format!(
            "  const [{name}, set{pascal}] = useState({init});\n",
            name = field.name,
            pascal = pascal(&field.name),
            init = init
        ));
    }
    for prop in &component.props {
        state_decls.push_str(&format!(
            "  const {name} = props.{name};\n",
            name = prop.name
        ));
    }
    for query in &component.queries {
        let table = program
            .resources
            .iter()
            .find(|r| r.name == query.resource)
            .map(|r| r.table_name())
            .unwrap_or_else(|| query.resource.to_ascii_lowercase());
        state_decls.push_str(&format!(
            r#"  const [{name}, set{pascal}] = useState([]);
  useEffect(() => {{
    fetch("/api/{table}").then(r => r.json()).then(set{pascal}).catch(console.error);
  }}, []);
"#,
            name = query.name,
            pascal = pascal(&query.name),
            table = table
        ));
    }

    if has_chat_ui {
        let prompt_field = chat_field.as_deref().unwrap_or("prompt");
        if let Some(session) = session_field.as_deref() {
            state_decls.push_str(&format!(
                r#"  const [messages, setMessages] = useState([]);
  const [thinking, setThinking] = useState(false);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [historyError, setHistoryError] = useState("");
  const [chatError, setChatError] = useState("");
  const activeSessionRef = useRef({session});
  const historyRequestRef = useRef(0);
  const inFlightSessionsRef = useRef(new Set());
  useEffect(() => {{
    activeSessionRef.current = {session};
    const requestId = ++historyRequestRef.current;
    const controller = new AbortController();
    setMessages([]);
    setHistoryError("");
    setChatError("");
    setThinking(inFlightSessionsRef.current.has({session}));
    if (!{session}) {{
      setHistoryLoading(false);
      return () => controller.abort();
    }}
    setHistoryLoading(true);
    fetch(`/history?session_id=${{encodeURIComponent({session})}}`, {{
      signal: controller.signal,
    }})
      .then((r) => {{
        if (!r.ok) throw new Error(`history request failed (${{r.status}})`);
        return r.json();
      }})
      .then((rows) => {{
        if (historyRequestRef.current !== requestId || activeSessionRef.current !== {session}) return;
        setMessages(Array.isArray(rows) ? [...rows].reverse() : []);
      }})
      .catch((error) => {{
        if (error?.name === "AbortError") return;
        if (historyRequestRef.current === requestId && activeSessionRef.current === {session}) {{
          setHistoryError(error instanceof Error ? error.message : String(error));
        }}
      }})
      .finally(() => {{
        if (historyRequestRef.current === requestId && activeSessionRef.current === {session}) {{
          setHistoryLoading(false);
        }}
      }});
    return () => controller.abort();
  }}, [{session}]);
"#,
                session = session
            ));
            state_decls.push_str(&format!(
                r#"  async function __chatComplete(promptText) {{
    const prompt = (promptText ?? {field} ?? "").toString().trim();
    if (!prompt) return;
    const capturedSession = {session};
    if (!capturedSession || inFlightSessionsRef.current.has(capturedSession)) return;
    const pendingId = crypto.randomUUID();
    inFlightSessionsRef.current.add(capturedSession);
    setChatError("");
    setThinking(true);
    setMessages((prev) => [
      ...prev,
      {{ id: pendingId, prompt, reply: "", pending: true, session_id: capturedSession }},
    ]);
    set{pascal}("");
    try {{
      const resp = await fetch("/complete", {{
        method: "POST",
        headers: {{ "content-type": "application/json" }},
        body: JSON.stringify({{ prompt, session_id: capturedSession }}),
      }});
      const data = await resp.json();
      if (!resp.ok || data.ok === false) {{
        throw new Error(data.error || "complete failed");
      }}
      if (activeSessionRef.current === capturedSession) {{
        const completed = {{
          id: data.id || pendingId,
          prompt,
          reply: data.reply || data.summary || "",
          model: data.model || undefined,
          session_id: capturedSession,
        }};
        setMessages((prev) =>
          prev.some((message) => message.id === pendingId)
            ? prev.map((message) => message.id === pendingId ? completed : message)
            : [...prev, completed]
        );
      }}
    }} catch (error) {{
      if (activeSessionRef.current === capturedSession) {{
        setMessages((prev) => prev.filter((message) => message.id !== pendingId));
        set{pascal}((draft) => draft || prompt);
        setChatError(error instanceof Error ? error.message : String(error));
      }}
    }} finally {{
      inFlightSessionsRef.current.delete(capturedSession);
      if (activeSessionRef.current === capturedSession) setThinking(false);
    }}
  }}
"#,
                field = prompt_field,
                pascal = pascal(prompt_field),
                session = session
            ));
        } else {
            state_decls.push_str(
                r#"  const [messages, setMessages] = useState([]);
  const [thinking, setThinking] = useState(false);
  const [historyLoading, setHistoryLoading] = useState(true);
  const [historyError, setHistoryError] = useState("");
  const [chatError, setChatError] = useState("");
  useEffect(() => {
    const controller = new AbortController();
    fetch("/history", { signal: controller.signal })
      .then((r) => {
        if (!r.ok) throw new Error(`history request failed (${r.status})`);
        return r.json();
      })
      .then((rows) => setMessages(Array.isArray(rows) ? [...rows].reverse() : []))
      .catch((error) => {
        if (error?.name !== "AbortError") {
          setHistoryError(error instanceof Error ? error.message : String(error));
        }
      })
      .finally(() => setHistoryLoading(false));
    return () => controller.abort();
  }, []);
"#,
            );
            state_decls.push_str(&format!(
                r#"  async function __chatComplete(promptText) {{
    const prompt = (promptText ?? {field} ?? "").toString().trim();
    if (!prompt || thinking) return;
    const pendingId = crypto.randomUUID();
    setChatError("");
    setThinking(true);
    setMessages((prev) => [
      ...prev,
      {{ id: pendingId, prompt, reply: "", pending: true }},
    ]);
    set{pascal}("");
    try {{
      const resp = await fetch("/complete", {{
        method: "POST",
        headers: {{ "content-type": "application/json" }},
        body: JSON.stringify({{ prompt }}),
      }});
      const data = await resp.json();
      if (!resp.ok || data.ok === false) {{
        throw new Error(data.error || "complete failed");
      }}
      const completed = {{
        id: data.id || pendingId,
        prompt,
        reply: data.reply || data.summary || "",
        model: data.model || undefined,
      }};
      setMessages((prev) =>
        prev.map((message) => message.id === pendingId ? completed : message)
      );
    }} catch (error) {{
      setMessages((prev) => prev.filter((message) => message.id !== pendingId));
      set{pascal}((draft) => draft || prompt);
      setChatError(error instanceof Error ? error.message : String(error));
    }} finally {{
      setThinking(false);
    }}
  }}
"#,
                field = prompt_field,
                pascal = pascal(prompt_field)
            ));
        }
    }

    let mut handlers = String::new();
    for handler in &component.handlers {
        let body = handler
            .body
            .iter()
            .map(|e| format!("    {};", expr_to_js_stmt(e, component)))
            .collect::<Vec<_>>()
            .join("\n");
        let params = handler
            .params
            .iter()
            .map(|p| p.name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        handlers.push_str(&format!(
            "  async function {name}({params}) {{\n{body}\n  }}\n",
            name = handler.name,
            params = params,
            body = body
        ));
    }

    let body = render_template(&component.render, 2);
    let body = if let Some(session) = session_field.as_deref() {
        body.replace(
            "submitting={thinking} />",
            &format!("submitting={{thinking}} focusKey={{{session}}} />"),
        )
    } else {
        body
    };
    format!(
        "function {name}(props = {{}}) {{\n{state}{handlers}  return (\n{body}\n  );\n}}\n",
        name = component.name,
        state = state_decls,
        handlers = handlers,
        body = body
    )
}

fn template_has_component(template: &UiTemplate, name: &str) -> bool {
    match template {
        UiTemplate::Node(node) => {
            node.component == name
                || node
                    .children
                    .iter()
                    .any(|c| template_has_component(c, name))
        }
        UiTemplate::When {
            body, else_body, ..
        } => {
            template_has_component(body, name)
                || else_body
                    .as_ref()
                    .map(|b| template_has_component(b, name))
                    .unwrap_or(false)
        }
        UiTemplate::For { body, .. } => template_has_component(body, name),
        UiTemplate::Block(items) => items.iter().any(|i| template_has_component(i, name)),
    }
}

fn find_chat_field(template: &UiTemplate) -> Option<String> {
    match template {
        UiTemplate::Node(node) => {
            if node.component == "chat" {
                return node
                    .prop("field")
                    .and_then(|e| e.as_ident())
                    .map(|s| s.to_string())
                    .or_else(|| {
                        node.prop("value")
                            .and_then(|e| e.as_ident())
                            .map(|s| s.to_string())
                    })
                    .or_else(|| Some("prompt".into()));
            }
            for child in &node.children {
                if let Some(field) = find_chat_field(child) {
                    return Some(field);
                }
            }
            None
        }
        UiTemplate::When {
            body, else_body, ..
        } => find_chat_field(body).or_else(|| else_body.as_ref().and_then(|b| find_chat_field(b))),
        UiTemplate::For { body, .. } => find_chat_field(body),
        UiTemplate::Block(items) => items.iter().find_map(find_chat_field),
    }
}

fn find_chat_session_field(template: &UiTemplate) -> Option<String> {
    match template {
        UiTemplate::Node(node) => {
            if node.component == "chat" {
                if let Some(session) = node.prop("session").and_then(|e| e.as_ident()) {
                    return Some(session.to_string());
                }
            }
            node.children.iter().find_map(find_chat_session_field)
        }
        UiTemplate::When {
            body, else_body, ..
        } => find_chat_session_field(body)
            .or_else(|| else_body.as_ref().and_then(|b| find_chat_session_field(b))),
        UiTemplate::For { body, .. } => find_chat_session_field(body),
        UiTemplate::Block(items) => items.iter().find_map(find_chat_session_field),
    }
}

fn render_template(template: &UiTemplate, indent: usize) -> String {
    let pad = " ".repeat(indent);
    match template {
        UiTemplate::Node(node) => render_node(node, indent),
        UiTemplate::When {
            condition,
            body,
            else_body,
        } => {
            let mut s = format!(
                "{pad}{{({cond}) ? (\n{then}\n{pad}) : (\n{else_}\n{pad})}}",
                pad = pad,
                cond = expr_to_js(condition),
                then = render_template(body, indent + 2),
                else_ = else_body
                    .as_ref()
                    .map(|b| render_template(b, indent + 2))
                    .unwrap_or_else(|| format!("{pad}  null"))
            );
            let _ = &mut s;
            s
        }
        UiTemplate::For {
            items,
            item_name,
            body,
        } => format!(
            "{pad}{{({items}).map(({item}) => (\n{body}\n{pad}))}}",
            pad = pad,
            items = expr_to_js(items),
            item = item_name,
            body = render_template(body, indent + 2)
        ),
        UiTemplate::Block(items) => {
            if items.is_empty() {
                format!("{pad}<></>")
            } else if items.len() == 1 {
                render_template(&items[0], indent)
            } else {
                let inner = items
                    .iter()
                    .map(|i| render_template(i, indent + 2))
                    .collect::<Vec<_>>()
                    .join("\n");
                format!("{pad}<>\n{inner}\n{pad}</>")
            }
        }
    }
}

fn render_node(node: &UiNode, indent: usize) -> String {
    let pad = " ".repeat(indent);
    // Author component
    if node
        .component
        .chars()
        .next()
        .map(|c| c.is_uppercase())
        .unwrap_or(false)
    {
        let props = node
            .props
            .iter()
            .map(|(k, v)| format!("{}={{{}}}", k, expr_to_js(v)))
            .collect::<Vec<_>>();
        let events = node
            .events
            .iter()
            .map(|e| {
                format!(
                    "on{ev}={{{handler}}}",
                    ev = pascal(&e.event),
                    handler = e.handler
                )
            })
            .collect::<Vec<_>>();
        let mut all = props;
        all.extend(events);
        return format!(
            "{pad}<{name} {props} />",
            pad = pad,
            name = node.component,
            props = all.join(" ")
        );
    }

    match node.component.as_str() {
        "page" => {
            let app_bar = node
                .slots
                .iter()
                .find(|(n, _)| n == "app_bar")
                .map(|(_, t)| render_template(t, indent + 2))
                .unwrap_or_default();
            let side = node
                .slots
                .iter()
                .find(|(n, _)| n == "side_panel")
                .map(|(_, t)| render_template(t, indent + 2))
                .unwrap_or_default();
            let children = render_children(&node.children, indent + 4);
            // Viewport-height shell: persistent app bar, independently
            // scrollable sidebar and main content on every ui::page.
            format!(
                "{pad}<div className=\"h-screen overflow-hidden flex flex-col\">\n{app_bar}\n{pad}  <div className=\"min-h-0 flex-1 flex\">\n{side}\n{pad}    <main className=\"min-h-0 min-w-0 flex-1 overflow-y-auto p-6 space-y-4\">\n{children}\n{pad}    </main>\n{pad}  </div>\n{pad}</div>",
                pad = pad,
                app_bar = app_bar,
                side = side,
                children = children
            )
        }
        "app_bar" => format!(
            "{pad}<AppBar title={{{title}}} />",
            pad = pad,
            title = prop_js(node, "title")
        ),
        "side_panel" => format!(
            "{pad}<SidePanel>\n{children}\n{pad}</SidePanel>",
            pad = pad,
            children = render_children(&node.children, indent + 2)
        ),
        "nav_item" => {
            let to = node.prop("to").map(expr_to_js);
            let on_click = if let Some(to) = to {
                format!("() => {{ window.history.pushState({{}}, \"\", {to}); window.dispatchEvent(new PopStateEvent(\"popstate\")); }}")
            } else {
                node.events
                    .iter()
                    .find(|e| e.event == "click")
                    .map(|e| e.handler.clone())
                    .unwrap_or_else(|| "undefined".into())
            };
            format!(
                "{pad}<NavItem label={{{label}}} active={{{active}}} onClick={{{on_click}}} />",
                pad = pad,
                label = prop_js(node, "label"),
                active = node
                    .prop("active")
                    .map(expr_to_js)
                    .unwrap_or_else(|| "false".into()),
                on_click = on_click
            )
        }
        "stack" => format!(
            "{pad}<div className=\"flex flex-col gap-3\">\n{children}\n{pad}</div>",
            pad = pad,
            children = render_children(&node.children, indent + 2)
        ),
        "row" => format!(
            "{pad}<div className=\"flex flex-row gap-3 items-center\">\n{children}\n{pad}</div>",
            pad = pad,
            children = render_children(&node.children, indent + 2)
        ),
        "grid" | "collection" => format!(
            "{pad}<div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4\">\n{children}\n{pad}</div>",
            pad = pad,
            children = render_children(&node.children, indent + 2)
        ),
        "card" => format!(
            "{pad}<Card>\n{children}\n{pad}</Card>",
            pad = pad,
            children = render_children(&node.children, indent + 2)
        ),
        "heading" => {
            let level = node
                .prop("level")
                .and_then(|e| e.as_ident())
                .unwrap_or("2");
            let tag = match level {
                "1" | "h1" => "h1",
                "3" | "h3" => "h3",
                _ => "h2",
            };
            format!(
                "{pad}<{tag} className=\"font-semibold tracking-tight\">{{{text}}}</{tag}>",
                pad = pad,
                tag = tag,
                text = prop_js(node, "text")
            )
        }
        "text" => format!(
            "{pad}<p className=\"text-sm opacity-80\">{{{text}}}</p>",
            pad = pad,
            text = prop_js(node, "text")
        ),
        "form" => {
            let on_submit = node
                .events
                .iter()
                .find(|e| e.event == "submit")
                .map(|e| e.handler.as_str())
                .unwrap_or("undefined");
            format!(
                "{pad}<form className=\"space-y-4\" onSubmit={{async (e) => {{ e.preventDefault(); await {handler}(); }}}}>\n{children}\n{pad}</form>",
                pad = pad,
                handler = on_submit,
                children = render_children(&node.children, indent + 2)
            )
        }
        "text_input" => {
            let field = node
                .prop("field")
                .and_then(|e| e.as_ident())
                .map(|s| s.to_string());
            let value = node
                .prop("value")
                .map(expr_to_js)
                .or_else(|| field.clone())
                .unwrap_or_else(|| "\"\"".into());
            let setter = field
                .as_ref()
                .map(|f| format!("set{}", pascal(f)))
                .unwrap_or_else(|| "undefined".into());
            format!(
                "{pad}<div className=\"space-y-1\"><Label>{{ {label} }}</Label><Input value={{{value}}} onChange={{(e) => {setter}?.(e.target.value)}} /></div>",
                pad = pad,
                label = prop_js(node, "label"),
                value = value,
                setter = setter
            )
        }
        "textarea" => {
            let field = node
                .prop("field")
                .and_then(|e| e.as_ident())
                .map(|s| s.to_string());
            let value = node
                .prop("value")
                .map(expr_to_js)
                .or_else(|| field.clone())
                .unwrap_or_else(|| "\"\"".into());
            let setter = field
                .as_ref()
                .map(|f| format!("set{}", pascal(f)))
                .unwrap_or_else(|| "undefined".into());
            format!(
                "{pad}<div className=\"space-y-1\"><Label>{{ {label} }}</Label><Textarea value={{{value}}} onChange={{(e) => {setter}?.(e.target.value)}} /></div>",
                pad = pad,
                label = prop_js(node, "label"),
                value = value,
                setter = setter
            )
        }
        "radio_group" => {
            let field = node
                .prop("field")
                .and_then(|e| e.as_ident())
                .map(|s| s.to_string());
            let value = node
                .prop("value")
                .map(expr_to_js)
                .or_else(|| field.clone())
                .unwrap_or_else(|| "\"\"".into());
            let setter = field
                .as_ref()
                .map(|f| format!("set{}", pascal(f)))
                .unwrap_or_else(|| "undefined".into());
            let options = node
                .prop("options")
                .map(expr_to_js)
                .unwrap_or_else(|| "[]".into());
            format!(
                "{pad}<RadioGroup label={{{label}}} value={{{value}}} options={{{options}}} onChange={{{setter}}} />",
                pad = pad,
                label = prop_js(node, "label"),
                value = value,
                options = options,
                setter = setter
            )
        }
        "button" => {
            let on_click = node
                .events
                .iter()
                .find(|e| e.event == "click")
                .map(|e| e.handler.clone())
                .unwrap_or_else(|| "undefined".into());
            let submit = node
                .prop("submit")
                .map(|_| "submit")
                .unwrap_or("button");
            let variant = if let Some(active) = node.prop("active") {
                format!(
                    "({} ? \"secondary\" : ({} ?? \"primary\"))",
                    expr_to_js(active),
                    prop_js(node, "variant")
                )
            } else {
                prop_js(node, "variant")
            };
            format!(
                "{pad}<Button type=\"{submit}\" variant={{{variant}}} onClick={{{on_click}}}>{{{label}}}</Button>",
                pad = pad,
                submit = submit,
                variant = variant,
                on_click = on_click,
                label = prop_js(node, "label")
            )
        }
        "toolbar" => format!(
            "{pad}<Toolbar>\n{children}\n{pad}</Toolbar>",
            pad = pad,
            children = render_children(&node.children, indent + 2)
        ),
        "chat" => {
            let field = node
                .prop("field")
                .and_then(|e| e.as_ident())
                .map(|s| s.to_string())
                .or_else(|| {
                    node.prop("value")
                        .and_then(|e| e.as_ident())
                        .map(|s| s.to_string())
                })
                .unwrap_or_else(|| "prompt".into());
            let value = node
                .prop("value")
                .or_else(|| node.prop("field"))
                .map(expr_to_js)
                .unwrap_or_else(|| field.clone());
            let setter = format!("set{}", pascal(&field));
            let send = node
                .events
                .iter()
                .find(|e| e.event == "send")
                .map(|e| e.handler.as_str());
            let on_submit = match send {
                Some(handler) => format!(
                    "async (e) => {{ e.preventDefault(); await {handler}(); }}"
                ),
                None => format!(
                    "async (e) => {{ e.preventDefault(); await __chatComplete({value}); }}"
                ),
            };
            let loading = node
                .prop("loading")
                .map(expr_to_js)
                .unwrap_or_else(|| "historyLoading".into());
            let error = node
                .prop("error")
                .map(expr_to_js)
                .unwrap_or_else(|| "historyError || chatError".into());
            format!(
                "{pad}<div className=\"flex min-h-0 flex-1 flex-col gap-4\">\n{pad}  <ChatThread messages={{messages}} thinking={{thinking}} loading={{{loading}}} error={{{error}}} />\n{pad}  <ChatComposer id={{\"{id}\"}} value={{{value}}} onChange={{{setter}}} onSubmit={{{on_submit}}} submitting={{thinking}} />\n{pad}</div>",
                pad = pad,
                id = field,
                value = value,
                setter = setter,
                on_submit = on_submit,
                loading = loading,
                error = error
            )
        }
        "chat_history" => format!(
            "{pad}<HistoryPanel items={{{items}}} title={{{title}}} />",
            pad = pad,
            items = node
                .prop("items")
                .map(expr_to_js)
                .unwrap_or_else(|| "messages".into()),
            title = prop_js(node, "title")
        ),
        "search_input" => format!(
            "{pad}<SearchInput value={{{value}}} onChange={{setQuery}} onSubmit={{{submit}}} placeholder={{{ph}}} />",
            pad = pad,
            value = node
                .prop("value")
                .map(expr_to_js)
                .unwrap_or_else(|| "query".into()),
            submit = node
                .events
                .iter()
                .find(|e| e.event == "submit")
                .map(|e| e.handler.as_str())
                .unwrap_or("undefined"),
            ph = prop_js(node, "placeholder")
        ),
        "filter_bar" => format!(
            "{pad}<div className=\"flex gap-2 items-center\">\n{children}\n{pad}</div>",
            pad = pad,
            children = render_children(&node.children, indent + 2)
        ),
        "list" => format!(
            "{pad}<ul className=\"space-y-2\">\n{children}\n{pad}</ul>",
            pad = pad,
            children = render_children(&node.children, indent + 2)
        ),
        "loading" => format!(
            "{pad}<p className=\"opacity-60\">{{{text}}}</p>",
            pad = pad,
            text = node
                .prop("text")
                .map(expr_to_js)
                .unwrap_or_else(|| "\"Loading…\"".into())
        ),
        "empty" => format!(
            "{pad}<p className=\"opacity-60\">{{{text}}}</p>",
            pad = pad,
            text = node
                .prop("text")
                .map(expr_to_js)
                .unwrap_or_else(|| "\"No items\"".into())
        ),
        other => format!("{pad}{{/* unsupported ui::{other} */}}"),
    }
}

fn render_children(children: &[UiTemplate], indent: usize) -> String {
    children
        .iter()
        .map(|c| render_template(c, indent))
        .collect::<Vec<_>>()
        .join("\n")
}

fn prop_js(node: &UiNode, name: &str) -> String {
    node.prop(name)
        .map(expr_to_js)
        .unwrap_or_else(|| "undefined".into())
}

pub fn expr_to_js(expr: &Expr) -> String {
    match expr {
        Expr::String(s) => escape_js_string(s),
        Expr::Number(n) => n.clone(),
        Expr::Bool(b) => b.to_string(),
        Expr::Ident(s) | Expr::Var(s) => s.clone(),
        Expr::Member { base, field } => format!("{}.{}", expr_to_js(base), field),
        Expr::Call { callee, args } => format!(
            "{}({})",
            expr_to_js(callee),
            args.iter().map(expr_to_js).collect::<Vec<_>>().join(", ")
        ),
        Expr::BinOp { op, left, right } => format!(
            "({} {} {})",
            expr_to_js(left),
            binop_js(op),
            expr_to_js(right)
        ),
        Expr::Unary { op, expr } => match op {
            UnaryOp::Not => format!("(!{})", expr_to_js(expr)),
            UnaryOp::Neg => format!("(-{})", expr_to_js(expr)),
        },
        Expr::List(items) => format!(
            "[{}]",
            items.iter().map(expr_to_js).collect::<Vec<_>>().join(", ")
        ),
        Expr::New { ty, fields } => {
            let fields = fields
                .iter()
                .map(|(k, v)| format!("{k}: {}", expr_to_js(v)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("/* {ty} */ ({{ {fields} }})")
        }
        Expr::Assign { target, value } => {
            // Prefer React setter when target is a simple var.
            if let Expr::Var(name) | Expr::Ident(name) = target.as_ref() {
                format!("set{}({})", pascal(name), expr_to_js(value))
            } else {
                format!("{} = {}", expr_to_js(target), expr_to_js(value))
            }
        }
        Expr::Emit { event, payload } => {
            let p = payload
                .as_ref()
                .map(|e| expr_to_js(e))
                .unwrap_or_else(|| "undefined".into());
            format!("props.on{}?.({})", pascal(event), p)
        }
        Expr::Navigate { path } => format!(
            "(window.history.pushState({{}}, \"\", {}); window.dispatchEvent(new PopStateEvent(\"popstate\")))",
            escape_js_string(path)
        ),
        Expr::Await(inner) => format!("(await {})", expr_to_js(inner)),
        Expr::Interpolated(parts) => {
            let mut s = String::from("`");
            for part in parts {
                match part {
                    sil_core::InterpPart::Lit(l) => s.push_str(&l.replace('`', "\\`")),
                    sil_core::InterpPart::Expr(e) => {
                        s.push_str(&format!("${{{}}}", expr_to_js(e)));
                    }
                }
            }
            s.push('`');
            s
        }
    }
}

fn expr_to_js_stmt(expr: &Expr, component: &Component) -> String {
    if let Expr::Call { callee, args } = expr {
        if let Expr::Ident(name) = callee.as_ref() {
            if name == "submit" || name.ends_with("submit") {
                let body = if args.is_empty() {
                    let fields = component
                        .state
                        .iter()
                        .map(|f| format!("{}: {}", f.name, f.name))
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{{ {fields} }}")
                } else {
                    expr_to_js(&args[0])
                };
                return format!(
                    "await fetch(\"/submit\", {{ method: \"POST\", headers: {{ \"content-type\": \"application/json\" }}, body: JSON.stringify({body}) }})"
                );
            }
        }
        if let Expr::Member { base, field } = callee.as_ref() {
            if let Expr::Ident(resource) = base.as_ref() {
                let table = snake_case(resource);
                let arg = args.first().map(expr_to_js).unwrap_or_else(|| "{}".into());
                if matches!(field.as_str(), "list" | "all") {
                    let qname = component
                        .queries
                        .iter()
                        .find(|q| q.resource == *resource)
                        .map(|q| q.name.clone())
                        .unwrap_or_else(|| "items".into());
                    return format!(
                        "set{}(await (await fetch(\"/api/{table}\")).json())",
                        pascal(&qname)
                    );
                }
                if field == "complete" {
                    let prompt_field =
                        find_chat_field(&component.render).unwrap_or_else(|| "prompt".into());
                    return format!("await __chatComplete({prompt_field})");
                }
                let method = match field.as_str() {
                    "create" | "add" => "POST",
                    "update" => "PUT",
                    "delete" | "remove" => "DELETE",
                    _ => "POST",
                };
                // Item mutations must target /api/{table}/:id (matches worker ACTIONS).
                if matches!(field.as_str(), "update" | "delete" | "remove") {
                    return format!(
                        "await fetch(`/api/{table}/${{({arg}).id}}`, {{ method: \"{method}\", headers: {{ \"content-type\": \"application/json\" }}, body: JSON.stringify({arg}) }})"
                    );
                }
                // Creating a chat session should select it so history scopes correctly.
                let selects_session = matches!(field.as_str(), "create" | "add")
                    && component.state.iter().any(|f| f.name == "active_session")
                    && (table.contains("session")
                        || resource.to_ascii_lowercase().contains("session"));
                if selects_session {
                    return format!(
                        "{{ const __created = await (await fetch(\"/api/{table}\", {{ method: \"POST\", headers: {{ \"content-type\": \"application/json\" }}, body: JSON.stringify({arg}) }})).json(); setActiveSession(__created.id); }}"
                    );
                }
                return format!(
                    "await fetch(\"/api/{table}\", {{ method: \"{method}\", headers: {{ \"content-type\": \"application/json\" }}, body: JSON.stringify({arg}) }})"
                );
            }
        }
    }
    expr_to_js(expr)
}

fn binop_js(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Eq => "===",
        BinOp::Ne => "!==",
        BinOp::Lt => "<",
        BinOp::Le => "<=",
        BinOp::Gt => ">",
        BinOp::Ge => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}

/// Emit a terminal UI module that mirrors the web component graph.
pub fn render_terminal_module(program: &Program, graph: &ExecutableGraph) -> String {
    let app = graph.app.as_ref().expect("UI graph requires app");
    let mut routes = String::from("[\n");
    for route in &app.routes {
        routes.push_str(&format!(
            "  {{ path: {}, component: {} }},\n",
            escape_js_string(&route.path),
            escape_js_string(&route.component)
        ));
    }
    routes.push(']');
    let mut components = String::from("{\n");
    for component in program.all_components() {
        components.push_str(&format!(
            "  {}: {{\n    props: [{}],\n    state: [{}],\n    emits: [{}],\n    queries: [{}],\n  }},\n",
            component.name,
            component
                .props
                .iter()
                .map(|p| escape_js_string(&p.name))
                .collect::<Vec<_>>()
                .join(", "),
            component
                .state
                .iter()
                .map(|p| escape_js_string(&p.name))
                .collect::<Vec<_>>()
                .join(", "),
            component
                .emits
                .iter()
                .map(|e| escape_js_string(&e.name))
                .collect::<Vec<_>>()
                .join(", "),
            component
                .queries
                .iter()
                .map(|q| escape_js_string(&q.name))
                .collect::<Vec<_>>()
                .join(", "),
        ));
    }
    components.push('}');
    format!(
        r#"// AUTO-GENERATED BY silc 0.2.0 — terminal surface metadata
export const ROUTES = {routes};
export const COMPONENTS = {components};
export const SURFACES = ["web", "terminal"];
"#,
        routes = routes,
        components = components
    )
}

fn escape_js_string(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

fn pascal(s: &str) -> String {
    let mut out = String::new();
    let mut cap = true;
    for ch in s.chars() {
        if ch == '_' || ch == '-' {
            cap = true;
            continue;
        }
        if cap {
            out.extend(ch.to_uppercase());
            cap = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use sil_core::{Expr, Span, UiNode, UiTemplate};

    #[test]
    fn expr_member_to_js() {
        let e = Expr::Member {
            base: Box::new(Expr::Var("product".into())),
            field: "name".into(),
        };
        assert_eq!(expr_to_js(&e), "product.name");
    }

    #[test]
    fn renders_heading_node() {
        let node = UiNode {
            component: "heading".into(),
            props: vec![("text".into(), Expr::String("Hello".into()))],
            events: vec![],
            slots: vec![],
            children: vec![],
            span: Span::default(),
        };
        let html = render_template(&UiTemplate::Node(node), 0);
        assert!(html.contains("Hello"));
    }

    #[test]
    fn active_button_uses_session_selected_variant() {
        let node = UiNode {
            component: "button".into(),
            props: vec![
                ("label".into(), Expr::String("Session".into())),
                ("active".into(), Expr::Var("is_selected".into())),
            ],
            events: vec![],
            slots: vec![],
            children: vec![],
            span: Span::default(),
        };
        let html = render_template(&UiTemplate::Node(node), 0);
        assert!(html.contains("is_selected ? \"secondary\""));
    }
}
