// AUTO-GENERATED BY silc — DO NOT EDIT
/** Deterministic hostile BT + simple waypoint navigation. Silclm only biases tactics. */

import { Ray, Vector3 } from "@babylonjs/core";
import type { BabylonHandles } from "../adapters/babylonScene.ts";
import type { Possession } from "../framework/mode.ts";
import type { Resources } from "../kernel/resources.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { EntityId, World } from "../kernel/world.ts";
import type { CombatState } from "./weapons.ts";

export type MindDirective = {
  aggression: number;
  preferred_tactic: "suppress" | "flank_left" | "flank_right" | "push" | "retreat" | "hold";
  bark?: string;
  ttl_s: number;
  revision: number;
};

type NpcBrain = {
  tactic: MindDirective["preferred_tactic"];
  waypoint: number;
  fireCd: number;
  repath: number;
  alert: boolean;
};

const brains = new Map<EntityId, NpcBrain>();

export function createAiSystem(
  world: World,
  handles: BabylonHandles,
  resources: Resources,
  possession: Possession,
  combat: CombatState,
): GameSystem {
  const waypoints = buildWaypoints(resources);
  return {
    name: "ai",
    order: 22,
    init() {
      for (const [id] of world.query("npc")) {
        brains.set(id, {
          tactic: defaultTactic(world, id),
          waypoint: Math.floor(Math.random() * Math.max(1, waypoints.length)),
          fireCd: 0.5 + Math.random(),
          repath: 0,
          alert: false,
        });
        ensureHealth(world, id);
      }
    },
    fixedUpdate(ctx) {
      const playerId = possession.pawnId;
      if (playerId == null) return;
      const playerPos = world.worldPosition(playerId);

      for (const [id, npc] of world.query("npc")) {
        if (world.getComponent("dead", id)) {
          const node = handles.nodes.get(id);
          if (node) node.setEnabled(false);
          continue;
        }
        const brain = brains.get(id) ?? {
          tactic: "suppress" as const,
          waypoint: 0,
          fireCd: 0,
          repath: 0,
          alert: false,
        };
        brains.set(id, brain);
        brain.fireCd = Math.max(0, brain.fireCd - ctx.fixedDt);
        brain.repath -= ctx.fixedDt;

        const directive = world.getComponent<MindDirective>("directive", id);
        if (directive && directive.ttl_s > 0) {
          directive.ttl_s -= ctx.fixedDt;
          brain.tactic = sanitizeTactic(directive.preferred_tactic);
          world.addComponent("directive", id, directive);
          if (directive.bark) {
            world.addComponent("bark", id, { text: directive.bark, t: 2.5 });
          }
        }

        const pos = world.worldPosition(id);
        const dist = Math.hypot(playerPos.x - pos.x, playerPos.z - pos.z);
        const perception = world.getComponent<{ sightM: number; hearM: number; fovDeg: number }>(
          "perception",
          id,
        );
        const sight = perception?.sightM ?? 28;
        const canSee = dist < sight && hasLineOfSight(handles, pos, playerPos);
        if (canSee || dist < (perception?.hearM ?? 12)) brain.alert = true;

        const speed = world.getComponent<{ speed: number }>("movement", id)?.speed ?? 3.2;
        let target = { x: pos.x, z: pos.z };
        if (!brain.alert) {
          const wp = waypoints[brain.waypoint % Math.max(1, waypoints.length)] ?? {
            x: pos.x,
            z: pos.z,
          };
          target = wp;
          if (Math.hypot(wp.x - pos.x, wp.z - pos.z) < 1.2) {
            brain.waypoint = (brain.waypoint + 1) % Math.max(1, waypoints.length);
          }
        } else {
          target = tacticTarget(brain.tactic, pos, playerPos, waypoints);
        }

        const dx = target.x - pos.x;
        const dz = target.z - pos.z;
        const len = Math.hypot(dx, dz) || 1;
        const yaw = Math.atan2(playerPos.x - pos.x, playerPos.z - pos.z);
        const vel =
          world.getComponent<{ vx: number; vy: number; vz: number }>("velocity", id) ?? {
            vx: 0,
            vy: 0,
            vz: 0,
          };
        // Physics owns integration; AI only writes desired planar velocity.
        vel.vx = (dx / len) * speed;
        vel.vz = (dz / len) * speed;
        world.addComponent("velocity", id, vel);
        world.setTransform(id, { yaw });

        if (brain.alert && canSee && brain.fireCd <= 0 && dist < sight) {
          npcFire(world, handles, id, pos, playerPos, playerId, combat, npc);
          brain.fireCd = fireInterval(npc);
        }

        const bark = world.getComponent<{ text: string; t: number }>("bark", id);
        if (bark) {
          bark.t -= ctx.fixedDt;
          if (bark.t <= 0) world.addComponent("bark", id, { text: "", t: 0 });
          else world.addComponent("bark", id, bark);
        }
      }
    },
  };
}

function npcFire(
  world: World,
  handles: BabylonHandles,
  id: EntityId,
  from: { x: number; y: number; z: number },
  to: { x: number; y: number; z: number },
  playerId: EntityId,
  combat: CombatState,
  npc: unknown,
): void {
  const archetype = (npc as { archetype?: string })?.archetype ?? "suppressor";
  const damage = archetype === "breacher" ? 14 : archetype === "flanker" ? 10 : 8;
  const origin = new Vector3(from.x, from.y + 1.4, from.z);
  const dir = new Vector3(to.x - from.x, to.y + 1.5 - (from.y + 1.4), to.z - from.z).normalize();
  // Spread
  dir.x += (Math.random() - 0.5) * 0.05;
  dir.y += (Math.random() - 0.5) * 0.03;
  dir.z += (Math.random() - 0.5) * 0.05;
  dir.normalize();
  const ray = new Ray(origin, dir, 50);
  const hit = handles.scene.pickWithRay(ray);
  if (hit?.hit) {
    const dPlayer = Math.hypot(to.x - from.x, to.z - from.z);
    if (dPlayer < 45 && Math.random() < 0.55) {
      combat.health = Math.max(0, combat.health - damage);
      const attrs =
        world.getComponent<{ name: string; value: number; max: number | null }[]>(
          "attributes",
          playerId,
        ) ?? [];
      const health = attrs.find((a) => a.name === "health");
      if (health) {
        health.value = combat.health;
        world.addComponent("attributes", playerId, attrs);
      }
    }
  }
}

function hasLineOfSight(
  handles: BabylonHandles,
  from: { x: number; y: number; z: number },
  to: { x: number; y: number; z: number },
): boolean {
  const origin = new Vector3(from.x, from.y + 1.4, from.z);
  const target = new Vector3(to.x, to.y + 1.5, to.z);
  const dir = target.subtract(origin);
  const len = dir.length();
  dir.normalize();
  const ray = new Ray(origin, dir, len);
  const hit = handles.scene.pickWithRay(ray, (m) => {
    const n = m.name.toLowerCase();
    return m.isVisible && !n.includes("cue_") && !n.includes("player");
  });
  if (!hit?.hit) return true;
  return (hit.distance ?? len) >= len - 0.6;
}

function tacticTarget(
  tactic: MindDirective["preferred_tactic"],
  pos: { x: number; z: number },
  player: { x: number; z: number },
  waypoints: Array<{ x: number; z: number }>,
): { x: number; z: number } {
  const dx = player.x - pos.x;
  const dz = player.z - pos.z;
  const len = Math.hypot(dx, dz) || 1;
  const fx = dx / len;
  const fz = dz / len;
  const lx = -fz;
  const lz = fx;
  switch (tactic) {
    case "flank_left":
      return { x: player.x + lx * 6 - fx * 2, z: player.z + lz * 6 - fz * 2 };
    case "flank_right":
      return { x: player.x - lx * 6 - fx * 2, z: player.z - lz * 6 - fz * 2 };
    case "push":
      return { x: player.x - fx * 3, z: player.z - fz * 3 };
    case "retreat":
      return { x: pos.x - fx * 8, z: pos.z - fz * 8 };
    case "hold":
      return nearestCover(pos, waypoints);
    case "suppress":
    default:
      return { x: player.x - fx * 9 + lx * 2, z: player.z - fz * 9 + lz * 2 };
  }
}

function nearestCover(pos: { x: number; z: number }, waypoints: Array<{ x: number; z: number }>) {
  let best = waypoints[0] ?? pos;
  let bestD = Infinity;
  for (const wp of waypoints) {
    const d = Math.hypot(wp.x - pos.x, wp.z - pos.z);
    if (d < bestD) {
      bestD = d;
      best = wp;
    }
  }
  return best;
}

function buildWaypoints(resources: Resources): Array<{ x: number; z: number }> {
  const pts: Array<{ x: number; z: number }> = [];
  for (const zone of resources.manifest.zones ?? []) {
    // Zone origins aren't explicit — derive from child transforms if present.
    for (const child of zone.children ?? []) {
      const t = (child as { transform?: { x: number; z: number } }).transform;
      if (t) pts.push({ x: t.x, z: t.z });
    }
    for (const spawn of zone.spawns ?? []) {
      const t = spawn.overrides?.transform;
      if (t) pts.push({ x: t.x, z: t.z });
    }
  }
  if (!pts.length) {
    pts.push(
      { x: -12, z: -8 },
      { x: 12, z: -8 },
      { x: 12, z: 12 },
      { x: -12, z: 12 },
      { x: 0, z: 18 },
      { x: 0, z: -16 },
    );
  }
  return pts;
}

function defaultTactic(world: World, id: EntityId): MindDirective["preferred_tactic"] {
  const behavior = world.getComponent<{ defaultTactic?: string }>("behavior", id);
  const npc = world.getComponent<{ archetype?: string }>("npc", id);
  const t = behavior?.defaultTactic ?? npc?.archetype;
  return sanitizeTactic(t);
}

function sanitizeTactic(t: unknown): MindDirective["preferred_tactic"] {
  const s = String(t ?? "suppress");
  if (s.includes("flank_left") || s === "flanker") return "flank_left";
  if (s.includes("flank_right")) return "flank_right";
  if (s.includes("push") || s === "breacher") return "push";
  if (s.includes("retreat")) return "retreat";
  if (s.includes("hold")) return "hold";
  return "suppress";
}

function fireInterval(npc: unknown): number {
  const a = (npc as { archetype?: string })?.archetype;
  if (a === "breacher") return 0.55;
  if (a === "flanker") return 0.4;
  return 0.7;
}

function ensureHealth(world: World, id: EntityId): void {
  const attrs =
    world.getComponent<{ name: string; value: number; max: number | null }[]>("attributes", id) ??
    [];
  if (!attrs.some((a) => a.name === "health")) {
    attrs.push({ name: "health", value: 100, max: 100 });
    world.addComponent("attributes", id, attrs);
  }
}
