// AUTO-GENERATED BY silc — DO NOT EDIT
/** Collectible system for overlap-based pickups (coins, gems, powerups, etc.). */

import type { AbstractMesh } from "@babylonjs/core";
import type { BabylonHandles } from "../adapters/babylonScene.ts";
import type { Possession } from "../framework/mode.ts";
import type { Resources } from "../kernel/resources.ts";
import type { SignalBus } from "../kernel/signals.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { EntityId, World } from "../kernel/world.ts";

export type CollectibleComp = {
  kind: "coin" | "gem" | "health" | "powerup" | "key" | "custom";
  value?: number;
  onCollect?: string;
  respawn?: number;
};

type CollectibleState = {
  collected: boolean;
  respawnTimer: number;
  originalY: number;
  meshes: AbstractMesh[]; // All meshes associated with this collectible
};

const collectibleStates = new Map<EntityId, CollectibleState>();

/** Find all meshes near a position that belong to this collectible. */
function findMeshesAtPosition(
  scene: { meshes: AbstractMesh[] },
  pos: { x: number; y: number; z: number },
  tolerance = 1.0,
): AbstractMesh[] {
  const result: AbstractMesh[] = [];
  for (const mesh of scene.meshes) {
    const name = mesh.name.toLowerCase();
    
    // Only consider meshes that are explicitly collectible-related
    // Must contain "coin" or be a sprite for a coin entity
    const isCollectibleMesh = 
      name.includes("coin") ||
      (name.startsWith("sprite_") && !name.includes("mario") && !name.includes("goomba") && !name.includes("koopa"));
    
    if (!isCollectibleMesh) continue;
    
    const meshPos = mesh.absolutePosition;
    const dist = Math.sqrt(
      (meshPos.x - pos.x) ** 2 +
      (meshPos.y - pos.y) ** 2 +
      (meshPos.z - pos.z) ** 2
    );
    if (dist < tolerance) {
      result.push(mesh);
    }
  }
  return result;
}

export function createCollectibleSystem(
  world: World,
  handles: BabylonHandles,
  resources: Resources,
  signals: SignalBus,
  possession: Possession,
): GameSystem {
  return {
    name: "collectible",
    order: 30,
    init() {
      // Delay mesh discovery to allow sprite system to create meshes first
      setTimeout(() => {
        for (const [id] of world.query("collectible")) {
          const pos = world.worldPosition(id);
          const meshes = findMeshesAtPosition(handles.scene, pos);
          collectibleStates.set(id, {
            collected: false,
            respawnTimer: 0,
            originalY: pos.y,
            meshes,
          });
        }
      }, 100);
    },
    fixedUpdate(ctx) {
      const pawnId = possession.pawnId;
      if (pawnId == null) return;

      const pawnPos = world.worldPosition(pawnId);
      const pawnCollider = world.getComponent<{ size: number }>("collider", pawnId);
      const pawnRadius = (pawnCollider?.size ?? 1) * 0.5;

      for (const [id, raw] of world.query("collectible")) {
        const collectible = raw as CollectibleComp;
        
        // Lazily initialize state for collectibles that weren't present at init
        let state = collectibleStates.get(id);
        if (!state) {
          const pos = world.worldPosition(id);
          const meshes = findMeshesAtPosition(handles.scene, pos);
          state = {
            collected: false,
            respawnTimer: 0,
            originalY: pos.y,
            meshes,
          };
          collectibleStates.set(id, state);
        }

        // Handle respawn timer
        if (state.collected) {
          if (collectible.respawn != null && collectible.respawn > 0) {
            state.respawnTimer -= ctx.fixedDt;
            if (state.respawnTimer <= 0) {
              state.collected = false;
              // Restore sprite visibility
              const sprite = world.getComponent<{ visible?: boolean }>("sprite", id);
              if (sprite) {
                sprite.visible = true;
                world.addComponent("sprite", id, sprite);
              }
              // Restore all meshes
              for (const mesh of state.meshes) {
                mesh.setEnabled(true);
              }
            }
          }
          continue;
        }

        // Check overlap with pawn
        const pos = world.worldPosition(id);
        const collider = world.getComponent<{ size: number }>("collider", id);
        const radius = (collider?.size ?? 0.5) * 0.5;

        const dx = pawnPos.x - pos.x;
        const dy = pawnPos.y - pos.y;
        const dz = pawnPos.z - pos.z;
        const distSq = dx * dx + dy * dy + dz * dz;
        const touchDist = pawnRadius + radius;

        if (distSq < touchDist * touchDist) {
          // Collected!
          state.collected = true;
          state.respawnTimer = collectible.respawn ?? 0;

          // Hide the collectible by setting sprite visibility to false
          // This prevents the sprite system from re-enabling it
          const sprite = world.getComponent<{ visible?: boolean }>("sprite", id);
          if (sprite) {
            sprite.visible = false;
            world.addComponent("sprite", id, sprite);
          }

          // Hide all associated meshes
          for (const mesh of state.meshes) {
            mesh.setEnabled(false);
          }

          // Apply effect based on kind
          applyCollectibleEffect(world, pawnId, collectible, possession);

          // Fire signal with position
          if (collectible.onCollect) {
            signals.emit(collectible.onCollect, {
              collectibleId: id,
              kind: collectible.kind,
              value: collectible.value ?? 1,
              x: pos.x,
              y: pos.y,
              z: pos.z,
            });
          }

          // Default signal with position for floating text
          signals.emit("collected", {
            collectibleId: id,
            kind: collectible.kind,
            value: collectible.value ?? 1,
            x: pos.x,
            y: pos.y,
            z: pos.z,
          });
        }
      }
    },
    update(ctx) {
      // Animate collectibles (bob up and down, rotate)
      for (const [id, raw] of world.query("collectible")) {
        let state = collectibleStates.get(id);
        if (!state) {
          const pos = world.worldPosition(id);
          const meshes = findMeshesAtPosition(handles.scene, pos);
          state = {
            collected: false,
            respawnTimer: 0,
            originalY: pos.y,
            meshes,
          };
          collectibleStates.set(id, state);
        }
        if (state.collected) continue;

        // Animate all meshes
        for (const mesh of state.meshes) {
          // Bob animation
          const bobOffset = Math.sin(ctx.time * 3) * 0.1;
          mesh.position.y = state.originalY + bobOffset;

          // Rotate
          mesh.rotation.y += ctx.dt * 2;
        }
      }
    },
  };
}

function applyCollectibleEffect(
  world: World,
  pawnId: EntityId,
  collectible: CollectibleComp,
  possession: Possession,
): void {
  const value = collectible.value ?? 1;

  switch (collectible.kind) {
    case "coin":
    case "gem":
      // Add to score
      possession.score += value;
      break;

    case "health": {
      // Restore health
      const attrs = world.getComponent<Array<{ name: string; value: number; max: number | null }>>(
        "attributes",
        pawnId,
      );
      if (attrs) {
        const health = attrs.find((a) => a.name === "health");
        if (health) {
          health.value = Math.min(health.value + value, health.max ?? 100);
          world.addComponent("attributes", pawnId, attrs);
        }
      }
      break;
    }

    case "powerup":
      // Powerup effects are game-specific, handled via signals
      break;

    case "key":
      // Key collection is game-specific, handled via signals
      break;

    case "custom":
      // Custom effects handled via signals
      break;
  }
}
