// AUTO-GENERATED BY silc — DO NOT EDIT
/** Floating text system for score/damage popups. */

import { DynamicTexture, Mesh, MeshBuilder, StandardMaterial } from "@babylonjs/core";
import type { BabylonHandles } from "../adapters/babylonScene.ts";
import type { Resources } from "../kernel/resources.ts";
import type { SignalBus } from "../kernel/signals.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { World } from "../kernel/world.ts";

export type FloatingTextConfig = {
  onTrigger: string;
  prefix?: string;
  color?: string;
  duration?: number;
  riseSpeed?: number;
};

type FloatingText = {
  mesh: Mesh;
  material: StandardMaterial;
  startY: number;
  life: number;
  maxLife: number;
  riseSpeed: number;
};

const activeTexts: FloatingText[] = [];
const textConfigs = new Map<string, FloatingTextConfig>();

export function createFloatingTextSystem(
  world: World,
  handles: BabylonHandles,
  resources: Resources,
  signals: SignalBus,
): GameSystem {
  return {
    name: "floatingText",
    order: 75,
    init() {
      // Register configs from manifest
      const configs = resources.manifest.floatingTexts ?? [];
      for (const config of configs) {
        textConfigs.set(config.onTrigger, config);

        // Set up signal listener
        signals.connect(config.onTrigger, (data) => {
          const { value, x, y, z } = (data ?? {}) as { value?: number; x?: number; y?: number; z?: number };
          if (value !== undefined) {
            spawnFloatingText(handles, config, value, x ?? 0, y ?? 0, z ?? 0);
          }
        });
      }

      // Default handlers for common signals
      signals.connect("score_gained", (data) => {
        const { value, x, y, z } = data as { value: number; x?: number; y?: number; z?: number };
        const config = textConfigs.get("score_gained") ?? {
          onTrigger: "score_gained",
          prefix: "+",
          color: "#ffff00",
          duration: 1,
          riseSpeed: 2,
        };
        spawnFloatingText(handles, config, value, x ?? 0, y ?? 0, z ?? 0);
      });

      signals.connect("damage_dealt", (data) => {
        const { value, x, y, z } = data as { value: number; x?: number; y?: number; z?: number };
        const config = textConfigs.get("damage_dealt") ?? {
          onTrigger: "damage_dealt",
          prefix: "-",
          color: "#ff4444",
          duration: 0.8,
          riseSpeed: 2.5,
        };
        spawnFloatingText(handles, config, value, x ?? 0, y ?? 0, z ?? 0);
      });

      // Also handle collected signal for score display
      signals.connect("collected", (data) => {
        const { value, x, y, z } = (data ?? {}) as { value?: number; x?: number; y?: number; z?: number; kind?: string };
        if (value && value > 0) {
          const config = textConfigs.get("collected") ?? {
            onTrigger: "collected",
            prefix: "+",
            color: "#ffd700",
            duration: 1,
            riseSpeed: 2,
          };
          spawnFloatingText(handles, config, value, x ?? 0, y ?? 0, z ?? 0);
        }
      });
    },
    update(ctx) {
      // Update active floating texts
      for (let i = activeTexts.length - 1; i >= 0; i--) {
        const ft = activeTexts[i];
        ft.life -= ctx.dt;

        if (ft.life <= 0) {
          ft.mesh.dispose();
          ft.material.dispose();
          activeTexts.splice(i, 1);
          continue;
        }

        // Rise upward
        ft.mesh.position.y += ft.riseSpeed * ctx.dt;

        // Fade out
        const alpha = ft.life / ft.maxLife;
        ft.mesh.visibility = alpha;

        // Billboard: face camera
        const cam = handles.scene.activeCamera;
        if (cam) {
          ft.mesh.lookAt(cam.position);
        }
      }
    },
  };
}

function spawnFloatingText(
  handles: BabylonHandles,
  config: FloatingTextConfig,
  value: number,
  x: number,
  y: number,
  z: number,
): void {
  const prefix = config.prefix ?? "";
  const colorHex = config.color ?? "#ffffff";
  const duration = config.duration ?? 1;
  const riseSpeed = config.riseSpeed ?? 2;

  const text = `${prefix}${value}`;

  // Create dynamic texture for text
  const textureSize = 128;
  const texture = new DynamicTexture(
    `floatText_${Date.now()}`,
    { width: textureSize, height: textureSize / 2 },
    handles.scene,
    false,
  );

  // Parse color
  const hex = colorHex.replace("#", "");
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);

  // Draw text
  const ctx = texture.getContext();
  ctx.clearRect(0, 0, textureSize, textureSize / 2);
  ctx.font = "bold 48px Arial";
  ctx.fillStyle = `rgb(${r}, ${g}, ${b})`;
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(text, textureSize / 2, textureSize / 4);

  // Add outline for visibility
  ctx.strokeStyle = "#000000";
  ctx.lineWidth = 3;
  ctx.strokeText(text, textureSize / 2, textureSize / 4);
  ctx.fillText(text, textureSize / 2, textureSize / 4);

  texture.update();

  // Create plane mesh
  const mesh = MeshBuilder.CreatePlane(
    `floatText_mesh_${Date.now()}`,
    { width: 1.5, height: 0.75 },
    handles.scene,
  );
  mesh.position.set(x, y + 1, z);
  mesh.isPickable = false;

  // Create material
  const material = new StandardMaterial(`floatText_mat_${Date.now()}`, handles.scene);
  material.diffuseTexture = texture;
  material.useAlphaFromDiffuseTexture = true;
  material.transparencyMode = 2; // ALPHA_TEST
  material.disableLighting = true;
  material.emissiveColor.set(1, 1, 1);
  material.backFaceCulling = false;

  mesh.material = material;

  activeTexts.push({
    mesh,
    material,
    startY: y + 1,
    life: duration,
    maxLife: duration,
    riseSpeed,
  });
}

/** Clean up all active floating texts. */
export function disposeFloatingTexts(): void {
  for (const ft of activeTexts) {
    ft.mesh.dispose();
    ft.material.dispose();
  }
  activeTexts.length = 0;
}
