// AUTO-GENERATED BY silc — DO NOT EDIT
import type { Possession } from "../framework/mode.ts";
import type { Resources } from "../kernel/resources.ts";
import type { HudDef } from "../manifest.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { World } from "../kernel/world.ts";
import type { CombatState } from "./weapons.ts";

export function createHudSystem(
  world: World,
  resources: Resources,
  possession: Possession,
  combat: CombatState,
): GameSystem {
  let root: HTMLDivElement | null = null;
  let cross: HTMLDivElement | null = null;
  return {
    name: "hud",
    order: 85,
    init() {
      const hud = resources.manifest.hud ?? {
        showCrosshair: true,
        showAmmo: true,
        showHealth: true,
      };
      root = document.createElement("div");
      root.id = "silc-fps-hud";
      root.style.cssText =
        "position:fixed;inset:0;pointer-events:none;z-index:30;color:#e8eef7;font:14px/1.4 ui-sans-serif,system-ui,sans-serif;";
      document.body.appendChild(root);

      if (hud.showCrosshair !== false) {
        cross = document.createElement("div");
        cross.style.cssText =
          "position:absolute;left:50%;top:50%;width:14px;height:14px;margin:-7px 0 0 -7px;border:1px solid rgba(255,255,255,0.75);border-radius:50%;box-shadow:0 0 8px rgba(0,0,0,0.5);";
        root.appendChild(cross);
      }

      const panel = document.createElement("div");
      panel.id = "silc-fps-hud-panel";
      panel.style.cssText =
        "position:absolute;left:16px;bottom:16px;min-width:220px;padding:10px 12px;background:rgba(6,10,16,0.72);border:1px solid rgba(255,255,255,0.12);border-radius:8px;";
      root.appendChild(panel);

      const tips = document.createElement("div");
      tips.style.cssText =
        "position:absolute;right:16px;bottom:16px;opacity:0.7;font-size:12px;text-align:right;";
      tips.innerHTML =
        "WASD move · Mouse look · LMB fire · Space jump · Shift sprint · R reload · 1-4 weapons · F1 debug";
      root.appendChild(tips);
    },
    update() {
      const panel = document.getElementById("silc-fps-hud-panel");
      if (!panel) return;
      const w = combat.weapons[combat.active];
      const hud: Partial<HudDef> = resources.manifest.hud ?? {};
      const lines: string[] = [];
      if (hud.showHealth !== false) {
        lines.push(`HP ${combat.health.toFixed(0)} / ${combat.maxHealth.toFixed(0)}`);
      }
      if (w && hud.showAmmo !== false) {
        const reload = w.reloading > 0 ? ` · RELOADING` : "";
        lines.push(
          `${w.name} [${w.fireMode}]  ${w.ammo}/${w.magazine}  (${w.reserve})${reload}`,
        );
      }
      lines.push(`Score ${combat.score}`);
      if (combat.lastHit) lines.push(`Last hit: ${combat.lastHit}`);

      // NPC barks
      const barks: string[] = [];
      for (const [id, bark] of world.query("bark")) {
        const b = bark as { text: string; t: number };
        if (b.text && b.t > 0) barks.push(`${world.nameOf(id)}: "${b.text}"`);
      }
      if (barks.length) lines.push(barks[0]);

      if (combat.health <= 0) {
        lines.push("GAME OVER");
        lines.push("Press R to restart");
        if (cross) cross.style.borderColor = "rgba(255,80,80,0.9)";
        
        // Handle restart
        if (resources.input.consumeKey("KeyR")) {
          window.location.reload();
        }
      }
      panel.innerHTML = lines.map((l) => `<div>${escapeHtml(l)}</div>`).join("");
    },
    dispose() {
      root?.remove();
      root = null;
      cross = null;
    },
  };
}

function escapeHtml(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
