// AUTO-GENERATED BY silc — DO NOT EDIT
/** Interactable system for blocks that respond to bumps and hits. */

import { Color3 } from "@babylonjs/core";
import type { BabylonHandles } from "../adapters/babylonScene.ts";
import type { Possession } from "../framework/mode.ts";
import { instantiatePrefab } from "../framework/spawn.ts";
import type { Groups } from "../kernel/groups.ts";
import type { Resources } from "../kernel/resources.ts";
import type { SignalBus } from "../kernel/signals.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { EntityId, World } from "../kernel/world.ts";

export type InteractableComp = {
  kind: "breakable" | "bumpable" | "switchable" | "container";
  contents?: string;
  health?: number;
  onInteract?: string;
};

type InteractableState = {
  activated: boolean;
  health: number;
  bumpCooldown: number;
  bumpOffset: number;
  bumpVelocity: number;
};

const interactableStates = new Map<EntityId, InteractableState>();

/** Ease-out curve for smooth bump animation. */
function easeOutQuad(t: number): number {
  return 1 - (1 - t) * (1 - t);
}

export function createInteractableSystem(
  world: World,
  groups: Groups,
  handles: BabylonHandles,
  resources: Resources,
  signals: SignalBus,
  possession: Possession,
): GameSystem {
  return {
    name: "interactable",
    order: 28,
    init() {
      for (const [id, raw] of world.query("interactable")) {
        const interactable = raw as InteractableComp;
        interactableStates.set(id, {
          activated: false,
          health: interactable.health ?? 1,
          bumpCooldown: 0,
          bumpOffset: 0,
          bumpVelocity: 0,
        });
      }
    },
    fixedUpdate(ctx) {
      const pawnId = possession.pawnId;
      if (pawnId == null) return;

      const pawnPos = world.worldPosition(pawnId);
      const pawnVel = world.getComponent<{ vx: number; vy: number; vz: number }>("velocity", pawnId);

      for (const [id, raw] of world.query("interactable")) {
        const interactable = raw as InteractableComp;
        const state = interactableStates.get(id);
        if (!state) continue;

        // Update bump cooldown
        if (state.bumpCooldown > 0) {
          state.bumpCooldown -= ctx.fixedDt;
        }

        // Skip if already activated (for bumpable/container)
        if (state.activated && (interactable.kind === "bumpable" || interactable.kind === "container")) {
          continue;
        }

        // Check for head-bump (pawn hitting from below while moving up)
        const pos = world.worldPosition(id);
        const collider = world.getComponent<{ size: number }>("collider", id);
        const halfSize = (collider?.size ?? 1) * 0.5;

        const pawnCollider = world.getComponent<{ size: number }>("collider", pawnId);
        const pawnHalfH = (pawnCollider?.size ?? 1.8) * 0.5;

        // Check if pawn head is hitting block bottom
        const pawnHead = pawnPos.y + pawnHalfH * 2;
        const blockBottom = pos.y - halfSize;

        const horizontalOverlap =
          Math.abs(pawnPos.x - pos.x) < halfSize + 0.3 &&
          Math.abs(pawnPos.z - pos.z) < halfSize + 0.3;

        const headBump =
          horizontalOverlap &&
          pawnHead >= blockBottom - 0.1 &&
          pawnHead <= blockBottom + 0.3 &&
          pawnVel &&
          pawnVel.vy > 0 &&
          state.bumpCooldown <= 0;

        if (headBump) {
          handleInteraction(world, groups, handles, resources, signals, id, interactable, state, "bump", pos);
          state.bumpCooldown = 0.3;
        }
      }
    },
    update(ctx) {
      // Animate bump offset with physics-based spring
      for (const [id] of world.query("interactable")) {
        const state = interactableStates.get(id);
        if (!state) continue;

        if (state.bumpOffset !== 0 || state.bumpVelocity !== 0) {
          // Spring physics: accelerate back to 0
          const springForce = -state.bumpOffset * 80;
          const damping = -state.bumpVelocity * 8;
          state.bumpVelocity += (springForce + damping) * ctx.dt;
          state.bumpOffset += state.bumpVelocity * ctx.dt;

          // Snap to 0 when close enough
          if (Math.abs(state.bumpOffset) < 0.01 && Math.abs(state.bumpVelocity) < 0.1) {
            state.bumpOffset = 0;
            state.bumpVelocity = 0;
          }

          const node = handles.nodes.get(id);
          if (node) {
            const baseY = world.transform(id)?.y ?? 0;
            node.position.y = baseY + state.bumpOffset;
          }
        }
      }
    },
  };
}

function handleInteraction(
  world: World,
  groups: Groups,
  handles: BabylonHandles,
  resources: Resources,
  signals: SignalBus,
  id: EntityId,
  interactable: InteractableComp,
  state: InteractableState,
  interactionType: "bump" | "hit",
  blockPos: { x: number; y: number; z: number },
): void {
  switch (interactable.kind) {
    case "bumpable":
      // Start bump animation with upward velocity
      state.bumpVelocity = 4;

      // Spawn contents if not activated
      if (!state.activated && interactable.contents) {
        spawnContents(world, groups, handles, resources, signals, id, interactable.contents, blockPos);
        state.activated = true;

        // Change to "empty" appearance
        updateToEmptyState(handles, id);

        // Update sprite animation if present
        const sprite = world.getComponent<{ animation?: string }>("sprite", id);
        if (sprite) {
          sprite.animation = "empty";
          world.addComponent("sprite", id, sprite);
        }
      }

      // Emit item_spawned signal
      signals.emit("item_spawned", {
        blockId: id,
        x: blockPos.x,
        y: blockPos.y,
        z: blockPos.z,
        contents: interactable.contents,
      });
      break;

    case "breakable":
      state.health -= 1;
      if (state.health <= 0) {
        // Destroy the block
        const node = handles.nodes.get(id);
        if (node) node.setEnabled(false);
        state.activated = true;

        // Emit block_break signal for particles
        signals.emit("block_break", {
          blockId: id,
          x: blockPos.x,
          y: blockPos.y,
          z: blockPos.z,
        });
      } else {
        // Bump animation
        state.bumpVelocity = 2;
      }
      break;

    case "container":
      if (!state.activated && interactable.contents) {
        spawnContents(world, groups, handles, resources, signals, id, interactable.contents, blockPos);
        state.activated = true;

        signals.emit("item_spawned", {
          blockId: id,
          x: blockPos.x,
          y: blockPos.y,
          z: blockPos.z,
          contents: interactable.contents,
        });
      }
      break;

    case "switchable":
      state.activated = !state.activated;
      // Toggle visual state
      const sprite = world.getComponent<{ animation?: string }>("sprite", id);
      if (sprite) {
        sprite.animation = state.activated ? "on" : "off";
        world.addComponent("sprite", id, sprite);
      }
      break;
  }

  // Fire signal
  if (interactable.onInteract) {
    signals.emit(interactable.onInteract, {
      interactableId: id,
      kind: interactable.kind,
      interactionType,
      activated: state.activated,
      x: blockPos.x,
      y: blockPos.y,
      z: blockPos.z,
    });
  }

  // Default signal
  signals.emit("interacted", {
    interactableId: id,
    kind: interactable.kind,
    interactionType,
    activated: state.activated,
    x: blockPos.x,
    y: blockPos.y,
    z: blockPos.z,
  });
}

function updateToEmptyState(handles: BabylonHandles, id: EntityId): void {
  const node = handles.nodes.get(id);
  if (!node) return;

  // Try to update material color to indicate empty state
  const mesh = node as { material?: { emissiveColor?: Color3; diffuseColor?: Color3 } };
  if (mesh.material) {
    // Darken the block to show it's empty
    if (mesh.material.emissiveColor) {
      mesh.material.emissiveColor = new Color3(0.3, 0.25, 0.2);
    }
    if (mesh.material.diffuseColor) {
      mesh.material.diffuseColor = new Color3(0.4, 0.35, 0.3);
    }
  }
}

function spawnContents(
  world: World,
  groups: Groups,
  handles: BabylonHandles,
  resources: Resources,
  signals: SignalBus,
  blockId: EntityId,
  prefabName: string,
  blockPos: { x: number; y: number; z: number },
): void {
  const collider = world.getComponent<{ size: number }>("collider", blockId);
  const halfSize = (collider?.size ?? 1) * 0.5;

  // Spawn above the block
  const spawnY = blockPos.y + halfSize + 0.5;

  const root = world.findByName("SceneRoot") ?? null;
  instantiatePrefab(
    world,
    groups,
    handles,
    resources,
    prefabName,
    { transform: { x: blockPos.x, y: spawnY, z: blockPos.z } },
    root,
  );
}
