// AUTO-GENERATED BY silc — DO NOT EDIT
/** Patrol system for 2D platformer enemy AI patterns. */

import type { BabylonHandles } from "../adapters/babylonScene.ts";
import type { Possession } from "../framework/mode.ts";
import type { Resources } from "../kernel/resources.ts";
import type { SignalBus } from "../kernel/signals.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { EntityId, World } from "../kernel/world.ts";
import { getEntityState, isDespawned } from "./stateMachine.ts";

export type PatrolComp = {
  behavior: "walk_reverse" | "walk_fall" | "stationary" | "follow" | "flee";
  speed?: number;
  bounds?: number;
  onStomp?: string;
  onTouch?: string;
};

type PatrolState = {
  direction: number; // -1 or 1
  spawnX: number;
  dead: boolean;
  stompCooldown: number;
};

const patrolStates = new Map<EntityId, PatrolState>();

/** States that disable movement. */
const DISABLED_STATES = new Set(["dead", "destroyed", "disabled", "stunned", "shell"]);

export function createPatrolSystem(
  world: World,
  handles: BabylonHandles,
  resources: Resources,
  signals: SignalBus,
  possession: Possession,
): GameSystem {
  return {
    name: "patrol",
    order: 23,
    init() {
      for (const [id] of world.query("patrol")) {
        const pos = world.worldPosition(id);
        patrolStates.set(id, {
          direction: 1,
          spawnX: pos.x,
          dead: false,
          stompCooldown: 0,
        });
      }
    },
    fixedUpdate(ctx) {
      const pawnId = possession.pawnId;
      const pawnPos = pawnId ? world.worldPosition(pawnId) : null;
      const pawnVel = pawnId
        ? world.getComponent<{ vx: number; vy: number; vz: number }>("velocity", pawnId)
        : null;

      // Update invincibility timer and visual feedback
      if (pawnId) {
        const invincible = world.getComponent<{ remaining: number }>("invincible", pawnId);
        if (invincible && invincible.remaining > 0) {
          invincible.remaining -= ctx.fixedDt;
          world.addComponent("invincible", pawnId, invincible);
          
          // Blink the sprite during invincibility
          const sprite = world.getComponent<{ visible?: boolean }>("sprite", pawnId);
          if (sprite) {
            // Blink every 0.1 seconds
            const blink = Math.floor(invincible.remaining * 10) % 2 === 0;
            (sprite as { visible?: boolean }).visible = blink;
            world.addComponent("sprite", pawnId, sprite);
          }
        } else if (invincible) {
          // Invincibility ended - ensure sprite is visible
          const sprite = world.getComponent<{ visible?: boolean }>("sprite", pawnId);
          if (sprite) {
            (sprite as { visible?: boolean }).visible = true;
            world.addComponent("sprite", pawnId, sprite);
          }
        }
      }

      for (const [id, raw] of world.query("patrol")) {
        const patrol = raw as PatrolComp;
        const state = patrolStates.get(id);
        if (!state) continue;

        // Check state machine for disabled states
        const entityState = getEntityState(id);
        const isDisabled = state.dead || isDespawned(id) || (entityState && DISABLED_STATES.has(entityState));

        if (isDisabled) {
          // Stop movement when disabled
          const vel = world.getComponent<{ vx: number; vy: number; vz: number }>("velocity", id);
          if (vel) {
            vel.vx = 0;
            world.addComponent("velocity", id, vel);
          }
          continue;
        }

        state.stompCooldown = Math.max(0, state.stompCooldown - ctx.fixedDt);

        const pos = world.worldPosition(id);
        const speed = patrol.speed ?? 2;
        const collider = world.getComponent<{ size: number }>("collider", id);
        const halfSize = (collider?.size ?? 1) * 0.5;

        // Check for stomp (pawn landing on top)
        if (pawnPos && pawnVel && state.stompCooldown <= 0) {
          const pawnCollider = world.getComponent<{ size: number }>("collider", pawnId!);
          const pawnRadius = (pawnCollider?.size ?? 1) * 0.35;

          const horizontalOverlap =
            Math.abs(pawnPos.x - pos.x) < halfSize + pawnRadius &&
            Math.abs(pawnPos.z - pos.z) < halfSize + pawnRadius;

          const pawnFeet = pawnPos.y;
          const enemyTop = pos.y + halfSize;

          const stomped =
            horizontalOverlap &&
            pawnFeet >= enemyTop - 0.2 &&
            pawnFeet <= enemyTop + 0.3 &&
            pawnVel.vy < -1;

          if (stomped) {
            handleStomp(world, handles, signals, id, patrol, state, pawnId!, pawnVel, pos);
            continue;
          }

          // Check for side touch (damage player)
          const sideTouch =
            horizontalOverlap &&
            Math.abs(pawnPos.y - pos.y) < halfSize + 0.5 &&
            !stomped;

          if (sideTouch) {
            // Check if player has invincibility frames
            const invincible = world.getComponent<{ remaining: number }>("invincible", pawnId!);
            if (!invincible || invincible.remaining <= 0) {
              handleTouch(world, signals, id, patrol, pawnId!, pos);
              // Grant invincibility frames after taking damage
              world.addComponent("invincible", pawnId!, { remaining: 1.5 });
            }
            state.stompCooldown = 0.3;
          }
        }

        // Movement based on behavior
        let vx = 0;
        const vel = world.getComponent<{ vx: number; vy: number; vz: number }>("velocity", id) ?? {
          vx: 0,
          vy: 0,
          vz: 0,
        };

        switch (patrol.behavior) {
          case "walk_reverse":
          case "walk_fall":
            vx = state.direction * speed;

            // Check bounds
            if (patrol.bounds != null) {
              if (pos.x > state.spawnX + patrol.bounds) state.direction = -1;
              if (pos.x < state.spawnX - patrol.bounds) state.direction = 1;
            }
            break;

          case "follow":
            if (pawnPos) {
              const dx = pawnPos.x - pos.x;
              if (Math.abs(dx) > 0.5) {
                vx = Math.sign(dx) * speed;
                state.direction = Math.sign(dx);
              }
            }
            break;

          case "flee":
            if (pawnPos) {
              const dx = pawnPos.x - pos.x;
              if (Math.abs(dx) < 10) {
                vx = -Math.sign(dx) * speed;
                state.direction = -Math.sign(dx);
              }
            }
            break;

          case "stationary":
            // Don't move
            break;
        }

        vel.vx = vx;
        vel.vz = 0; // Lock Z for 2D
        world.addComponent("velocity", id, vel);

        // Face movement direction
        if (vx !== 0) {
          // Update sprite flip if present
          const sprite = world.getComponent<{ flipX?: boolean }>("sprite", id);
          if (sprite) {
            sprite.flipX = vx < 0;
            world.addComponent("sprite", id, sprite);
          }
        }
      }
    },
  };
}

function handleStomp(
  world: World,
  handles: BabylonHandles,
  signals: SignalBus,
  enemyId: EntityId,
  patrol: PatrolComp,
  state: PatrolState,
  pawnId: EntityId,
  pawnVel: { vx: number; vy: number; vz: number },
  enemyPos: { x: number; y: number; z: number },
): void {
  // Check if entity has a state machine - if so, let it handle the death
  const hasStateMachine = world.hasComponent("stateMachine", enemyId);

  if (!hasStateMachine) {
    // Legacy behavior: immediately hide
    state.dead = true;
    const node = handles.nodes.get(enemyId);
    if (node) node.setEnabled(false);
  }

  // Bounce pawn up
  pawnVel.vy = 8;
  world.addComponent("velocity", pawnId, pawnVel);

  // Fire signal with position for particles/effects
  if (patrol.onStomp) {
    signals.emit(patrol.onStomp, { enemyId, pawnId, x: enemyPos.x, y: enemyPos.y, z: enemyPos.z });
  }

  signals.emit("enemy_stomped", { enemyId, pawnId, x: enemyPos.x, y: enemyPos.y, z: enemyPos.z });
}

function handleTouch(
  world: World,
  signals: SignalBus,
  enemyId: EntityId,
  patrol: PatrolComp,
  pawnId: EntityId,
  enemyPos: { x: number; y: number; z: number },
): void {
  // Fire signal (game handles damage via signal)
  if (patrol.onTouch) {
    signals.emit(patrol.onTouch, { enemyId, pawnId, x: enemyPos.x, y: enemyPos.y, z: enemyPos.z });
  }

  signals.emit("enemy_touch", { enemyId, pawnId, x: enemyPos.x, y: enemyPos.y, z: enemyPos.z });

  // Knockback: push player away from enemy
  const pawnPos = world.worldPosition(pawnId);
  const pawnVel = world.getComponent<{ vx: number; vy: number; vz: number }>("velocity", pawnId);
  if (pawnVel && pawnPos) {
    const knockbackStrength = 8;
    const knockbackUp = 5;
    const dx = pawnPos.x - enemyPos.x;
    const direction = dx >= 0 ? 1 : -1;
    pawnVel.vx = direction * knockbackStrength;
    pawnVel.vy = knockbackUp;
    world.addComponent("velocity", pawnId, pawnVel);
  }

  // Default: damage player
  const attrs = world.getComponent<Array<{ name: string; value: number; max: number | null }>>(
    "attributes",
    pawnId,
  );
  if (attrs) {
    const health = attrs.find((a) => a.name === "health");
    if (health) {
      health.value = Math.max(0, health.value - 1);
      world.addComponent("attributes", pawnId, attrs);
    }
  }
}

/** Check if an enemy is dead. */
export function isPatrolDead(id: EntityId): boolean {
  return patrolStates.get(id)?.dead ?? false;
}

/** Revive an enemy (for respawning). */
export function revivePatrol(id: EntityId, handles: BabylonHandles): void {
  const state = patrolStates.get(id);
  if (state) {
    state.dead = false;
    const node = handles.nodes.get(id);
    if (node) node.setEnabled(true);
  }
}
