// AUTO-GENERATED BY silc — DO NOT EDIT
/** Patrol system for 2D platformer enemy AI patterns. */

import type { BabylonHandles } from "../adapters/babylonScene.ts";
import type { Possession } from "../framework/mode.ts";
import type { Resources } from "../kernel/resources.ts";
import type { SignalBus } from "../kernel/signals.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { EntityId, World } from "../kernel/world.ts";

export type PatrolComp = {
  behavior: "walk_reverse" | "walk_fall" | "stationary" | "follow" | "flee";
  speed?: number;
  bounds?: number;
  onStomp?: string;
  onTouch?: string;
};

type PatrolState = {
  direction: number; // -1 or 1
  spawnX: number;
  dead: boolean;
  stompCooldown: number;
};

const patrolStates = new Map<EntityId, PatrolState>();

export function createPatrolSystem(
  world: World,
  handles: BabylonHandles,
  resources: Resources,
  signals: SignalBus,
  possession: Possession,
): GameSystem {
  return {
    name: "patrol",
    order: 23,
    init() {
      for (const [id] of world.query("patrol")) {
        const pos = world.worldPosition(id);
        patrolStates.set(id, {
          direction: 1,
          spawnX: pos.x,
          dead: false,
          stompCooldown: 0,
        });
      }
    },
    fixedUpdate(ctx) {
      const pawnId = possession.pawnId;
      const pawnPos = pawnId ? world.worldPosition(pawnId) : null;
      const pawnVel = pawnId
        ? world.getComponent<{ vx: number; vy: number; vz: number }>("velocity", pawnId)
        : null;

      for (const [id, raw] of world.query("patrol")) {
        const patrol = raw as PatrolComp;
        const state = patrolStates.get(id);
        if (!state || state.dead) continue;

        state.stompCooldown = Math.max(0, state.stompCooldown - ctx.fixedDt);

        const pos = world.worldPosition(id);
        const speed = patrol.speed ?? 2;
        const collider = world.getComponent<{ size: number }>("collider", id);
        const halfSize = (collider?.size ?? 1) * 0.5;

        // Check for stomp (pawn landing on top)
        if (pawnPos && pawnVel && state.stompCooldown <= 0) {
          const pawnCollider = world.getComponent<{ size: number }>("collider", pawnId!);
          const pawnRadius = (pawnCollider?.size ?? 1) * 0.35;

          const horizontalOverlap =
            Math.abs(pawnPos.x - pos.x) < halfSize + pawnRadius &&
            Math.abs(pawnPos.z - pos.z) < halfSize + pawnRadius;

          const pawnFeet = pawnPos.y;
          const enemyTop = pos.y + halfSize;

          const stomped =
            horizontalOverlap &&
            pawnFeet >= enemyTop - 0.2 &&
            pawnFeet <= enemyTop + 0.3 &&
            pawnVel.vy < -1;

          if (stomped) {
            handleStomp(world, handles, signals, id, patrol, state, pawnId!, pawnVel);
            continue;
          }

          // Check for side touch (damage player)
          const sideTouch =
            horizontalOverlap &&
            Math.abs(pawnPos.y - pos.y) < halfSize + 0.5 &&
            !stomped;

          if (sideTouch) {
            handleTouch(world, signals, id, patrol, pawnId!);
            state.stompCooldown = 0.5; // Prevent rapid damage
          }
        }

        // Movement based on behavior
        let vx = 0;
        const vel = world.getComponent<{ vx: number; vy: number; vz: number }>("velocity", id) ?? {
          vx: 0,
          vy: 0,
          vz: 0,
        };

        switch (patrol.behavior) {
          case "walk_reverse":
          case "walk_fall":
            vx = state.direction * speed;

            // Check bounds
            if (patrol.bounds != null) {
              if (pos.x > state.spawnX + patrol.bounds) state.direction = -1;
              if (pos.x < state.spawnX - patrol.bounds) state.direction = 1;
            }

            // TODO: Check for walls and edges to reverse direction
            break;

          case "follow":
            if (pawnPos) {
              const dx = pawnPos.x - pos.x;
              if (Math.abs(dx) > 0.5) {
                vx = Math.sign(dx) * speed;
                state.direction = Math.sign(dx);
              }
            }
            break;

          case "flee":
            if (pawnPos) {
              const dx = pawnPos.x - pos.x;
              if (Math.abs(dx) < 10) {
                vx = -Math.sign(dx) * speed;
                state.direction = -Math.sign(dx);
              }
            }
            break;

          case "stationary":
            // Don't move
            break;
        }

        vel.vx = vx;
        vel.vz = 0; // Lock Z for 2D
        world.addComponent("velocity", id, vel);

        // Face movement direction
        if (vx !== 0) {
          // Update sprite flip if present
          const sprite = world.getComponent<{ flipX?: boolean }>("sprite", id);
          if (sprite) {
            sprite.flipX = vx < 0;
            world.addComponent("sprite", id, sprite);
          }
        }
      }
    },
  };
}

function handleStomp(
  world: World,
  handles: BabylonHandles,
  signals: SignalBus,
  enemyId: EntityId,
  patrol: PatrolComp,
  state: PatrolState,
  pawnId: EntityId,
  pawnVel: { vx: number; vy: number; vz: number },
): void {
  state.dead = true;

  // Hide enemy
  const node = handles.nodes.get(enemyId);
  if (node) node.setEnabled(false);

  // Bounce pawn up
  pawnVel.vy = 8;
  world.addComponent("velocity", pawnId, pawnVel);

  // Fire signal
  if (patrol.onStomp) {
    signals.emit(patrol.onStomp, { enemyId, pawnId });
  }

  signals.emit("enemy_stomped", { enemyId, pawnId });
}

function handleTouch(
  world: World,
  signals: SignalBus,
  enemyId: EntityId,
  patrol: PatrolComp,
  pawnId: EntityId,
): void {
  // Fire signal (game handles damage via signal)
  if (patrol.onTouch) {
    signals.emit(patrol.onTouch, { enemyId, pawnId });
  }

  signals.emit("enemy_touch", { enemyId, pawnId });

  // Default: damage player
  const attrs = world.getComponent<Array<{ name: string; value: number; max: number | null }>>(
    "attributes",
    pawnId,
  );
  if (attrs) {
    const health = attrs.find((a) => a.name === "health");
    if (health) {
      health.value = Math.max(0, health.value - 10);
      world.addComponent("attributes", pawnId, attrs);
    }
  }
}

/** Check if an enemy is dead. */
export function isPatrolDead(id: EntityId): boolean {
  return patrolStates.get(id)?.dead ?? false;
}

/** Revive an enemy (for respawning). */
export function revivePatrol(id: EntityId, handles: BabylonHandles): void {
  const state = patrolStates.get(id);
  if (state) {
    state.dead = false;
    const node = handles.nodes.get(id);
    if (node) node.setEnabled(true);
  }
}
