// AUTO-GENERATED BY silc — DO NOT EDIT
/** Sky system for procedural clouds and star fields. */

import {
  DynamicTexture,
  Mesh,
  MeshBuilder,
  ParticleSystem,
  StandardMaterial,
  Texture,
  Vector3,
} from "@babylonjs/core";
import type { BabylonHandles } from "../adapters/babylonScene.ts";
import type { CloudsDef, StarsDef } from "../manifest.ts";
import type { Resources } from "../kernel/resources.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { World } from "../kernel/world.ts";

type CloudState = {
  mesh: Mesh;
  velocity: Vector3;
  basePosition: Vector3;
  spread: number;
};

type StarState = {
  mesh: Mesh;
  baseAlpha: number;
  twinkleOffset: number;
};

const cloudStates: CloudState[] = [];
const starStates: StarState[] = [];

export function createSkySystem(
  world: World,
  handles: BabylonHandles,
  resources: Resources,
): GameSystem {
  return {
    name: "sky",
    order: 3,
    async init() {
      const env = resources.manifest.environment;
      if (!env) return;

      // Create cloud layers
      for (const cloudDef of env.clouds ?? []) {
        createClouds(handles, cloudDef);
      }

      // Create star layers
      for (const starDef of env.stars ?? []) {
        createStars(handles, starDef);
      }
    },
    update(ctx) {
      const camera = handles.scene.activeCamera;
      const cameraPos = camera?.position ?? Vector3.Zero();

      // Animate clouds
      for (const cloud of cloudStates) {
        // Drift
        cloud.mesh.position.x += cloud.velocity.x * ctx.dt;
        cloud.mesh.position.z += cloud.velocity.z * ctx.dt;

        // Wrap around when drifting too far from center
        const dx = cloud.mesh.position.x - cameraPos.x;
        const dz = cloud.mesh.position.z - cameraPos.z;
        if (Math.abs(dx) > cloud.spread) {
          cloud.mesh.position.x = cameraPos.x - Math.sign(dx) * cloud.spread;
        }
        if (Math.abs(dz) > cloud.spread) {
          cloud.mesh.position.z = cameraPos.z - Math.sign(dz) * cloud.spread;
        }
      }

      // Animate stars (twinkle)
      for (const star of starStates) {
        if (star.baseAlpha < 1) {
          const twinkle = 0.3 * Math.sin(ctx.time * 2.5 + star.twinkleOffset);
          star.mesh.visibility = star.baseAlpha + twinkle * 0.2;
        }
        // Keep star dome centered on camera
        star.mesh.position.x = cameraPos.x;
        star.mesh.position.z = cameraPos.z;
      }
    },
  };
}

function createCloudTexture(scene: import("@babylonjs/core").Scene, color: string): DynamicTexture {
  const size = 256;
  const tex = new DynamicTexture("cloudTex", { width: size, height: size }, scene, false);
  const ctx = tex.getContext();

  // Parse color
  const hex = color.replace("#", "");
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);

  // Draw soft radial gradient cloud shape
  ctx.clearRect(0, 0, size, size);

  const cx = size / 2;
  const cy = size / 2;

  // Multiple overlapping circles for fluffy appearance
  const blobs = [
    { x: cx, y: cy, r: size * 0.35 },
    { x: cx - size * 0.2, y: cy - size * 0.05, r: size * 0.25 },
    { x: cx + size * 0.2, y: cy + size * 0.05, r: size * 0.28 },
    { x: cx - size * 0.1, y: cy + size * 0.12, r: size * 0.22 },
    { x: cx + size * 0.1, y: cy - size * 0.1, r: size * 0.2 },
  ];

  for (const blob of blobs) {
    const gradient = ctx.createRadialGradient(blob.x, blob.y, 0, blob.x, blob.y, blob.r);
    gradient.addColorStop(0, `rgba(${r}, ${g}, ${b}, 0.7)`);
    gradient.addColorStop(0.5, `rgba(${r}, ${g}, ${b}, 0.3)`);
    gradient.addColorStop(1, `rgba(${r}, ${g}, ${b}, 0)`);
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, size, size);
  }

  tex.update();
  tex.hasAlpha = true;
  return tex;
}

function createClouds(handles: BabylonHandles, def: CloudsDef): void {
  const count = def.count ?? 12;
  const altitude = def.altitude ?? 60;
  const spread = def.spread ?? 150;
  const speed = def.speed ?? 1.0;
  const scale = def.scale ?? 1.0;
  const color = def.color ?? "#ffffff";
  const opacity = def.opacity ?? 0.8;

  const cloudTex = createCloudTexture(handles.scene, color);

  for (let i = 0; i < count; i++) {
    const cloudScale = (8 + Math.random() * 40) * scale;
    const heightScale = cloudScale * (0.2 + Math.random() * 0.5);

    const mesh = MeshBuilder.CreatePlane(
      `cloud_${i}`,
      { width: cloudScale, height: heightScale, sideOrientation: Mesh.DOUBLESIDE },
      handles.scene,
    );

    // Random position within spread
    const x = (Math.random() - 0.5) * spread * 2;
    const y = altitude + (Math.random() - 0.5) * 20;
    const z = (Math.random() - 0.5) * spread * 2;
    mesh.position.set(x, y, z);

    // Face upward slightly for 3D look, but mostly billboard
    mesh.billboardMode = Mesh.BILLBOARDMODE_Y;
    mesh.isPickable = false;
    mesh.renderingGroupId = 0;

    // Material
    const mat = new StandardMaterial(`cloud_mat_${i}`, handles.scene);
    mat.diffuseTexture = cloudTex;
    mat.useAlphaFromDiffuseTexture = true;
    mat.transparencyMode = 2; // ALPHA_BLEND
    mat.disableLighting = true;
    mat.emissiveColor.set(1, 1, 1);
    mat.backFaceCulling = false;
    mat.fogEnabled = false; // Clouds should not be affected by fog
    mat.alpha = opacity;
    mesh.material = mat;

    // Random drift velocity
    const vx = (Math.random() - 0.5) * 2 * speed;
    const vz = (Math.random() - 0.5) * 2 * speed;

    cloudStates.push({
      mesh,
      velocity: new Vector3(vx, 0, vz),
      basePosition: new Vector3(x, y, z),
      spread,
    });
  }
}

function createStars(handles: BabylonHandles, def: StarsDef): void {
  const count = def.count ?? 100;
  const altitude = def.altitude ?? 200;
  const size = def.size ?? 0.5;
  const color = def.color ?? "#ffffff";
  const opacity = def.opacity ?? 0.7;
  const twinkle = def.twinkle ?? false;

  // Parse color
  const hex = color.replace("#", "");
  const r = parseInt(hex.substring(0, 2), 16) / 255;
  const g = parseInt(hex.substring(2, 4), 16) / 255;
  const b = parseInt(hex.substring(4, 6), 16) / 255;

  for (let i = 0; i < count; i++) {
    // Distribute on upper hemisphere
    const theta = Math.random() * Math.PI * 2;
    const phi = Math.random() * Math.PI * 0.45; // Upper hemisphere only
    const x = altitude * Math.sin(phi) * Math.cos(theta);
    const y = altitude * Math.cos(phi);
    const z = altitude * Math.sin(phi) * Math.sin(theta);

    // Vary brightness per star
    const brightness = 0.3 + Math.random() * 0.7;
    const starSize = size * (0.15 + Math.random() * 2.5);

    const starMesh = MeshBuilder.CreatePlane(
      `star_${i}`,
      { size: starSize },
      handles.scene,
    );
    starMesh.position.set(x, y, z);
    starMesh.billboardMode = Mesh.BILLBOARDMODE_ALL;
    starMesh.isPickable = false;
    starMesh.renderingGroupId = 0;

    // Each star gets its own material for individual brightness
    const mat = new StandardMaterial(`star_mat_${i}`, handles.scene);
    mat.disableLighting = true;
    mat.emissiveColor.set(r * brightness, g * brightness, b * brightness);
    mat.fogEnabled = false; // Stars should not be affected by fog
    mat.backFaceCulling = false;
    starMesh.material = mat;
    starMesh.visibility = opacity * brightness;

    if (twinkle) {
      starStates.push({
        mesh: starMesh,
        baseAlpha: opacity * brightness,
        twinkleOffset: Math.random() * Math.PI * 2,
      });
    }
  }
}
