// AUTO-GENERATED BY silc — DO NOT EDIT
/** Sprite rendering system for 2D billboard sprites from texture atlases. */

import { Mesh, MeshBuilder, StandardMaterial, Texture, VertexBuffer } from "@babylonjs/core";
import type { BabylonHandles } from "../adapters/babylonScene.ts";
import type { Resources } from "../kernel/resources.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { EntityId, World } from "../kernel/world.ts";

export type SpriteComp = {
  atlas: string;
  frame?: string;
  width?: number;
  height?: number;
  animation?: string;
  flipX?: boolean;
  billboard?: boolean;
};

export type AnimationDef = {
  frames: number[];
  frameDuration: number;
  loop: boolean;
};

export type AtlasData = {
  frameWidth: number;
  frameHeight: number;
  columns: number;
  rows: number;
  animations: Record<string, AnimationDef>;
};

const DEFAULT_ATLAS: AtlasData = {
  frameWidth: 32,
  frameHeight: 32,
  columns: 4,
  rows: 4,
  animations: {
    idle: { frames: [0], frameDuration: 1, loop: true },
    walk: { frames: [1, 2, 3, 2], frameDuration: 0.15, loop: true },
    jump: { frames: [4], frameDuration: 1, loop: false },
    fall: { frames: [5], frameDuration: 1, loop: false },
  },
};

type SpriteState = {
  mesh: Mesh;
  material: StandardMaterial;
  texture: Texture;
  currentAnimation: string;
  currentFrameIndex: number;
  animationTime: number;
  atlasData: AtlasData;
};

const spriteStates = new Map<EntityId, SpriteState>();
const atlasCache = new Map<string, AtlasData>();

export function createSpriteSystem(
  world: World,
  handles: BabylonHandles,
  resources: Resources,
): GameSystem {
  return {
    name: "sprite",
    order: 25,
    async init() {
      for (const [id, raw] of world.query("sprite")) {
        const sprite = raw as SpriteComp;
        await createSpriteMesh(world, handles, resources, id, sprite);
      }
    },
    update(ctx) {
      for (const [id, raw] of world.query("sprite")) {
        const sprite = raw as SpriteComp;
        const state = spriteStates.get(id);
        if (!state) continue;

        // Handle visibility (for invincibility blinking, etc.)
        const isVisible = (sprite as { visible?: boolean }).visible !== false;
        state.mesh.setEnabled(isVisible);
        if (!isVisible) continue;

        // Update position from transform
        const pos = world.worldPosition(id);
        const spriteHeight = sprite.height ?? 1;
        // Position sprite so its bottom is at the entity's Y position
        const spriteY = pos.y + spriteHeight * 0.5;
        // Offset Z toward camera to render in front of ground/platforms
        state.mesh.position.set(pos.x, spriteY, pos.z + 1.5);

        // Billboard: face camera (for side-scroll, we want to face +Z)
        const cameraMode = resources.manifest.camera?.mode;
        if (cameraMode === "side_scroll") {
          state.mesh.rotation.y = 0;
        } else if (sprite.billboard !== false) {
          const cam = handles.scene.activeCamera;
          if (cam) {
            state.mesh.lookAt(cam.position);
            state.mesh.rotation.x = 0;
            state.mesh.rotation.z = 0;
          }
        }

        // Flip X based on direction
        state.mesh.scaling.x = sprite.flipX ? -1 : 1;

        // Animation frame cycling
        const animName = sprite.animation ?? "idle";
        if (animName !== state.currentAnimation) {
          state.currentAnimation = animName;
          state.currentFrameIndex = 0;
          state.animationTime = 0;
        }

        const anim = state.atlasData.animations[animName];
        if (anim && anim.frames.length > 0) {
          state.animationTime += ctx.dt;
          if (state.animationTime >= anim.frameDuration) {
            state.animationTime -= anim.frameDuration;
            state.currentFrameIndex++;
            if (state.currentFrameIndex >= anim.frames.length) {
              state.currentFrameIndex = anim.loop ? 0 : anim.frames.length - 1;
            }
            const frameIndex = anim.frames[state.currentFrameIndex];
            updateSpriteUVs(state, frameIndex);
          }
        }
      }
    },
  };
}

async function loadAtlasData(atlasName: string): Promise<AtlasData> {
  if (atlasCache.has(atlasName)) {
    return atlasCache.get(atlasName)!;
  }

  // Try baked/sprites/ first (generated assets), then public/assets/ (manual/exported)
  const paths = [
    `/baked/sprites/${atlasName}.json`,
    `/assets/${atlasName}.json`,
  ];

  for (const path of paths) {
    try {
      const resp = await fetch(path);
      if (resp.ok) {
        const raw = await resp.json();
        // Normalize animation format (bake worker uses 'duration', runtime expects 'frameDuration')
        const data: AtlasData = {
          frameWidth: raw.frameWidth ?? 32,
          frameHeight: raw.frameHeight ?? 32,
          columns: raw.columns ?? 4,
          rows: raw.rows ?? 4,
          animations: {},
        };
        for (const [name, anim] of Object.entries(raw.animations ?? {})) {
          const a = anim as { frames?: number[]; duration?: number; frameDuration?: number; loop?: boolean };
          data.animations[name] = {
            frames: a.frames ?? [0],
            frameDuration: a.frameDuration ?? a.duration ?? 0.15,
            loop: a.loop ?? true,
          };
        }
        atlasCache.set(atlasName, data);
        return data;
      }
    } catch {
      // Try next path
    }
  }

  atlasCache.set(atlasName, DEFAULT_ATLAS);
  return DEFAULT_ATLAS;
}

async function createSpriteMesh(
  world: World,
  handles: BabylonHandles,
  resources: Resources,
  id: EntityId,
  sprite: SpriteComp,
): Promise<void> {
  const width = sprite.width ?? 1;
  const height = sprite.height ?? 1;

  // Load atlas data
  const atlasData = await loadAtlasData(sprite.atlas);

  // Create a plane mesh for the sprite
  const mesh = MeshBuilder.CreatePlane(
    `sprite_${id}`,
    { width, height, sideOrientation: Mesh.DOUBLESIDE },
    handles.scene,
  );

  // Create material with atlas texture
  const material = new StandardMaterial(`sprite_mat_${id}`, handles.scene);
  material.backFaceCulling = false;
  material.disableLighting = true;
  material.emissiveColor.set(1, 1, 1);

  // Load atlas texture - try baked/sprites/ first, then public/assets/
  const atlasPath = await resolveAtlasTexturePath(sprite.atlas);
  const texture = new Texture(atlasPath, handles.scene, false, true, Texture.NEAREST_SAMPLINGMODE);
  texture.hasAlpha = true;
  texture.wrapU = Texture.CLAMP_ADDRESSMODE;
  texture.wrapV = Texture.CLAMP_ADDRESSMODE;
  material.diffuseTexture = texture;
  material.useAlphaFromDiffuseTexture = true;
  material.transparencyMode = 2; // ALPHA_TEST

  mesh.material = material;
  
  // Ensure sprites render on top of other geometry
  mesh.renderingGroupId = 1;

  // Position at entity location (offset Z toward camera for proper rendering)
  // Ground extends from z=-1 to z=+1, so sprites need to be at z > 1
  const pos = world.worldPosition(id);
  mesh.position.set(pos.x, pos.y + height * 0.5, pos.z + 1.5);

  // Store state
  const state: SpriteState = {
    mesh,
    material,
    texture,
    currentAnimation: sprite.animation ?? "idle",
    currentFrameIndex: 0,
    animationTime: 0,
    atlasData,
  };
  spriteStates.set(id, state);

  // Set initial frame UVs
  const initialAnim = atlasData.animations[state.currentAnimation];
  if (initialAnim && initialAnim.frames.length > 0) {
    updateSpriteUVs(state, initialAnim.frames[0]);
  }

  // Register with handles for cleanup
  handles.nodes.set(id, mesh);
}

const texturePathCache = new Map<string, string>();

async function resolveAtlasTexturePath(atlasName: string): Promise<string> {
  if (texturePathCache.has(atlasName)) {
    return texturePathCache.get(atlasName)!;
  }

  // Try baked/sprites/ first (generated assets), then public/assets/ (manual/exported)
  const paths = [
    `/baked/sprites/${atlasName}.png`,
    `/assets/${atlasName}.png`,
  ];

  for (const path of paths) {
    try {
      const resp = await fetch(path, { method: "HEAD" });
      if (resp.ok) {
        texturePathCache.set(atlasName, path);
        return path;
      }
    } catch {
      // Try next path
    }
  }

  // Default to assets path
  const fallback = `/assets/${atlasName}.png`;
  texturePathCache.set(atlasName, fallback);
  return fallback;
}

function updateSpriteUVs(state: SpriteState, frameIndex: number): void {
  const { atlasData, mesh } = state;
  const { columns, rows } = atlasData;

  // Calculate UV coordinates for this frame
  const col = frameIndex % columns;
  const row = Math.floor(frameIndex / columns);

  const uMin = col / columns;
  const uMax = (col + 1) / columns;
  const vMin = 1 - (row + 1) / rows;
  const vMax = 1 - row / rows;

  // Update mesh UVs
  // Plane UVs are: bottom-left, bottom-right, top-right, top-left
  const uvs = new Float32Array([
    uMin, vMin,  // bottom-left
    uMax, vMin,  // bottom-right
    uMax, vMax,  // top-right
    uMin, vMax,  // top-left
  ]);

  mesh.setVerticesData(VertexBuffer.UVKind, uvs, true);
}

/** Update sprite animation state. */
export function setSpriteAnimation(world: World, id: EntityId, animation: string): void {
  const sprite = world.getComponent<SpriteComp>("sprite", id);
  if (sprite && sprite.animation !== animation) {
    sprite.animation = animation;
    world.addComponent("sprite", id, sprite);
  }
}

/** Update sprite flip state. */
export function setSpriteFlip(world: World, id: EntityId, flipX: boolean): void {
  const sprite = world.getComponent<SpriteComp>("sprite", id);
  if (sprite) {
    sprite.flipX = flipX;
    world.addComponent("sprite", id, sprite);
  }
}
