// AUTO-GENERATED BY silc — DO NOT EDIT
/** Tilemap rendering system for tile-based level geometry. */

import { Mesh, MeshBuilder, StandardMaterial, Texture, Vector3 } from "@babylonjs/core";
import type { BabylonHandles } from "../adapters/babylonScene.ts";
import type { Resources } from "../kernel/resources.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { World } from "../kernel/world.ts";

export type TilemapComp = {
  asset: string;
  tileset: string;
  tileSize?: number;
  collisionLayer?: string;
};

export type TilemapData = {
  width: number;
  height: number;
  layers: TilemapLayer[];
  tilesets: TilesetRef[];
};

export type TilemapLayer = {
  name: string;
  data: number[];
  width: number;
  height: number;
  visible?: boolean;
};

export type TilesetRef = {
  firstgid: number;
  name: string;
  tilewidth: number;
  tileheight: number;
  imagewidth: number;
  imageheight: number;
  columns: number;
  tilecount: number;
  properties?: Record<string, TileProperty[]>;
};

export type TileProperty = {
  name: string;
  type: string;
  value: unknown;
};

type TilemapState = {
  meshes: Mesh[];
  colliders: Array<{ minX: number; maxX: number; minY: number; maxY: number }>;
};

const tilemapStates = new Map<string, TilemapState>();

export function createTilemapSystem(
  world: World,
  handles: BabylonHandles,
  resources: Resources,
): GameSystem {
  return {
    name: "tilemap",
    order: 5,
    async init() {
      for (const [id, raw] of world.query("tilemap")) {
        const tilemap = raw as TilemapComp;
        await loadTilemap(world, handles, resources, tilemap);
      }
    },
  };
}

async function loadTilemap(
  world: World,
  handles: BabylonHandles,
  resources: Resources,
  tilemap: TilemapComp,
): Promise<void> {
  const tileSize = tilemap.tileSize ?? 1;

  // Load tilemap data
  let data: TilemapData;
  try {
    const resp = await fetch(`/assets/${tilemap.asset}.json`);
    data = await resp.json();
  } catch (e) {
    console.warn(`Failed to load tilemap ${tilemap.asset}:`, e);
    return;
  }

  // Load tileset texture
  const tilesetPath = `/assets/${tilemap.tileset}.png`;
  const texture = new Texture(tilesetPath, handles.scene);
  texture.hasAlpha = true;

  const meshes: Mesh[] = [];
  const colliders: TilemapState["colliders"] = [];

  // Get tileset info
  const tilesetInfo = data.tilesets[0];
  if (!tilesetInfo) return;

  const cols = tilesetInfo.columns;
  const tileW = tilesetInfo.tilewidth;
  const tileH = tilesetInfo.tileheight;
  const imgW = tilesetInfo.imagewidth;
  const imgH = tilesetInfo.imageheight;

  // Process each layer
  for (const layer of data.layers) {
    if (layer.visible === false) continue;

    const isCollisionLayer = layer.name === (tilemap.collisionLayer ?? "collision");

    for (let y = 0; y < layer.height; y++) {
      for (let x = 0; x < layer.width; x++) {
        const idx = y * layer.width + x;
        const gid = layer.data[idx];
        if (gid === 0) continue; // Empty tile

        const localId = gid - tilesetInfo.firstgid;
        const tileX = localId % cols;
        const tileY = Math.floor(localId / cols);

        // World position (Y is up, tilemap Y is down)
        const worldX = x * tileSize;
        const worldY = (layer.height - 1 - y) * tileSize;

        // Create tile mesh
        const mesh = MeshBuilder.CreatePlane(
          `tile_${layer.name}_${x}_${y}`,
          { width: tileSize, height: tileSize },
          handles.scene,
        );

        // Position tile
        mesh.position.set(worldX + tileSize * 0.5, worldY + tileSize * 0.5, 0);
        mesh.rotation.y = Math.PI; // Face camera

        // Create material with UV for this tile
        const material = new StandardMaterial(`tile_mat_${x}_${y}`, handles.scene);
        material.backFaceCulling = false;
        material.disableLighting = true;
        material.emissiveColor.set(1, 1, 1);
        material.diffuseTexture = texture.clone();
        material.useAlphaFromDiffuseTexture = true;
        material.transparencyMode = 2;

        // Set UV coordinates for this tile
        const uMin = (tileX * tileW) / imgW;
        const uMax = ((tileX + 1) * tileW) / imgW;
        const vMin = 1 - ((tileY + 1) * tileH) / imgH;
        const vMax = 1 - (tileY * tileH) / imgH;

        // Apply UV scaling
        if (material.diffuseTexture) {
          material.diffuseTexture.uOffset = uMin;
          material.diffuseTexture.vOffset = vMin;
          material.diffuseTexture.uScale = uMax - uMin;
          material.diffuseTexture.vScale = vMax - vMin;
        }

        mesh.material = material;
        meshes.push(mesh);

        // Add collision AABB for collision layer
        if (isCollisionLayer) {
          colliders.push({
            minX: worldX,
            maxX: worldX + tileSize,
            minY: worldY,
            maxY: worldY + tileSize,
          });
        }
      }
    }
  }

  tilemapStates.set(tilemap.asset, { meshes, colliders });
}

/** Get collision AABBs for a tilemap. */
export function getTilemapColliders(
  asset: string,
): Array<{ minX: number; maxX: number; minY: number; maxY: number }> {
  return tilemapStates.get(asset)?.colliders ?? [];
}
