// AUTO-GENERATED BY silc — DO NOT EDIT
import type { BabylonHandles } from "../adapters/babylonScene.ts";
import { syncTransformNode } from "../adapters/babylonScene.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { World } from "../kernel/world.ts";

export function createTransformSyncSystem(world: World, handles: BabylonHandles): GameSystem {
  return {
    name: "transformSync",
    order: 50,
    update() {
      for (const id of world.entities()) {
        const pos = world.worldPosition(id);
        const t = world.transform(id);
        const name = world.nameOf(id) ?? `e${id}`;
        syncTransformNode(handles, id, name, pos, t.yaw);
      }
    },
  };
}
