// AUTO-GENERATED BY silc — DO NOT EDIT
/** Warp system for teleport triggers (pipes, doors, etc.). */

import type { BabylonHandles } from "../adapters/babylonScene.ts";
import type { Possession } from "../framework/mode.ts";
import type { Resources } from "../kernel/resources.ts";
import type { SignalBus } from "../kernel/signals.ts";
import type { GameSystem } from "../kernel/systems.ts";
import type { EntityId, World } from "../kernel/world.ts";

export type WarpComp = {
  target: string;
  direction?: "down" | "up" | "left" | "right";
  onWarp?: string;
};

export type LevelEndComp = {
  onComplete?: string;
  nextLevel?: string;
};

type WarpState = {
  cooldown: number;
};

const warpStates = new Map<EntityId, WarpState>();

export function createWarpSystem(
  world: World,
  handles: BabylonHandles,
  resources: Resources,
  signals: SignalBus,
  possession: Possession,
): GameSystem {
  return {
    name: "warp",
    order: 35,
    init() {
      for (const [id] of world.query("warp")) {
        warpStates.set(id, { cooldown: 0 });
      }
    },
    fixedUpdate(ctx) {
      const pawnId = possession.pawnId;
      if (pawnId == null) return;

      const pawnPos = world.worldPosition(pawnId);
      const pawnCollider = world.getComponent<{ size: number }>("collider", pawnId);
      const pawnRadius = (pawnCollider?.size ?? 1) * 0.5;

      // Check warps
      for (const [id, raw] of world.query("warp")) {
        const warp = raw as WarpComp;
        const state = warpStates.get(id);
        if (!state) continue;

        if (state.cooldown > 0) {
          state.cooldown -= ctx.fixedDt;
          continue;
        }

        const pos = world.worldPosition(id);
        const collider = world.getComponent<{ size: number }>("collider", id);
        const radius = (collider?.size ?? 1) * 0.5;

        // Check overlap
        const dx = pawnPos.x - pos.x;
        const dy = pawnPos.y - pos.y;
        const dz = pawnPos.z - pos.z;
        const distSq = dx * dx + dy * dy + dz * dz;
        const touchDist = pawnRadius + radius;

        if (distSq < touchDist * touchDist) {
          // Check direction requirement
          if (warp.direction && !checkDirection(resources, warp.direction)) {
            continue;
          }

          // Teleport!
          const targetPos = resolveTarget(world, warp.target);
          if (targetPos) {
            world.setTransform(pawnId, { x: targetPos.x, y: targetPos.y, z: targetPos.z });
            state.cooldown = 1.0; // Prevent immediate re-warp

            // Fire signal
            if (warp.onWarp) {
              signals.emit(warp.onWarp, { warpId: id, target: warp.target });
            }
            signals.emit("warped", { warpId: id, target: warp.target });
          }
        }
      }

      // Check level ends
      for (const [id, raw] of world.query("level_end")) {
        const levelEnd = raw as LevelEndComp;
        const pos = world.worldPosition(id);
        const collider = world.getComponent<{ size: number }>("collider", id);
        const radius = (collider?.size ?? 1) * 0.5;

        const dx = pawnPos.x - pos.x;
        const dy = pawnPos.y - pos.y;
        const dz = pawnPos.z - pos.z;
        const distSq = dx * dx + dy * dy + dz * dz;
        const touchDist = pawnRadius + radius;

        if (distSq < touchDist * touchDist) {
          // Level complete!
          if (levelEnd.onComplete) {
            signals.emit(levelEnd.onComplete, { levelEndId: id });
          }
          signals.emit("level_complete", {
            levelEndId: id,
            nextLevel: levelEnd.nextLevel,
          });

          // TODO: Load next level if specified
        }
      }
    },
  };
}

function checkDirection(resources: Resources, direction: string): boolean {
  const input = resources.input;
  switch (direction) {
    case "down":
      return input.keys.has("KeyS") || input.keys.has("ArrowDown");
    case "up":
      return input.keys.has("KeyW") || input.keys.has("ArrowUp");
    case "left":
      return input.keys.has("KeyA") || input.keys.has("ArrowLeft");
    case "right":
      return input.keys.has("KeyD") || input.keys.has("ArrowRight");
    default:
      return true;
  }
}

function resolveTarget(
  world: World,
  target: string,
): { x: number; y: number; z: number } | null {
  // Try to find entity by name
  const entity = world.findByName(target);
  if (entity != null) {
    return world.worldPosition(entity);
  }

  // Try to parse as coordinates "x,y,z"
  const parts = target.split(",").map((s) => parseFloat(s.trim()));
  if (parts.length >= 2 && parts.every((n) => !isNaN(n))) {
    return { x: parts[0], y: parts[1], z: parts[2] ?? 0 };
  }

  return null;
}
