// AUTO-GENERATED BY silc — DO NOT EDIT
/** Boot: World.fromManifest → systems → tick. */

import { createBabylonScene } from "./adapters/babylonScene.ts";
import type { KitDef, MaterialDef } from "./adapters/kitBuilder.ts";
import { createAbilitySystem } from "./framework/ability.ts";
import { createFrameworkSystems, type Possession } from "./framework/mode.ts";
import { Groups } from "./kernel/groups.ts";
import { buildResources } from "./kernel/resources.ts";
import { SignalBus } from "./kernel/signals.ts";
import { SystemSchedule, Ticker } from "./kernel/systems.ts";
import { World } from "./kernel/world.ts";
import type { GameBake, GameManifest } from "./manifest.ts";
import { DEFAULT_MANIFEST } from "./manifest.ts";
import { createAiSystem } from "./systems/ai.ts";
import { createCameraSystem } from "./systems/camera.ts";
import { createCognitionSystem } from "./systems/cognition.ts";
import { createCollectibleSystem } from "./systems/collectible.ts";
import { createHudSystem } from "./systems/hud.ts";
import { createInteractableSystem } from "./systems/interactable.ts";
import { createOverlaySystem } from "./systems/overlay.ts";
import { createPatrolSystem } from "./systems/patrol.ts";
import { createPhysicsSystem } from "./systems/physics.ts";
import { createPostSystem } from "./systems/post.ts";
import { createSpriteSystem } from "./systems/sprite.ts";
import { createTilemapSystem } from "./systems/tilemap.ts";
import { createTransformSyncSystem } from "./systems/transformSync.ts";
import { createWarpSystem } from "./systems/warp.ts";
import {
  createProjectileSystem,
  createWeaponSystem,
  type CombatState,
} from "./systems/weapons.ts";

async function bootGame(canvas: HTMLCanvasElement): Promise<() => void> {
  const [manifestRes, bakeRes, kitRes, matsRes] = await Promise.all([
    fetch("/manifest.json"),
    fetch("/baked/game_bake.json"),
    fetch("/baked/kit.json"),
    fetch("/baked/materials.json"),
  ]);
  const manifest = (manifestRes.ok
    ? await manifestRes.json()
    : DEFAULT_MANIFEST) as GameManifest;
  const bake = (bakeRes.ok ? await bakeRes.json() : null) as GameBake | null;
  const kit = (kitRes.ok ? await kitRes.json() : bake && (bake as { kit?: KitDef }).kit) as
    | KitDef
    | null;
  const kitMaterials = (matsRes.ok
    ? await matsRes.json()
    : bake?.materials ?? {}) as Record<string, MaterialDef>;

  const bakeData: GameBake = bake ?? {
    engine: "cpython-bake-v1",
    data: manifest.data ?? {},
    assets: manifest.assets ?? {},
    materials: manifest.materials ?? {},
    zones: manifest.zones ?? [],
    weapons: manifest.weapons ?? {},
    encounters: manifest.encounters ?? [],
    objectives: manifest.objectives ?? [],
    environment: manifest.environment,
    navHints: { navmeshAssets: [], agents: [] },
    mindRefs: [],
    prefabs: manifest.prefabs ?? {},
    colliders: [],
    spawns: [],
    signals: manifest.signals ?? [],
    mode: manifest.mode,
    attributes: {},
  };

  const env = manifest.environment ?? bakeData.environment;
  const firstPerson = (manifest.camera?.mode ?? "third_person") === "first_person";
  const handles = await createBabylonScene(canvas, {
    firstPerson,
    fogDensity: env?.fogDensity ?? undefined,
    fogColor: env?.fogColor ?? undefined,
    skyColor: env?.skyColor ?? undefined,
    exposure: env?.exposure ?? undefined,
    shadows: manifest.shadow?.enabled !== false,
  });

  const world = new World();
  const groups = new Groups();
  const signals = new SignalBus();
  const resources = buildResources(manifest, bakeData, canvas, kit, kitMaterials);
  const possession: Possession = {
    modeId: "default",
    pawnId: null,
    yaw: 0,
    pitch: firstPerson ? 0 : 1.1,
    impulse: 0,
    lastAbility: null,
    score: 0,
  };
  const combat: CombatState = {
    weapons: [],
    active: 0,
    health: 100,
    maxHealth: 100,
    score: 0,
    lastHit: null,
  };

  const schedule = new SystemSchedule();
  for (const s of createFrameworkSystems(world, groups, signals, handles, resources, possession)) {
    schedule.add(s);
  }
  // Platformer systems (order matters: tilemap first for collision data)
  schedule.add(createTilemapSystem(world, handles, resources));
  schedule.add(createSpriteSystem(world, handles, resources));
  schedule.add(createPhysicsSystem(world));
  schedule.add(createPatrolSystem(world, handles, resources, signals, possession));
  schedule.add(createCollectibleSystem(world, handles, resources, signals, possession));
  schedule.add(createInteractableSystem(world, groups, handles, resources, signals, possession));
  schedule.add(createWarpSystem(world, handles, resources, signals, possession));
  // FPS systems
  schedule.add(createAiSystem(world, handles, resources, possession, combat));
  schedule.add(createWeaponSystem(world, signals, handles, resources, possession, combat));
  schedule.add(createProjectileSystem(world, handles, combat));
  schedule.add(createCognitionSystem(world, resources, possession, combat));
  schedule.add(createAbilitySystem(world, signals, handles, resources, possession));
  schedule.add(createTransformSyncSystem(world, handles));
  schedule.add(createCameraSystem(world, handles, resources, possession));
  schedule.add(createPostSystem(handles, resources));
  schedule.add(createHudSystem(world, resources, possession, combat));
  schedule.add(createOverlaySystem(world, resources, possession));

  await schedule.initAll();
  handles.engine.resize();

  if (possession.pawnId == null) {
    console.warn("[silc-game] no pawn possessed — camera stays at origin");
  }
  console.info(
    "[silc-game] boot",
    manifest.title,
    "entities=",
    world.entities().length,
    "meshes=",
    handles.scene.meshes.length,
    "pawn=",
    possession.pawnId,
    "fp=",
    firstPerson,
    "kit=",
    kit ? Object.keys(kit.pieces || {}).length : 0,
  );

  // Inspection handle for the F1 overlay and headless smoke tests.
  (globalThis as unknown as { __silc?: unknown }).__silc = {
    world,
    handles,
    resources,
    possession,
    combat,
  };

  const ticker = new Ticker(schedule, manifest.targetFps || 90);
  handles.engine.runRenderLoop(() => {
    handles.scene.render();
  });
  ticker.start();

  return () => {
    ticker.stop();
    handles.engine.stopRenderLoop();
    schedule.disposeAll();
    resources.input.dispose();
    void resources.run.end("quit");
    handles.dispose();
  };
}

function setStatus(text: string, pct?: number): void {
  const status = document.getElementById("loading-status");
  const fill = document.getElementById("loading-bar-fill");
  if (status) status.textContent = text;
  if (fill && pct != null) fill.style.width = `${Math.round(pct * 100)}%`;
}

async function main(): Promise<void> {
  const noGpu = document.getElementById("no-webgpu");
  const loading = document.getElementById("loading");
  if (!("gpu" in navigator)) {
    if (noGpu) (noGpu as HTMLElement).style.display = "flex";
    if (loading) loading.classList.add("hidden");
    return;
  }
  const canvas = document.getElementById("game-root") as HTMLCanvasElement | null;
  if (!canvas) throw new Error("missing #game-root canvas");
  setStatus("Starting WebGPU…", 0.1);
  try {
    await bootGame(canvas);
    setStatus("Ready", 1);
    window.setTimeout(() => loading?.classList.add("hidden"), 200);
  } catch (err) {
    setStatus(err instanceof Error ? err.message : String(err), 0);
    throw err;
  }
}

void main();
