// AUTO-GENERATED BY silc — DO NOT EDIT
import {
  ArcRotateCamera,
  CascadedShadowGenerator,
  Color3,
  Color4,
  DirectionalLight,
  HemisphericLight,
  Mesh,
  MeshBuilder,
  PointLight,
  Scene,
  ShadowGenerator,
  SpotLight,
  TransformNode,
  UniversalCamera,
  Vector3,
  WebGPUEngine,
} from "@babylonjs/core";
import { applyPrimitivePbr, solidMat } from "./kitBuilder.ts";

export type BabylonHandles = {
  engine: WebGPUEngine;
  scene: Scene;
  camera: UniversalCamera | ArcRotateCamera;
  fpCamera: UniversalCamera;
  orbitCamera: ArcRotateCamera;
  firstPerson: boolean;
  nodes: Map<number, TransformNode>;
  shadowGen: CascadedShadowGenerator | null;
  dispose: () => void;
};

export async function createBabylonScene(
  canvas: HTMLCanvasElement,
  opts?: {
    firstPerson?: boolean;
    fogDensity?: number;
    fogColor?: string;
    skyColor?: string;
    exposure?: number;
    shadows?: boolean;
  },
): Promise<BabylonHandles> {
  if (!navigator.gpu) {
    throw new Error("WebGPU is required");
  }

  canvas.style.width = "100%";
  canvas.style.height = "100%";
  canvas.style.display = "block";
  canvas.style.background = opts?.skyColor ?? "#6a84a8";

  const engine = new WebGPUEngine(canvas, {
    antialias: true,
    adaptToDeviceRatio: true,
    powerPreference: "high-performance",
  });
  await engine.initAsync();
  engine.setHardwareScalingLevel(1);
  engine.resize();

  const scene = new Scene(engine);
  const sky = parseColor4(opts?.skyColor ?? "#6a84a8", 0.42, 0.52, 0.66);
  scene.clearColor = sky;
  scene.ambientColor = new Color3(0.28, 0.3, 0.34);
  scene.autoClear = true;
  scene.autoClearDepthAndStencil = true;
  scene.fogMode = Scene.FOGMODE_EXP2;
  scene.fogDensity = opts?.fogDensity ?? 0.012;
  scene.fogColor = parseColor3(opts?.fogColor ?? "#8aa0b8", 0.55, 0.62, 0.7);
  scene.imageProcessingConfiguration.exposure = opts?.exposure ?? 1.05;
  scene.imageProcessingConfiguration.contrast = 1.08;
  scene.imageProcessingConfiguration.toneMappingEnabled = true;

  const fpCamera = new UniversalCamera("fpCam", new Vector3(0, 1.7, 0), scene);
  fpCamera.minZ = 0.05;
  fpCamera.maxZ = 400;
  fpCamera.speed = 0;
  fpCamera.angularSensibility = 800;
  fpCamera.inertia = 0.3;
  fpCamera.inputs.removeByType("FreeCameraKeyboardMoveInput");

  const orbitCamera = new ArcRotateCamera(
    "orbitCam",
    -Math.PI * 0.45,
    1.1,
    8,
    new Vector3(0, 1.2, 0),
    scene,
  );
  orbitCamera.lowerRadiusLimit = 2;
  orbitCamera.upperRadiusLimit = 24;
  orbitCamera.minZ = 0.1;
  orbitCamera.maxZ = 500;
  orbitCamera.inputs.clear();

  const firstPerson = opts?.firstPerson !== false;
  const camera = firstPerson ? fpCamera : orbitCamera;
  scene.activeCamera = camera;
  camera.attachControl(canvas, false);
  if (firstPerson) {
    fpCamera.inputs.removeByType("FreeCameraKeyboardMoveInput");
  }

  const hemi = new HemisphericLight("hemi", new Vector3(0.25, 1, 0.15), scene);
  hemi.intensity = 0.55;
  hemi.groundColor = new Color3(0.18, 0.2, 0.22);

  const sun = new DirectionalLight("kitSun", new Vector3(-0.45, -1, -0.3), scene);
  sun.position = new Vector3(40, 60, 30);
  sun.intensity = 1.35;
  sun.diffuse = new Color3(1, 0.96, 0.88);

  let shadowGen: CascadedShadowGenerator | null = null;
  if (opts?.shadows !== false) {
    try {
      shadowGen = new CascadedShadowGenerator(1024, sun);
      shadowGen.lambda = 0.9;
      shadowGen.cascadeBlendPercentage = 0.1;
      shadowGen.bias = 0.002;
      shadowGen.normalBias = 0.02;
      shadowGen.shadowMaxZ = 80;
      shadowGen.autoCalcDepthBounds = true;
    } catch (err) {
      console.warn("[silc-game] cascaded shadows unavailable:", err);
      shadowGen = null;
    }
  }

  const nodes = new Map<number, TransformNode>();
  const onResize = () => engine.resize();
  window.addEventListener("resize", onResize);
  requestAnimationFrame(() => requestAnimationFrame(onResize));

  return {
    engine,
    scene,
    camera,
    fpCamera,
    orbitCamera,
    firstPerson,
    nodes,
    shadowGen,
    dispose() {
      window.removeEventListener("resize", onResize);
      shadowGen?.dispose();
      scene.dispose();
      engine.dispose();
    },
  };
}

export function syncTransformNode(
  handles: BabylonHandles,
  entityId: number,
  name: string,
  pos: { x: number; y: number; z: number },
  yaw = 0,
): TransformNode {
  let node = handles.nodes.get(entityId);
  if (!node) {
    node = new TransformNode(name || `e${entityId}`, handles.scene);
    handles.nodes.set(entityId, node);
  }
  node.position.set(pos.x, pos.y, pos.z);
  node.rotation.y = yaw;
  return node;
}

export function attachMesh(
  scene: Scene,
  parent: TransformNode,
  shape: string,
  size: number,
  color: string,
  shadowGen?: CascadedShadowGenerator | ShadowGenerator | null,
  materialName?: string,
  kitMaterials?: Record<string, import("./kitBuilder.ts").MaterialDef>,
): Mesh {
  let mesh: Mesh;
  if (shape === "plane") {
    mesh = MeshBuilder.CreateGround(`${parent.name}_mesh`, { width: size, height: size }, scene);
  } else if (shape === "sphere") {
    mesh = MeshBuilder.CreateSphere(`${parent.name}_mesh`, { diameter: size }, scene);
  } else if (shape === "capsule") {
    mesh = MeshBuilder.CreateCapsule(
      `${parent.name}_mesh`,
      { height: size, radius: size * 0.28 },
      scene,
    );
  } else {
    mesh = MeshBuilder.CreateBox(`${parent.name}_mesh`, { size }, scene);
  }
  mesh.parent = parent;
  mesh.position.set(0, shape === "plane" ? 0 : 0, 0);
  if (kitMaterials && Object.keys(kitMaterials).length) {
    applyPrimitivePbr(scene, mesh, color, kitMaterials, materialName || "plaster");
  } else {
    mesh.material = solidMat(scene, `${parent.name}_mat`, color);
  }
  mesh.isVisible = true;
  mesh.setEnabled(true);
  mesh.receiveShadows = true;
  if (shape !== "plane") shadowGen?.addShadowCaster(mesh);
  return mesh;
}

export function attachLight(
  scene: Scene,
  parent: TransformNode,
  kind: string,
  intensity: number,
  color: string,
  radiusM: number,
  castShadows = false,
  shadowGen?: CascadedShadowGenerator | null,
): void {
  const col = parseColor3(color, 1, 1, 1);
  if (kind === "point") {
    const light = new PointLight(`${parent.name}_light`, Vector3.Zero(), scene);
    light.parent = parent;
    light.intensity = intensity;
    light.diffuse = col;
    light.range = radiusM;
  } else if (kind === "spot") {
    const light = new SpotLight(
      `${parent.name}_spot`,
      Vector3.Zero(),
      new Vector3(0, -1, 0.15),
      Math.PI / 3,
      2,
      scene,
    );
    light.parent = parent;
    light.intensity = intensity;
    light.diffuse = col;
    light.range = radiusM;
  } else {
    const light = new DirectionalLight(`${parent.name}_sun`, new Vector3(-0.35, -1, -0.25), scene);
    light.intensity = intensity;
    light.diffuse = col;
    light.position = parent.position.clone().add(new Vector3(20, 40, 10));
    if (castShadows && shadowGen) {
      // already cascaded from kit sun; leave intensity contribution
    }
  }
}

function parseColor3(color: string, r: number, g: number, b: number): Color3 {
  try {
    if (/^#[0-9a-fA-F]{6}$/.test(color)) return Color3.FromHexString(color);
    if (/^[0-9a-fA-F]{6}$/.test(color)) return Color3.FromHexString(`#${color}`);
  } catch {
    // fall through
  }
  return new Color3(r, g, b);
}

function parseColor4(color: string, r: number, g: number, b: number): Color4 {
  const c = parseColor3(color, r, g, b);
  return new Color4(c.r, c.g, c.b, 1);
}

export { Vector3, Scene, UniversalCamera, ArcRotateCamera, applyPrimitivePbr };
