// AUTO-GENERATED BY silc — DO NOT EDIT
/** Procedural megastructure kit: PBR modular pieces from bake textures. */

import {
  Color3,
  Mesh,
  MeshBuilder,
  PBRMaterial,
  Scene,
  StandardMaterial,
  Texture,
  TransformNode,
  Vector3,
} from "@babylonjs/core";

export type KitPiece = {
  kind: string;
  size: { x: number; y: number; z: number };
  material?: string;
  collider?: string;
  coverQuality?: string;
  opening?: { x: number; y: number; z: number };
};

export type KitDef = {
  gridM: number;
  pieces: Record<string, KitPiece>;
};

/**
 * A solid box in entity-local space. Centers are relative to the entity
 * origin, which sits at the base of the piece, and `h*` are half-extents.
 */
export type ColliderPart = {
  cx: number;
  cy: number;
  cz: number;
  hx: number;
  hy: number;
  hz: number;
};

/**
 * Collision boxes matching the meshes `buildKitPiece` emits. Door pieces
 * return jambs plus a lintel so the opening stays walkable.
 */
export function kitColliderParts(piece: KitPiece): ColliderPart[] {
  const { x, y, z } = piece.size;
  if (piece.kind === "wall_door" && piece.opening) {
    const ox = piece.opening.x;
    const oy = piece.opening.y;
    const jamb = (x - ox) * 0.5;
    const lintelH = Math.max(0.2, y - oy);
    return [
      { cx: (ox + jamb) * 0.5, cy: y * 0.5, cz: 0, hx: jamb * 0.5, hy: y * 0.5, hz: z * 0.5 },
      { cx: -(ox + jamb) * 0.5, cy: y * 0.5, cz: 0, hx: jamb * 0.5, hy: y * 0.5, hz: z * 0.5 },
      { cx: 0, cy: oy + lintelH * 0.5, cz: 0, hx: ox * 0.5, hy: lintelH * 0.5, hz: z * 0.5 },
    ];
  }
  return [{ cx: 0, cy: y * 0.5, cz: 0, hx: x * 0.5, hy: y * 0.5, hz: z * 0.5 }];
}

/**
 * Material channels are either a texture path, a `#rrggbb` tint, or a scalar
 * (`roughness: 0.85`). Baked materials also carry `*Map` texture variants.
 */
export type MaterialChannel = string | number | null | undefined;

export type MaterialDef = {
  albedo?: MaterialChannel;
  normal?: MaterialChannel;
  roughness?: MaterialChannel;
  roughnessMap?: MaterialChannel;
  metallic?: MaterialChannel;
  metallicMap?: MaterialChannel;
  ao?: MaterialChannel;
  emissive?: MaterialChannel;
  alpha?: number | null;
  tiling?: number | null;
};

const textureCache = new Map<string, Texture>();
const materialCache = new Map<string, PBRMaterial>();

/** Baked texture paths are relative to the `/baked/` bundle root. */
function resolveTexturePath(path: string): string {
  if (/^(https?:)?\/\//.test(path) || path.startsWith("data:") || path.startsWith("/")) {
    return path;
  }
  return `/baked/${path.replace(/^\.\//, "")}`;
}

/** A channel is only a texture when it is a non-empty, non-hex string. */
function texturePath(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed || trimmed.startsWith("#")) return null;
  return resolveTexturePath(trimmed);
}

function scalar(value: unknown): number | null {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  return null;
}

function hexTint(value: unknown): Color3 | null {
  if (typeof value !== "string" || !/^#[0-9a-fA-F]{6}$/.test(value.trim())) return null;
  try {
    return Color3.FromHexString(value.trim());
  } catch {
    return null;
  }
}

function tex(scene: Scene, path: string, tile = 1, invertY = true): Texture {
  const key = `${path}|${tile}`;
  let t = textureCache.get(key);
  if (!t) {
    t = new Texture(path, scene, false, invertY);
    t.wrapU = Texture.WRAP_ADDRESSMODE;
    t.wrapV = Texture.WRAP_ADDRESSMODE;
    t.uScale = tile;
    t.vScale = tile;
    textureCache.set(key, t);
  }
  return t;
}

export function getKitMaterial(
  scene: Scene,
  name: string,
  mats: Record<string, MaterialDef>,
): PBRMaterial {
  const cached = materialCache.get(name);
  if (cached) return cached;
  const def = mats[name] ?? {};
  const mat = new PBRMaterial(`kit_${name}`, scene);
  mat.metallic = scalar(def.metallic) ?? (name.includes("metal") ? 0.85 : 0.05);
  mat.roughness =
    scalar(def.roughness) ??
    (name.includes("glass") ? 0.05 : name.includes("metal") ? 0.35 : 0.72);
  const tile = def.tiling ?? (name === "concrete" || name === "asphalt" ? 4 : 2);

  const albedoPath = texturePath(def.albedo);
  if (albedoPath) {
    mat.albedoTexture = tex(scene, albedoPath, tile);
  } else {
    mat.albedoColor = hexTint(def.albedo) ?? tintFor(name);
  }

  const normalPath = texturePath(def.normal);
  if (normalPath) {
    mat.bumpTexture = tex(scene, normalPath, tile);
  }

  const ormPath = texturePath(def.roughnessMap ?? def.metallicMap ?? def.roughness);
  if (ormPath) {
    mat.metallicTexture = tex(scene, ormPath, tile);
    mat.useRoughnessFromMetallicTextureAlpha = false;
    mat.useRoughnessFromMetallicTextureGreen = true;
    mat.useMetallnessFromMetallicTextureBlue = true;
  }

  const aoPath = texturePath(def.ao);
  if (aoPath) {
    mat.ambientTexture = tex(scene, aoPath, tile);
  }

  const emissivePath = texturePath(def.emissive);
  const emissiveTint = hexTint(def.emissive);
  if (emissivePath) {
    mat.emissiveTexture = tex(scene, emissivePath, tile);
    mat.emissiveColor = new Color3(0.4, 0.7, 1.0);
    mat.emissiveIntensity = 1.5;
  } else if (emissiveTint) {
    mat.emissiveColor = emissiveTint;
    mat.emissiveIntensity = 1.2;
  }

  const alpha = scalar(def.alpha);
  if (alpha != null && alpha < 1) {
    mat.alpha = alpha;
    mat.transparencyMode = PBRMaterial.PBRMATERIAL_ALPHABLEND;
  }
  if (name === "glass") {
    mat.alpha = alpha ?? 0.35;
    mat.transparencyMode = PBRMaterial.PBRMATERIAL_ALPHABLEND;
    mat.indexOfRefraction = 1.5;
  }
  materialCache.set(name, mat);
  return mat;
}

function tintFor(name: string): Color3 {
  switch (name) {
    case "concrete":
      return new Color3(0.45, 0.46, 0.48);
    case "metal":
      return new Color3(0.55, 0.58, 0.62);
    case "wood":
      return new Color3(0.42, 0.28, 0.16);
    case "glass":
      return new Color3(0.55, 0.7, 0.85);
    case "plaster":
      return new Color3(0.82, 0.8, 0.76);
    case "asphalt":
      return new Color3(0.18, 0.18, 0.2);
    default:
      return new Color3(0.5, 0.5, 0.5);
  }
}

export function buildKitPiece(
  scene: Scene,
  pieceName: string,
  kit: KitDef,
  mats: Record<string, MaterialDef>,
  parent: TransformNode,
): Mesh[] {
  const piece = kit.pieces[pieceName];
  if (!piece) {
    console.warn(`[silc-game] unknown kit piece ${pieceName}`);
    return [];
  }
  const mat = getKitMaterial(scene, piece.material ?? "concrete", mats);
  const { x, y, z } = piece.size;
  const meshes: Mesh[] = [];

  if (piece.kind === "wall_door" && piece.opening) {
    const ox = piece.opening.x;
    const oy = piece.opening.y;
    const leftW = (x - ox) * 0.5;
    const right = MeshBuilder.CreateBox(
      `${parent.name}_wr`,
      { width: leftW, height: y, depth: z },
      scene,
    );
    right.position = new Vector3((ox + leftW) * 0.5, y * 0.5, 0);
    right.material = mat;
    right.parent = parent;
    meshes.push(right);
    const left = MeshBuilder.CreateBox(
      `${parent.name}_wl`,
      { width: leftW, height: y, depth: z },
      scene,
    );
    left.position = new Vector3(-(ox + leftW) * 0.5, y * 0.5, 0);
    left.material = mat;
    left.parent = parent;
    meshes.push(left);
    const lintelH = Math.max(0.2, y - oy);
    const lintel = MeshBuilder.CreateBox(
      `${parent.name}_lintel`,
      { width: ox, height: lintelH, depth: z },
      scene,
    );
    lintel.position = new Vector3(0, oy + lintelH * 0.5, 0);
    lintel.material = mat;
    lintel.parent = parent;
    meshes.push(lintel);
  } else if (piece.kind === "wall_window" && piece.opening) {
    const body = MeshBuilder.CreateBox(
      `${parent.name}_wall`,
      { width: x, height: y, depth: z },
      scene,
    );
    body.position = new Vector3(0, y * 0.5, 0);
    body.material = mat;
    body.parent = parent;
    meshes.push(body);
    const glassMat = getKitMaterial(scene, "glass", mats);
    const pane = MeshBuilder.CreateBox(
      `${parent.name}_pane`,
      { width: piece.opening.x, height: piece.opening.y * 0.6, depth: z * 0.4 },
      scene,
    );
    pane.position = new Vector3(0, y * 0.55, 0);
    pane.material = glassMat;
    pane.parent = parent;
    meshes.push(pane);
  } else {
    const mesh = MeshBuilder.CreateBox(
      `${parent.name}_${pieceName}`,
      { width: x, height: y, depth: z },
      scene,
    );
    mesh.position = new Vector3(0, y * 0.5, 0);
    mesh.material = mat;
    mesh.parent = parent;
    mesh.receiveShadows = true;
    meshes.push(mesh);
  }

  for (const m of meshes) {
    m.receiveShadows = true;
    m.checkCollisions = false;
  }
  return meshes;
}

export function applyPrimitivePbr(
  scene: Scene,
  mesh: Mesh,
  color: string,
  mats: Record<string, MaterialDef>,
  materialName = "plaster",
): void {
  const mat = getKitMaterial(scene, materialName, mats);
  // Clone so per-mesh tint does not mutate shared kit materials.
  const clone = mat.clone(`${mesh.name}_mat`) ?? mat;
  try {
    if (/^#[0-9a-fA-F]{6}$/.test(color)) {
      clone.albedoColor = Color3.FromHexString(color);
    }
  } catch {
    // keep default
  }
  mesh.material = clone;
}

/** Fallback solid material when bake textures are absent. */
export function solidMat(scene: Scene, name: string, color: string): StandardMaterial {
  const mat = new StandardMaterial(name, scene);
  try {
    mat.diffuseColor = Color3.FromHexString(color);
    mat.emissiveColor = mat.diffuseColor.scale(0.08);
  } catch {
    mat.diffuseColor = new Color3(0.5, 0.5, 0.5);
  }
  return mat;
}
