/**
 * AUTO-GENERATED BY silc — DO NOT EDIT
 * Bun host for WebGPU game programs (ADR-012): static dist/, UDS HELLO/READY,
 * SQLite settings/saves/telemetry (shared DB with Go store).
 */
import { connect, type Socket } from "node:net";
import { join } from "node:path";
import { Database } from "bun:sqlite";

const socketPath = process.env.SILC_SOCKET || "";
const port = Number(process.env.SILC_HTTP_PORT || "18140");
const dbPath = process.env.SILC_DB_PATH || join(import.meta.dir, "..", "data", "app.db");
const protocolVersion = 1;
const abiVersion = 1;
const dist = join(import.meta.dir, "dist");

function encodeFrame(value: unknown): Buffer {
  const payload = Buffer.from(JSON.stringify(value));
  const frame = Buffer.allocUnsafe(6 + payload.length);
  frame.writeUInt32LE(payload.length, 0);
  frame.writeUInt16LE(protocolVersion, 4);
  payload.copy(frame, 6);
  return frame;
}

function decodeFrame(buffer: Buffer): { frame: any; rest: Buffer } | null {
  if (buffer.length < 6) return null;
  const length = buffer.readUInt32LE(0);
  const version = buffer.readUInt16LE(4);
  if (version !== protocolVersion) throw new Error(`unsupported Silc protocol ${version}`);
  if (buffer.length < 6 + length) return null;
  const frame = JSON.parse(buffer.subarray(6, 6 + length).toString());
  return { frame, rest: buffer.subarray(6 + length) };
}

let supervisor: Socket | null = null;
let pending = Buffer.alloc(0);

function connectSupervisor(): Promise<void> {
  if (!socketPath) return Promise.resolve();
  return new Promise((resolve, reject) => {
    supervisor = connect(socketPath);
    supervisor.on("connect", () => {
      supervisor!.write(
        encodeFrame({
          type: "HELLO",
          worker_id: "bun",
          role: "bun",
          abi_version: abiVersion,
          pid: process.pid,
        }),
      );
      supervisor!.write(encodeFrame({ type: "READY", worker_id: "bun" }));
      resolve();
    });
    supervisor.on("data", (chunk) => {
      pending = Buffer.concat([pending, chunk]);
      while (true) {
        const decoded = decodeFrame(pending);
        if (!decoded) break;
        pending = decoded.rest;
      }
    });
    supervisor.on("error", reject);
    supervisor.on("close", () => {
      supervisor = null;
    });
  });
}

function openDb(): Database {
  const db = new Database(dbPath, { create: true });
  db.exec(`
    CREATE TABLE IF NOT EXISTS game_settings (
      id TEXT PRIMARY KEY,
      data TEXT NOT NULL,
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    CREATE TABLE IF NOT EXISTS game_saves (
      id TEXT PRIMARY KEY,
      data TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
    CREATE TABLE IF NOT EXISTS game_telemetry (
      id TEXT PRIMARY KEY,
      kind TEXT NOT NULL,
      payload TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `);
  return db;
}

function contentType(path: string): string {
  if (path.endsWith(".html")) return "text/html; charset=utf-8";
  if (path.endsWith(".js") || path.endsWith(".mjs")) return "application/javascript; charset=utf-8";
  if (path.endsWith(".css")) return "text/css; charset=utf-8";
  if (path.endsWith(".json")) return "application/json; charset=utf-8";
  if (path.endsWith(".wasm")) return "application/wasm";
  if (path.endsWith(".f32")) return "application/octet-stream";
  if (path.endsWith(".png")) return "image/png";
  if (path.endsWith(".jpg") || path.endsWith(".jpeg")) return "image/jpeg";
  if (path.endsWith(".map")) return "application/json; charset=utf-8";
  return "application/octet-stream";
}

function isStaticAsset(pathname: string): boolean {
  return /\.(js|mjs|css|json|wasm|f32|png|jpe?g|map|svg|woff2?|ttf|ico)$/i.test(pathname);
}

async function main() {
  await connectSupervisor();
  const db = openDb();

  Bun.serve({
    port,
    async fetch(req) {
      const url = new URL(req.url);
      let pathname = decodeURIComponent(url.pathname);

      if (pathname === "/api/health") {
        return Response.json({
          ok: true,
          role: "bun",
          supervisor: Boolean(supervisor),
          engines: ["bun", "cpython-bake", "go"],
        });
      }

      if (pathname === "/api/settings" && req.method === "GET") {
        const row = db.query("SELECT data FROM game_settings WHERE id = ?").get("default") as
          | { data: string }
          | null;
        return Response.json(row ? JSON.parse(row.data) : {});
      }
      if (pathname === "/api/settings" && req.method === "PUT") {
        const body = await req.json();
        db.query(
          `INSERT INTO game_settings (id, data, updated_at)
           VALUES (?, ?, datetime('now'))
           ON CONFLICT(id) DO UPDATE SET data = excluded.data, updated_at = datetime('now')`,
        ).run("default", JSON.stringify(body ?? {}));
        return Response.json({ ok: true });
      }

      if (pathname === "/api/saves" && req.method === "GET") {
        const rows = db
          .query("SELECT id, data, created_at, updated_at FROM game_saves ORDER BY updated_at DESC")
          .all() as Array<{ id: string; data: string; created_at: string; updated_at: string }>;
        return Response.json(
          rows.map((r) => ({
            id: r.id,
            data: JSON.parse(r.data),
            created_at: r.created_at,
            updated_at: r.updated_at,
          })),
        );
      }
      if (pathname === "/api/saves" && req.method === "POST") {
        const body = (await req.json()) as { id?: string; data?: unknown };
        const id = body.id || crypto.randomUUID();
        db.query(
          `INSERT INTO game_saves (id, data, created_at, updated_at)
           VALUES (?, ?, datetime('now'), datetime('now'))
           ON CONFLICT(id) DO UPDATE SET data = excluded.data, updated_at = datetime('now')`,
        ).run(id, JSON.stringify(body.data ?? {}));
        return Response.json({ ok: true, id });
      }

      if (pathname === "/api/telemetry" && req.method === "POST") {
        const body = (await req.json()) as { kind?: string; payload?: unknown };
        const id = crypto.randomUUID();
        db.query(
          `INSERT INTO game_telemetry (id, kind, payload, created_at)
           VALUES (?, ?, ?, datetime('now'))`,
        ).run(id, body.kind || "event", JSON.stringify(body.payload ?? {}));
        return Response.json({ ok: true, id });
      }

      if (pathname === "/" || pathname === "") pathname = "/index.html";
      const filePath = join(dist, pathname);
      const file = Bun.file(filePath);
      if (await file.exists()) {
        return new Response(file, {
          headers: {
            "content-type": contentType(pathname),
            "cache-control": pathname.endsWith(".html") ? "no-cache" : "no-cache",
          },
        });
      }
      // Never SPA-fallback asset requests — returning HTML as JS leaves the
      // loader stuck on "Initializing" with a module parse error.
      if (isStaticAsset(pathname) || pathname.startsWith("/assets/")) {
        return new Response(`Not found: ${pathname}`, {
          status: 404,
          headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "no-cache" },
        });
      }
      const index = Bun.file(join(dist, "index.html"));
      if (await index.exists()) {
        return new Response(index, {
          headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-cache" },
        });
      }
      return new Response("Not found", { status: 404 });
    },
  });

  console.log(`silc game web listening on http://127.0.0.1:${port}/`);
}

main().catch((error) => {
  console.error("silc game worker failed:", error);
  process.exit(1);
});
